### ISSUE TITLE
Question: individual instructions on a task level with GeoJSON

### ISSUE THREAD

**Issue by camelCaseNick** [osmlab/maproulette3#1001]
I assume there is already a way to do so, since I have seen distinct instructions per task. I doubt that those were added manually, though for the unlikely case that there is no way see it as a feature request and not a request for documentation.

How should a geoJSON be structured to make use of the fields in MapRoulette that can be changed on task level and not only challenge level.

(I hope I didn't miss already existing documentation and wasting your time with not finding it.)

**Comment by nrotstan** [comment]
I don't believe we currently will set individual task instructions from GeoJSON, but we do support referencing task properties in the challenge instructions using mustache tags, which I would guess is what you are seeing on those other challenges. Truly task-specific instructions tend to be somewhat rare, but can be set either manually or through the API.

Here's what we say about those mustache tags for the Challenge Instructions:

> You can also reference feature properties from your GeoJSON with simple mustache tags: e.g. `{{address}}` would be replaced with the value of the `address` property, allowing for basic customization of instructions for each task

Let me know if that is sufficient for your needs.

**Comment by camelCaseNick** [comment]
@nrotstan That's great. And in theory, if I weren't happy with that I could just use `{{instructions}}` as the instructions. It is definitely sufficient for me. Thank you!
