### ISSUE TITLE
Filter by property, in edit mode, didn't work as expected

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1004]
![image](https://user-images.githubusercontent.com/5821688/70220024-d54bf880-1780-11ea-895f-f33c17658d5b.png)

While in edit mode, I'm trying to filter certain tasks based on the property value, "addr:province" equals "Catanduanes" and it doesn't return any task , regardless of status. I waited a few minutes more thinking it must be the processing, but nothing ever came up.

I'm not sure if this is related to issue #999 , which fails to prioritize tasks based on certain rules.

**Comment by nrotstan** [comment]
Fixed by PR #1006. Issue #999 remains under investigation.

**Comment by nrotstan** [comment]
This should now be fixed on maproulette.org
