### ISSUE TITLE
[feature request] option to call iD editor with certain features disabled/enabled.

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1012]
![image](https://user-images.githubusercontent.com/5821688/70387470-4dfcc000-19e0-11ea-8b6c-6c7957ea4cd4.png)

iD supports the ability to disable/enable certain map features, to make it more convenient for mappers to map features, especially thematic ones.

For example, working on a task that doesn't need boundaries you can call iD with an option `&disable_features=boundaries` to hide those features by default. Or, say disable all indoor features from the map, because your user is not expected to use them.

That will minimize the clutter for the contributors to a challenge, who may have no need for them to work on the tasks.

**Comment by nrotstan** [comment]
I think support for optionally customizing iD presets makes sense.

iD PR openstreetmap/Id#8243 also looks interesting, as it could be used to selectively promote certain validation issues to blocking errors and prevent the mapper from saving until those issues are fixed. We could potentially offer challenge managers the ability to customize these on a per-challenge basis.

**Comment by nrotstan** [comment]
PR #1548 adds support for restricting iD presets when creating/editing a challenge.
