### ISSUE TITLE
Map of nearby tasks not showing, and Unable to fetch next task

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1013]
![image](https://user-images.githubusercontent.com/5821688/70409964-77712680-1a88-11ea-994f-9d9b6b147c73.png)

In this [challenge](https://maproulette.org/browse/challenges/9413), after doing a task, the map of nearby tasks isn't showing up (when nearby option is selected), and since no task is selected, user gets this error message and is returned to the challenge's landing page. Same thing happens when random option is selected.

![image](https://user-images.githubusercontent.com/5821688/70408570-97eab200-1a83-11ea-9e8f-ae1e3a7cf3ef.png)

I'm working on another challenge but this error isn't happening, only in challenge 9413, and just recently (today, 12-9,2016)

**Comment by mvexel** [comment]
Works for me working on https://maproulette.org/challenge/9413/task/29381407 -- could you try again / re-confirm please? 
![Screen Shot 2019-12-09 at 1 43 16 PM](https://user-images.githubusercontent.com/120452/70471183-f450d000-1a89-11ea-8607-9c656e59c12c.png)

**Comment by govvin** [comment]
I am on Firefox when that occurred. A friend using Chrome said it was working alright.

**Comment by nrotstan** [comment]
Thanks for reporting it, @govvin . Just to clarify, you ran into the issue multiple times for that task?

I tried that task in Firefox and the Nearby map worked for me, but it's good to know that an issue may be lurking out there. Please let us know if you run into it again.

**Comment by nrotstan** [comment]
Oh wait, are saying it is still happening for you @govvin ?

**Comment by govvin** [comment]
> Oh wait, are saying it is still happening for you @govvin ?

Everything seems to be working as expected now, but for two days in a row, the observed behavior was consistent for me on Firefox and Chromium, and there had been no updates or changes from my end with regard to the browsers.

**Comment by govvin** [comment]
This issues seems to have to do with DNS. When using a different network, I am not experiencing the problem, although it's weird that it only affects a particular challenge.

**Comment by nrotstan** [comment]
I'm going to close this issue, but feel free to reopen if it continues to be a problem.
