### ISSUE TITLE
Open list with all challanges from a specific project

### ISSUE THREAD

**Issue by thibaultmol** [osmlab/maproulette3#1020]
Hi,

In the Maproulette interface there doesn't seem to be a way to get a list of all the available tasks from a certain organisation/project. 

I realized this when there was:
- No way to filter the tasks by project on the https://maproulette.org/browse/challenges page
- And clicking on this link would instinctively think that it'd take you to the page with all the tasks of that project:
![image](https://user-images.githubusercontent.com/1010226/70634263-30bf3000-1c32-11ea-8afe-6b0a8be75f0c.png)

**Comment by nrotstan** [comment]
Thanks, @thibaultmol , a project page that lists the challenges in the project was actually just added in PR #1000 and will be in the next release.

**Comment by nrotstan** [comment]
Included v3.5.1
