### ISSUE TITLE
[feature request] add shorter time periods for leaderboards , for mapathons

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1026]
![image](https://user-images.githubusercontent.com/5821688/70960379-d999df00-20b9-11ea-8146-2705328fc0c3.png)

Could we have additional options for shorter periods available?  Leaderboards for the last 4 hours?  Last 8 hours? They could be useful for tracking during mapathons.

**Comment by nrotstan** [comment]
Given the very specific need, I think the simplest thing would be to create a fresh [virtual project](https://github.com/osmlab/maproulette3/wiki/Virtual-Projects), add your mapathon challenge(s) to it, and then use that project's leaderboard for the mapathon.

I'm going to close this issue, but feel free to reopen it with further discussion if you feel strongly about it.
