### ISSUE TITLE
Edit button does not work anymore for tasks in my challenge

### ISSUE THREAD

**Issue by imajic-unimelb** [osmlab/maproulette3#1032]
I have a challenge with ~ 16 000 tasks in it - [link to challenge](https://maproulette.org/browse/challenges/11486).
Everything used to work fine with the challenge, as I have solved a number of tasks myself to make sure of it. However, recently the _Edit_ button has stopped working for tasks. Instead of opening the task in the preferred OSM editor, it just gets stuck in loading.
The only thing I have noticed in between the last time the button was working and the time it stopped working is that the MapRoulette website was down for a day (possibly for maintenance or version update).

**Comment by nrotstan** [comment]
Thanks for the report, @imajic-unimelb . This is fixed by PR #1028 in version 3.5.2, which will likely be deployed to maproulette.org early this week.

**Comment by nrotstan** [comment]
Deployment is complete, so this should be fixed on maproulette.org now.

**Comment by imajic-unimelb** [comment]
@nrotstan I can confirm the problem is now fixed for my challenge in maproulette.org! Thanks :)
