### ISSUE TITLE
New challange form data lost on resize

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/maproulette3#1033]
When filling out the new challenge form, if you change the browser window size lower than the mobile threshold then back up again all the form data you entered is cleared. This shouldn't happen, any existing input should be retained.

**Comment by nrotstan** [comment]
Thanks for reporting this, @andrewharvey . Realistically it probably isn't going to be addressed until we look at supporting the Create & Manage area on mobile devices (which would naturally solve it).

**Comment by andrewharvey** [comment]
That's unfortunate but of course as an open source project there's no expectation on this. I think a good middle ground is just to remove the "Please widen your browser window" screen and just let the full desktop layout render. At least then data you enter won't be deleted just because the window is resized.

**Comment by andrewharvey** [comment]
Or even as a short term change the ~1050px threshold could be reduced just putting two windows side my side on my what I thought was large 1920x1080 screen is enough to hit the "Please widen your browser window".

A good workaround for me is to zoom out the page to 80% that makes me get away with making the window a bit narrower before running into the issue.

**Comment by nrotstan** [comment]
Are you using side-by-side windows so that you can reference another challenge while creating a new one? If that's the case, one option might be to Clone the original challenge when creating a new one, which will set the new one up with most of the same information as the original.

**Comment by andrewharvey** [comment]
> Are you using side-by-side windows so that you can reference another challenge while creating a new one?

No it's just sometimes I work with two windows side by side and don't expect all the things I've entered into the form to be lost just because the window size was reduced.

**Comment by nrotstan** [comment]
This will be addressed by PR #1334

**Comment by nrotstan** [comment]
This is now on maproulette.org
