### ISSUE TITLE
importing a geojson with z coordinates breaks upload

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/maproulette3#1034]
When exporting a GeoJSON file from QGIS unless you untick the z coordinates button it could output GeoJSON coordinates as [lon, lat, z], it seems maproulette doesn't support this as once I tick this off the upload works (but it could also be that I've specified the file type too).

**Comment by nrotstan** [comment]
The backend does not currently support z coordinates. I'm going to close this issue, but I'd be happy to accept a PR if someone wants to submit a frontend change to reliably detect the z coordinates and generate an error during the GeoJSON validation step.

**Comment by mvexel** [comment]
I wanted to resurface this. 

Can we just drop the Z coordinates silently if we encounter them?
