### ISSUE TITLE
Mobile: Actions on Tasks-UI dont show

### ISSUE THREAD

**Issue by tordans** [osmlab/maproulette3#1046]
All of the features of the tasks UI seem to be accessible on mobile except the actions. The button changes color from black to blue but no UI shows.

Eg. https://maproulette.org/challenge/11567/task/38670021 => Chrome => Mobile Preview
Eg. iOS with blue icon
![](https://user-images.githubusercontent.com/111561/72169667-d7ccee00-33cf-11ea-8b3d-f0e853d24ec0.jpg)

**Comment by nrotstan** [comment]
Thank you for reporting this, @tordans , it's true that mobile is in a bit of limbo right now. A lot of good -- but different -- ideas/visions have been proposed. I'm going to close this issue out in favor of #1108 , which I think is the likely direction in the near term until we settle on a longer term strategy for mobile.

**Comment by tordans** [comment]
@nrotstan I love the GoMap idea but IMO this issue is still valid. At the very least the mobile UI that I see when I open the page should not be broken but inform the user, that it is unusable. Right now everything looks like it is mobile friendly, but the main UI feature does nothing without information or warning.

A minimal solution would be to show an alert on mobile saying "Editing is not possible on mobile." whenever I click the third icon on the task bar.
