### ISSUE TITLE
Create wiki page for Overpass challenges

### ISSUE THREAD

**Issue by nrotstan** [osmlab/maproulette3#1055]
Create a wiki page that describes how to correctly create a challenge using Overpass, ideally with a "cookbook" of example queries for common scenarios and a "troubleshooting" section addressing frequent mistakes and misconceptions. See #954 and #721 

The new wiki page could be referenced as additional documentation during challenge creation to fix #912 

Current help on the wiki references a general diary entry on challenge creation, which does contain some details of Overpass: https://www.openstreetmap.org/user/mvexel/diary/46863

Old MR2 wiki entry on challenge creation (since deleted): https://github.com/maproulette/maproulette2/wiki/Introducing-New-MapRoulette---Part-1.-Creating-and-Maintaining-Challenges/d67f308dadd4f736a58ab12314f3302689dcb56e

**Comment by mvexel** [comment]
MapRoulette user `Binette` made a good start with some [useful query examples](https://wiki.openstreetmap.org/wiki/User:Binnette/OverpassQueries). I'll start by linking to that from the wiki!

**Comment by Binnette** [comment]
Hi @mvexel, for sure i want to write in your wiki about Overpass friendly queries. Can you give me the write access? I will try to write a "cookbook" as requested by @nrotstan.

**Comment by nrotstan** [comment]
@Binnette Is wiki access is holding you up? If you want to create a gist I will get the content on to the wiki. Thank you for helping with this!

cc @mvexel

**Comment by Binnette** [comment]
Hi @nrotstan, I still have no write access to the wiki. I can not edit this page:
https://github.com/osmlab/maproulette3/wiki/Using-Overpass-queries-to-create-Challenges

**Comment by mvexel** [comment]
Hi @Binnette, can you create a Gist (see gist.github.com)  and link back to it in this issue, please? We will then merge it into the wiki. Thanks and sorry about the delay responding on my part.

**Comment by nrotstan** [comment]
A link to Martijn's new [wiki page](https://github.com/osmlab/maproulette3/wiki/Using-Overpass-to-create-Challenges) is now included in the updated challenge forms and deployed to maproulette.org
