### ISSUE TITLE
Unable to enter Create & Manage

### ISSUE THREAD

**Issue by cieniu9** [osmlab/maproulette3#1056]
Hi I am constantly getting a message:

"Please sign out and sign back in to regenerate a fresh home project"

will trying to go into Create & Manage. My OSM username is: cienrique

I was able to open it first time to create some invisible test challenge and now it's like that.

Regards,
Tomasz

**Comment by nrotstan** [comment]
Thanks for reporting this, @cieniu9. Can you also try signing out of OpenStreetMap as well if you haven't already?

**Comment by cieniu9** [comment]
nothing is helping

**Comment by nrotstan** [comment]
Ok, thanks. Which browser are you using? Can you try a different one to see if anything changes? Any other additional details you can provide would be helpful. We haven't received any other reports of this happening, so something unusual seems to be going on.

**Comment by nrotstan** [comment]
I'm going to close this, but feel free to reopen with additional details if it continues to be an issue for you.
