### ISSUE TITLE
[question] adding additional challenge managers?

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1061]
Is there a way to add additional challenge managers?

**Comment by nrotstan** [comment]
Yes, managers are setup at the project level and their permissions apply to all challenges in the project. If you go to the management page for your project there should be a Project Managers widget, probably at the bottom left. If not, you can add the widget.

<img width="507" alt="project_managers" src="https://user-images.githubusercontent.com/445970/72627217-f3b91e00-3900-11ea-995b-1471ff10f4c8.png">

If you need to control the managers separately for multiple challenges that are currently in the same project, you would need to setup multiple projects and move the challenges to the appropriate projects. If you like having the challenges all together for the purpose of organization or statistics, you could then take the further step of creating a virtual project and adding all of the challenges to the virtual project. That would let you see their stats aggregated together and give you a single project where you could see everything while maintaining different challenge managers for the various challenges (unlike normal projects, virtual projects don't confer any challenge management permissions). You can read more about virtual projects on the [wiki](https://github.com/osmlab/maproulette3/wiki/Virtual-Projects).

**Comment by govvin** [comment]
Thank you @nrotstan .

Something unexpected is happening.  Every time I try to add the user [maning](http://hdyc.neis-one.org/?maning) as admin, a different user "BrunoC" is added as a project manager:
![image](https://user-images.githubusercontent.com/5821688/72655288-ccc91d80-39ce-11ea-8e43-dfc36f46df35.png)

So far, it's only happening whenever I try to add Maning, but other user accounts I've added seem to work as expected
