### ISSUE TITLE
[question] is there a way to review tasks not tagged for review?

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1068]
For project managers, is there an interface for reviewing challenge tasks, especially those that has been worked on by contributors, and not necessarily tagged by the contributors for review?

**Comment by nrotstan** [comment]
No, there isn't. Requesting a review is currently a voluntary operation.

**Comment by nrotstan** [comment]
I should mention that if you "inspect" a task from the challenge management page, the Task History widget shows the OSMCha and Diff options just as it does in task review, so it should still be fairly straightforward to examine changes. But you can't formally review the task.

We don't show the Task History widget by default, so you may need to add it to your layout if you don't see it.
