### ISSUE TITLE
Complete together count discrepancy

### ISSUE THREAD

**Issue by DavidMetcalfe** [osmlab/maproulette3#1086]
It appears that the MapRoulette UI counts tasks differently depending on the view/module being used.

The "WORK ON MULTIPLE TASKS TOGETHER" view in the included screenshot shows 2 tasks selected, yet the "COMPLETION" view advises that 3 tasks are selected.

Example task URL if needed: https://maproulette.org/challenge/11530/task/38188435

![image](https://user-images.githubusercontent.com/80915/73302500-9444f300-41c9-11ea-95c1-1ef4e03423cf.png)

**Comment by DavidMetcalfe** [comment]
Additionally: When I select "Complete Together" the counter in the "COMPLETION" view changes to reflect the correct number (2).

![image](https://user-images.githubusercontent.com/80915/73302699-e84fd780-41c9-11ea-8084-45bc795fdf54.png)

**Comment by nrotstan** [comment]
Thanks for the report, @DavidMetcalfe . PR #1089 has been submitted to fix this.
