### ISSUE TITLE
Explain 'blurb'

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#110]
Make clear where the text is going to be used, how changing a value will affect behavior, etc.

I'll create a doc to work on this a bit more.

**Comment by nrotstan** [comment]
We've made some progress on this with PR #120 in alpha.5, but there is certainly further room for improvement.

**Comment by mvexel** [comment]
Related to #96 I will refer to the fields in a challenge creation guide I will start working on this week. We can then link to this document for more background.

**Comment by mvexel** [comment]
I think the only field that is really unclear to people is 'blurb'. I will rename the issue accordingly.

**Comment by nrotstan** [comment]
Closing due to age.
