### ISSUE TITLE
GoMap!! integration

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1108]
Proposed in the GoMap!! repository is an integration with MapRoulette, showing tasks as an overlay.

Thinking of what we may need from the MapRoulette side...
1. A simplified / mobile friendly task page that can be loaded in a GoMap!! view
2. A filter for 'local' challenges?

See https://github.com/bryceco/GoMap/issues/240

**Comment by nrotstan** [comment]
PRs #1164 and maproulette/maproulette2#720 add support for "local" challenges where on-the-ground knowledge is desired or required for task completion.

**Comment by nrotstan** [comment]
This is now available on maproulette.org
