### ISSUE TITLE
changing priority rules are unsuccessful 

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1110]
In the past several days, I've been unsuccessful with changing the priorities of certain tasks

When I filter tasks by property there are matching tasks available and only in the low, medium priority:
![image](https://user-images.githubusercontent.com/5821688/74219930-203a3d00-4ce9-11ea-9b66-782aa124431a.png)

I would like the same tasks set to High so I changed the priority rules to use the same property filter, but it doesn't appear to be doing so. Am I misunderstanding how this works?

**Comment by nrotstan** [comment]
Hi @govvin can you provide some more details on what you're trying to do and what is happening? I've just tried reprioritizing tasks based on a property and it seemed to work. Also, can you take another look at the challenge and see if it's still incorrect? Maproulette has been a little bit sluggish recently and may be taking longer to reprioritize than usual.

If it's still incorrect, details about the challenge, the filters you're setting up, etc. would be helpful in aiding an investigation.

**Comment by govvin** [comment]
Hi @nrotstan .

I was just reviewing the [challenge](https://maproulette.org/challenge/9413), and for some reason, the priority rules are now empty:
![image](https://user-images.githubusercontent.com/5821688/74286971-e0646b80-4d63-11ea-9cdc-8978723f3a17.png) . 

I'm pretty sure there were existing rules we were using before that worked okay, and I'm not sure what happened here. I'll setup the rules again, and get back to this.

**Comment by nrotstan** [comment]
I think PR maproulette/maproulette2#788 will likely address the problem with updated priority rules sometimes not being applied
