### ISSUE TITLE
Error when trying to to add a project manager

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1122]
I get this error message when I try to add `maning` to a [project](https://maproulette.org/admin/project/39181) where I have admin privileges: ![image](https://user-images.githubusercontent.com/5821688/75016017-01942d00-54c5-11ea-87a2-6d7570a3cc91.png)

**Comment by DavidMetcalfe** [comment]
I'd say the title can be changed to apply more broadly. The server doesn't seem to be processing requests of any kind. Simply loading the website homepage or the Leaderboard elicits this failure.

![image](https://user-images.githubusercontent.com/80915/75082727-eaa40980-54c9-11ea-9bdc-a2f1d2b96c61.png)

**Comment by govvin** [comment]
Thank you for the comment, @DavidMetcalfe . 

That wasn't true in my case. I can use the other features of the website, and it was only this that wasn't working.

**Comment by nrotstan** [comment]
This should work now, @govvin. Let me know if you have further issues.
