### ISSUE TITLE
intermitttent tags get split when text has space

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1123]
I have preferred tags:

![image](https://user-images.githubusercontent.com/5821688/75016249-82ebbf80-54c5-11ea-9eb3-424245f5e515.png)

but some of tags are intermittently split into two when adding or editing tags. For example, here "found it!" is supposed to be just one tag, but is split into "found" and "it!". 

Sometimes they work alright, but when editing preferred tags existing other tags could get split.

**Comment by nrotstan** [comment]
This should now be fixed on maproulette.org
