### ISSUE TITLE
requesting takedown of malformed challenge (trace_zoom)

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/maproulette3#1134]
https://maproulette.org/challenge/12836/task/42414217 is useless at best, harmful at worst

> add trace_zoom=* if non-exist, ensure to match zoom
> add trace_zoom:range=* if non-exist, to indicate approx. trace_zoom levels

This tags are not documented and appear to be adding to OSM data tags about aerial images quality what is unwanted, undesirable and unnecessary.

I contacted also one of apparently main users of that challenge ( https://www.openstreetmap.org/changeset/81459367 ) and tried to contact author of challenge ( https://www.openstreetmap.org/user/Mapping%20Human ) based on description of it in maproulette.

Note that this was triggered by post to mailing list by someone who also was confused by situation.

**Comment by mvexel** [comment]
Hi @matkoniecz , the first step would be to message the author through OSM, which would be https://www.openstreetmap.org/message/new/EditConscript in this case. If you receive no response, and there is consensus in the community that this Challenge actually causes harm to the OSM data, we can follow up here. Let us know what you find out.

**Comment by matkoniecz** [comment]
I already pinged him/her at https://www.openstreetmap.org/changeset/81459367 - I now commented again now that I know that (s)he is also author of this challenge

**Comment by FutureLearnSole** [comment]
Upon inspection of the changesets, node coordinates seem to be more aligned to the most recent imageries, with addition of tags that would be appropriate to the needs of the project. There is no harm/vandalism done asides from tag wars here

**Comment by FutureLearnSole** [comment]
Please see Just Map https://wiki.openstreetmap.org/wiki/Just_Map Any tags you like https://wiki.openstreetmap.org/wiki/Any_tags_you_like

**Comment by FutureLearnSole** [comment]
, data is not worldwide and kept constrained in boundary, Palm Bay, FL.

**Comment by FutureLearnSole** [comment]
1. Please see MR task https://maproulette.org/challenge/12882/task/42444809 and inspect it with several different imageries. I invite bright members of the community to place forth your observations.



2. Please be mindful of your colorful language, your words will determine if it is welcoming of new members that literally was once zero knowledge in the world of mapping. You will not bully me or coerce me into taking actions that please only your self interest.



3. I had done all my efforts with the intent that it helps than harm OSM data. I have thoughts of future use before uploading. It may not be useful to you very apparently, but it will be for those who place the time and effort to work it out with me. So if you are not going to hold my hand, then let me be the one doing it.



4. How dare you smear MapRoulette, a platform that allows me to help other members of the OSM community? I am proud to have helped another OSM member in his projects to put together the data essential to his/her project needs in their bicycling/car community! See MR project https://maproulette.org/browse/challenges/11530, https://maproulette.org/browse/challenges/12376. Again, if you aren't going to be the ones improving the website don't be colorful with your words!



Bye,

**Comment by FutureLearnSole** [comment]
https://github.com/matkoniecz is quick to degrade a members efforts at best and is not very helpful at worst, in many situations

**Comment by mvexel** [comment]
Hi all, this discussion has become uncivil in tone, and off-topic. I will close this issue.

@FutureLearnSole If you want to participate in discussions here in the future, please consider your language carefully.
