### ISSUE TITLE
Add time spent mapping to export .csv

### ISSUE THREAD

**Issue by nathanopen** [osmlab/maproulette3#1161]
It would be helpful for Project Managers to know how much time is spent mapping per task.  This can help with both planning how long a challenge/project may take, and also identifying trends within a challenge/project.

**Comment by nrotstan** [comment]
Thanks for the feedback, @nathanopen! A new `CompletionTime` CSV column is included in the v3.5.7 release, which was tagged yesterday and will be deployed to maproulette.org on Monday. However, it will only have data for tasks completed going forward (post-deployment).

**Comment by nrotstan** [comment]
This is now available on maproulette.org
