### ISSUE TITLE
Unchecking 'Task Feature' in the map widget reset the zoom level

### ISSUE THREAD

**Issue by jgscherber** [osmlab/maproulette3#1167]
Unchecking the 'Task Feature' item in the map view resets the zoom to the level that's required to show the whole feature. Because the feature is being hidden, being able to see it's extent shouldn't be important.

Use case - I was doing the [lane quick task challenge](https://maproulette.org/challenge/12945/). I zoomed all the way in on the map to better see the lane markers and the task feature was blocking the the details, when I hid that item it zoomed me back out and I had to zoom in again.

![image](https://user-images.githubusercontent.com/6207661/76561878-30714380-6472-11ea-99ec-a6b3a8e39c9e.png)

**Comment by nrotstan** [comment]
This should now be fixed on maproulette.org
