### ISSUE TITLE
Challenge leaderboard showing inaccurate point totals

### ISSUE THREAD

**Issue by DavidMetcalfe** [osmlab/maproulette3#1168]
Hi there,

This is probably not unique to a particular challenge, but I'm a bit tight on time for investigating this one at the moment. Challenge https://maproulette.org/challenge/12061/ has 1,087 tasks total, 25 (2%) of which have been completed.

Despite this, the challenge leaderboard's Top 10 is providing the lifetime points of a user instead of the challenge-specific points for all but three of the users (andrewwiseman, David Metcalfe, PkBuzios). 

![image](https://user-images.githubusercontent.com/80915/76664384-6df0d200-6541-11ea-9c47-cc54c7c1270a.png)

**Comment by nrotstan** [comment]
This should now be fixed on maproulette.org

**Comment by DavidMetcalfe** [comment]
Hard to tell from the surface, but it looks like erroneous data is being passed to the client and then this is being filtered down to the valid data?

Upon loading the leaderboard, the following is shown:

![image](https://user-images.githubusercontent.com/80915/77608232-db094d80-6ed9-11ea-9642-2767d134ca12.png)

And then moments after, it changes to this:

![image](https://user-images.githubusercontent.com/80915/77608260-e8bed300-6ed9-11ea-83a4-6f4ca8678459.png)

**Comment by nrotstan** [comment]
PR #1195 addresses temporary display of incorrect results

**Comment by nrotstan** [comment]
Transient display of incorrect results during loading should now be fixed on maproulette.org
