### ISSUE TITLE
@mentioning people in comments

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1171]
In the comments, I'd like to be able to @mention users. They would then get a message through MapRoulette (if they have a MR account) or through OSM (if they're not)

**Comment by nrotstan** [comment]
This is supported and should be working, though there isn't any indication to the comment author.

**Comment by mvexel** [comment]
Incredible, we should make that more apparent then. Incremental search triggered by typing `@`

**Comment by mvexel** [comment]
I got your test @mention ... Would be good if that message could then turn into a conversation!

**Comment by nrotstan** [comment]
PR #1183 expands user mentions into links in the rendered (or previewed) comment.

**Comment by mvexel** [comment]
That was merged some time ago, closing
