### ISSUE TITLE
Comparing last edit on feature with task age

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1172]
I'd like to be alerted if an OSM object's last modified timestamp is after the last task status update. Alternatively be able to inspect object's history in some simplified way.

**Comment by nrotstan** [comment]
Related: #1390

**Comment by nrotstan** [comment]
I'm closing this as we now offer the OSM History widget that will both show you the history and include a warning icon if the OSM element was modified since the task was created.
