### ISSUE TITLE
Bad request when cloning a challenge

### ISSUE THREAD

**Issue by cbeddow** [osmlab/maproulette3#1188]
I select a challenge of my own, click clone challenge, then change the name, edit the hashtags, upload a new local file geojson, click next and next, click finish, and the page jumps to top, but no error message.

In the console I see:

![image](https://user-images.githubusercontent.com/10554922/77253995-6d9db880-6c5e-11ea-8289-e324d5bb4915.png)

**Comment by cbeddow** [comment]
Following it up, it seems to be when I edit the hashtags in the cloned version that this happens. If I do not edit the hashtags, it goes on fine.

**Comment by nrotstan** [comment]
Thanks for the detailed bug report, @cbeddow . I've submitted PR #1189 to address this.

**Comment by nrotstan** [comment]
This should now be fixed on maproulette.org
