### ISSUE TITLE
Overpass down ?

### ISSUE THREAD

**Issue by nlehuby** [osmlab/maproulette3#1193]
Hi,

For a few days, I can't update my old challenges or create new ones using overpass.
When building the tasks, I always get this message:
```Read timeout to overpass-api.de/178.63.11.215:80 after 120000 ms```

**Comment by nrotstan** [comment]
Hi @nlehuby , thanks for letting us know! I just tried and am able to create a challenge using a simple Overpass query. Is it possible your queries are large/expensive and just taking a long time? Do they work if you run them on [Overpass](http://overpass-turbo.eu/) directly?

**Comment by nlehuby** [comment]
yes, it may be because the queries are too large (I have this issue with challenges on the whole France country). But I do test all queries in Overpass turbo first and they never timed out :thinking:

**Comment by mvexel** [comment]
Hi @nlehuby -- are you still having issues? If so we're happy to further support, if not we'll close the issue.

**Comment by nlehuby** [comment]
I still have this issue from time to time when updating large challenges.

**Comment by mvexel** [comment]
There could just be a timeout then -- you can override the default timeout for your query in the same way you would do in Overpass Turbo / regular Overpass: https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#timeout:
Let us know if that helps.
Thanks for reporting!

**Comment by nrotstan** [comment]
I'm going to close this, but feel free to reopen if you are still experiencing Overpass issues that you think are related to MapRoulette.
