### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by ignaciolep** [osmlab/maproulette3#1196]
Hi, I've been working with the Spanish translation. Now it's 100% complete and I've also corrected several string that were wrong.
Can you update the web to use the new translations?
Thanks!
Ignacio

**Comment by nrotstan** [comment]
Thank you for this, @ignaciolep ! It's much appreciated. We'll pull in the latest translations as we approach the next release candidate. I'll leave this open until we've done that.
