### ISSUE TITLE
virtual projects are turning into "real" projects?

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1207]
I noticed today that some of the virtual projects I maintain has turned into "real" projects, and trying to add new challenge sends me to creating a new challenge instead.

**Comment by nrotstan** [comment]
Thanks @govvin , can you provide the ids of the (formerly) virtual projects where this has occurred? You can navigate to them in Create & Manage and then grab the ids from the URL (e.g. `admin/project/XXXX` where XXXX is the id).

**Comment by govvin** [comment]
Hi @nrotstan 

I have the following:
* 39612
* 40200

**Comment by govvin** [comment]
Could you help with restoring these back to its virtual status?

**Comment by nrotstan** [comment]
@govvin They should now be restored

**Comment by govvin** [comment]
FYI. Indeed, the virtual project containers was restored, but the original challenges are no longer there.

**Comment by govvin** [comment]
After hitting the "done" button from challenge management, it appears that they've been restored. Sorry for the bother.
