### ISSUE TITLE
"Unable to render the map / API key warning"

### ISSUE THREAD

**Issue by mboeringa** [osmlab/maproulette3#1214]
Hi,

After creating a new challenge, each time I try to open it, I get the following message. If I click the red cross to dismiss the warning, I can continue with using the challenge:

Anything I need to change in the challenge's settings, or is this is known current issue?

![afbeelding](https://user-images.githubusercontent.com/7635726/80233555-efff0b00-8656-11ea-8510-6542ce74c7c5.png)

**Comment by nrotstan** [comment]
Hi @mboeringa that looks like an incorrectly configured map layer. Which map layer did you choose for your challenge? Or is it a custom layer?

**Comment by mboeringa** [comment]
Hi @nrotstan ,

Thanks for the quick response, the Challenge Basemap is just OpenStreetMap (Standard) layer, see screenshot, or is there another place I need to configure something?

https://maproulette.org/admin/project/40318/challenge/13209

Note that this is a **cloned** challenge, and I deleted the original one. I made a minor mistake with the Overpass query, and then noticed I couldn't edit it, which is another issue: https://github.com/osmlab/maproulette3/issues/783. Maybe allowing the owners to at least edit the data source for one or a few days, could help with the latter issue, instead of blocking it outright.

![afbeelding](https://user-images.githubusercontent.com/7635726/80236672-be3c7300-865b-11ea-9a1e-b6b18650c570.png)

**Comment by nrotstan** [comment]
That challenge works for me, @mboeringa . Have you by chance configured a default layer in your User Settings?

**Comment by mboeringa** [comment]
@nrotstan 

No, it is set to "None".

I do see an API key listed in the User Settings though, what is its function there, and is this the API key the error refers to?

**Comment by nrotstan** [comment]
No, that error occurs when MapRoulette tries to load a map layer from a 3rd-party service that itself requires an api key, but no api key has been included or setup for the layer. The error is most often seen when someone sets up a custom base map to a 3rd-party service and forgets to include an api key for that service.

As far as I can tell, that challenge looks setup correctly and it's working fine for me. Can you try refreshing the page in your browser and see if you continue to experience the error?

**Comment by mboeringa** [comment]
> Can you try refreshing the page in your browser and see if you continue to experience the error?

@nrotstan . For some reason, and with many other TABs open, I hadn't yet thought of refreshing the page. That indeed seems to fix it _for that session_.

However, when I close the TAB (also signing out), and reopen a new one and subsequently clicking **Sign In**, I see the same message pop up _**just before**_ the OpenStreetMap login page is opened, which then of course replaces the page.

**Comment by nrotstan** [comment]
The OpenCycleMap layer wasn't configured properly and was missing an API key. It has now been setup with an API key. I believe that will resolve any remaining problems related to this error, but let me know if you continue to experience it.

**Comment by mboeringa** [comment]
Thanks @nrotstan .

All seems fine now. 

Yesterday, but you are probably aware of that, the situation worsened in that I could not access MapRoulette challenges at all. There was another warning that no challengens could be found, as if the system was down, and none were shown / accessible.

This seems to have been resolved now though.
