### ISSUE TITLE
Accessing website: Unable to retrieve data from server

### ISSUE THREAD

**Issue by adrienandrem** [osmlab/maproulette3#1216]
Accessing [maproulette.org](https://maproulette.org),  
this error message is displayed:

![maproulette_bug](https://user-images.githubusercontent.com/6804697/80312414-1a65db00-87b3-11ea-9013-da0fc0c9d2f1.png)

**Comment by nrotstan** [comment]
Thanks for the report, looking into it now.

**Comment by nrotstan** [comment]
This should now be resolved.
