### ISSUE TITLE
Unable to retrieve latest challenge data from server

### ISSUE THREAD

**Issue by adrienandrem** [osmlab/maproulette3#1217]
Once logged-in to contribute to a challenge, after some time a popup appears, with the error:

> Unable to retrieve latest challenge data from server.

@nrotstan this might be related to [#1216](https://github.com/osmlab/maproulette3/issues/1216)

**Comment by nrotstan** [comment]
This should be addressed by PR maproulette/maproulette2#771

**Comment by nrotstan** [comment]
This should now be fixed on maproulette.org
