### ISSUE TITLE
Custom imagery from OpenAerialMap is not loading in editors

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1230]
Hi! 

I'm working on a [challenge](https://maproulette.org/challenge/13450) that uses a layer from OpenAerialMap, which displays correctly on MR but doesn't load the layer in the editor ( iD, or JOSM) automatically

Have I missed any setting?

**Comment by nrotstan** [comment]
No, we'll need to add support for that. Thanks for mentioning it.

**Comment by nrotstan** [comment]
This is now available on maproulette.org
