### ISSUE TITLE
when sign-in has expired, user is unable to lock a timed-out task

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1233]
![image](https://user-images.githubusercontent.com/5821688/82000994-9c4b7480-968c-11ea-822d-bed591c61348.png)

When a user's sign-in to MR has expired, and they are working on a task, they won't be able to re-lock on the task, and the modal window doesn't inform them of the fact that they were signed-out.

Suggested fix: Offer user to log-in again,  and then re-lock the task if it's still availble.

**Comment by nrotstan** [comment]
Good catch, thanks!
