### ISSUE TITLE
Rendering issues in Task instruction related to the forms option

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1239]
Two issues rendering the text when using the triple-mustache form shorthand:

 * Non-ASCII characters are not decoded correctly
 * Inside the form label, a combination of regular double-mustache with markdown ** renders the actual HTML tag instead of the **strong** text.

Below example demonstrates both:

```
{{{select "What would you do with this **{{highway}}** road?" name="tiger_decision" values="leave as is - it's good,change highway value,improve alignment,delete altogether"}}}
```

<img width="350" alt="Screen Shot 2020-05-19 at 9 09 33 AM" src="https://user-images.githubusercontent.com/120452/82343773-7be32900-99b0-11ea-8ea7-867785de9931.png">
<img width="368" alt="Screen Shot 2020-05-19 at 9 09 24 AM" src="https://user-images.githubusercontent.com/120452/82343780-7d145600-99b0-11ea-9d9f-4bf653906023.png">

**Comment by nrotstan** [comment]
Fixed in v3.6.2
