### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by ignaciolep** [osmlab/maproulette3#1262]
Hi, I'm Spanish translator and reviewer in transifex.com/osmlab/maproulette3

As you can see there, all Spanish strings are 100% translated.

I waited a new release (3.6.3) to be sure all translated string be in production, but I found several strings missing (in English). Some of them seems to be translated in Transifex but not used in production, some other could be missing in transifex.

I attached 9 screenshots where I highlighted the problems, but it would be better to set your language to Spanish (100% translated) and walk thru the screens to check the strings that are still in English.

Thanks!
Ignacio

![MapRoulette](https://user-images.githubusercontent.com/13091755/84081147-d0783380-a9b3-11ea-92fd-d2d5ff83ed13.png)
![MapRoulette (1)](https://user-images.githubusercontent.com/13091755/84081209-e84fb780-a9b3-11ea-9625-3fa2f975b4fc.png)
![MapRoulette (2)](https://user-images.githubusercontent.com/13091755/84081205-e685f400-a9b3-11ea-9bc5-9b682721ea77.png)
![MapRoulette (3)](https://user-images.githubusercontent.com/13091755/84081199-e554c700-a9b3-11ea-816a-5aac819f01ff.png)
![MapRoulette (4)](https://user-images.githubusercontent.com/13091755/84081195-e4239a00-a9b3-11ea-90f4-f9cbd778b30f.png)
![MapRoulette (5)](https://user-images.githubusercontent.com/13091755/84081192-e259d680-a9b3-11ea-8f4d-3285026a2193.png)
![MapRoulette (6)](https://user-images.githubusercontent.com/13091755/84081185-dec64f80-a9b3-11ea-98b1-d6c51f34a041.png)
![MapRoulette (7)](https://user-images.githubusercontent.com/13091755/84081182-de2db900-a9b3-11ea-8332-cdfa2984661b.png)
![MapRoulette (8)](https://user-images.githubusercontent.com/13091755/84081179-dd952280-a9b3-11ea-9bc8-0e54f015fa3b.png)

**Comment by nrotstan** [comment]
Thanks for all of your great work @ignaciolep ! I saw that you had done those and really, really appreciate it. I usually update the translations just before release, but it slipped my mind this time. I realized I had forgotten to update them right after the new release went out. :-( My apologies. I will be very sure to get them into the next release.

I'll also look at getting those missing strings into the translation file. Thanks for pointing those out, and my apologies again for the mixup.

**Comment by ignaciolep** [comment]
No problem! Thank you!!

**Comment by nrotstan** [comment]
Translations are now updated on maproulette.org. I'll leave this issue open until the identified missing strings have been added to the translation file.

**Comment by Andygol** [comment]
@nrotstan I see similar issue for Ukrainian translation when everything except text on start page is localized.
![image](https://user-images.githubusercontent.com/369696/97630451-4e5adb00-1a38-11eb-8746-b4b1c232bd02.png)

It is frustrating as this is only one language with 100% of translation on Transifex 😢 
![image](https://user-images.githubusercontent.com/369696/97631423-9dedd680-1a39-11eb-8457-fe65f8a82185.png)

**Comment by nrotstan** [comment]
Thanks for the reminder, @Andygol , I'll try to get most those into the next version.

**Comment by nrotstan** [comment]
I think I've addressed most of these now and made the new messages available on transifex.

**Comment by nrotstan** [comment]
v3.6.14 was released today and is now on maproulette.org so I'm going to close this issue, as I believe most of the identified messages have been addressed. Let's open a new issue for any further messages that need to be internationalized.
