### ISSUE TITLE
Maproulette: User Metric 'Custom' per Day meteric is broken

### ISSUE THREAD

**Issue by v-cofor** [osmlab/maproulette3#1289]
Hi if you go to the User Metric Tab on MapRoulette, in the middle of the page where you see "Completed Tasks" you use to be able to filter by date to tell how many tasks you completed in any one give day, this is currently broken as it just shows 0% and no tasks completed for anyone. This is useful for workflows to determine performance, and would improve performances for those that have a goal to hit.

![image](https://user-images.githubusercontent.com/67337355/85439625-0edc2980-b542-11ea-9992-87b2a5c11845.png)

**Comment by nrotstan** [comment]
Thanks for the report, @v-cofor !
