### ISSUE TITLE
Creating a Tag Fix challenge doesn't give the expected UI result

### ISSUE THREAD

**Issue by kmpoppe** [osmlab/maproulette3#1328]
Good evening,

I've tried creating a Tag Fix challenge using a GeoJSON as described in the [wiki](https://github.com/osmlab/maproulette3/wiki/Cooperative-Challenges#creating-tag-fix-challenges).

My GeoJSON looks like this, but with loads more entries:

```
{
   "type":"FeatureCollection",
   "generator":"overpass-ide",
   "copyright":"The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.",
   "timestamp":"2020-07-20T20:38:04Z",
   "features":[
      {
         "type":"Feature",
         "properties":{
            "@id":"way\/5219528",
            "addr:city":"Bedford",
            "addr:country":"GB",
            "addr:housenumber":"1",
            "addr:postcode":"MK41 0UE",
            "addr:street":"Riverfield Drive",
            "amenity":"restaurant",
            "brand":"Harvester",
            "brand:wikidata":"Q5676915",
            "brand:wikipedia":"en:Harvester (restaurant)",
            "building":"commercial",
            "contact:website":"https:\/\/www.harvester.co.uk\/restaurants\/eastofengland\/theorchardbedford",
            "cuisine":"american",
            "fhrs:id":"97406",
            "name":"The Orchard",
            "phone":"+44 1234 271339"
         }
     }
   ],
   "cooperativeWork":{
      "meta":{
         "version":2,
         "type":1
      },
      "operations":[
         {
            "operationType":"modifyElement",
            "data":{
               "id":"way\/5219528",
               "operations":{
                  "operation":"setTags",
                  "data":{
                     "opening_hours":"Mo-Su 09:00-23:00",
                     "opening_hours:kitchen":"Mo-Su 11:30-22:00",
                     "breakfast":"Mo-Su 09:00-11:30"
                  }
               }
            }
         }
      ]
   }
}
```

Yet, creating a challenge in a project off of it yields nothing different than with the same JSON without the `cooperativeWork` object.

Am I missing a step? Is there a typo in the object names that I just don't see?

Any input would be appreciated!

Kai

**Comment by nrotstan** [comment]
Hi @kmpoppe , the `operations` field in your `data` object needs to be an array of objects.

Also, just in case you're not aware, there is a [mr-cli](https://www.npmjs.com/package/@maproulette/mr-cli) command-line tool that can generate the cooperative JSON for you depending on your situation.

**Comment by nrotstan** [comment]
Also @kmpoppe , you can upload your updated GeoJSON using the "Rebuild Tasks" option when managing the challenge.

**Comment by camelCaseNick** [comment]
I cannot get the cooperative challenge to work properly as well. I have an array of dependent operations per independent operation:

    {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {
            ...
            "@id": "node/1689201130"
          },
          "geometry": {
            "type": "Point",
            "coordinates": [ ... ]
          }
        }
      ],
      "cooperativeWork": {
        "meta": {
          "version": 2,
          "type": 1
        },
        "operations": [
          {
            "operationType": "modifyElement",
            "data": {
              "id": "node/1689201130",
              "operations": [
                {
                  "operation": "setTags",
                  "data": {
                    "wikidata": "Q67087359"
                  }
                }
              ]
            }
          }
        ]
      }
    }

**Comment by kmpoppe** [comment]
Yeah, same for me, I changed the operations -> data -> operations-object to be an Array, but there's no change.
I'll just check what mr-cli delivers for an .osm file.

**Comment by kmpoppe** [comment]
Strangely, it works with mr-cli from an .osm ... but I cannae see the difference YET. Watch this space.

**Comment by nrotstan** [comment]
@kmpoppe @camelCaseNick Just to be clear, this is only supported for the [line-by-line format](https://github.com/osmlab/maproulette3/wiki/Line-by-Line-GeoJSON-Format) of GeoJSON. I'm assuming you pretty-printed the JSON for your examples above, but if not then that could also be part of the problem.

**Comment by kmpoppe** [comment]
@nrotstan Yeah ... This was pretty much what I just discovered. Reading said wiki again it tells me, that line-by-line is required, but why would it RTFM be a thing 🤦 .
Thanks for pointing it out ... again!

**Comment by kmpoppe** [comment]
Closing Issue as it's not a problem in the code but 70cm in front of it 😆

**Comment by nrotstan** [comment]
Sorry that wasn't clearer. I've updated the wiki page with a warning in the GeoJSON section to try to make it more obvious.

**Comment by kmpoppe** [comment]
Thanks, Neil!
There's a small typo in the text:
`**_Ony_** line-by-line GeoJSON is supported for cooperative challenges.`
Can't change that myself sadly.

**Comment by nrotstan** [comment]
Thanks for catching that! Fixed.
