### ISSUE TITLE
Unable to find users with modified usernames

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1336]
When adding credentials for project managers, I was unable to find matching users who has changed their usernames as would be expected.

I tried this with a user "ᴎivvOG" but the username didn't get a match
![Screenshot_20200728-114718_Firefox](https://user-images.githubusercontent.com/5821688/88617002-2de15480-d0c8-11ea-9a45-abb5d07a76f5.jpg)

However, you can match them with their original username, in this case the user "GOvvin".

**Comment by nrotstan** [comment]
Do you know if the user logged in to MapRoulette with their new OSM username? MR will update usernames, but I believe it happens at login. If the user hasn't signed in to MapRoulette since changing their OSM username, MR will still have the old one.

**Comment by govvin** [comment]
Apparently, they haven't logged back in since the name change, but after the login it's indeed searchable. 

Thanks for elaborating.
