### ISSUE TITLE
Increase the size of the loading circle

### ISSUE THREAD

**Issue by thibaultmol** [osmlab/maproulette3#1343]
Hi, 

Please consider making the circle loading indicator on the map larger and thicker so it's easier to notice.
Newcomers to the platform will zoom into an area and nothing will appear (because it's still loading) but it's so small that some people might not notice it.

Cheers

**Comment by nrotstan** [comment]
Thanks for the feedback, @thibaultmol ! I've submitted PR #1344 to make the busy spinner larger.

**Comment by nrotstan** [comment]
This is now on maproulette.org
