### ISSUE TITLE
JOSM shortcuts not working in Review mode

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1353]
On Firefox v79, the JOSM shortcut keys `t`, `r` doesn't seem to work in Review mode. The other editor shortcuts are working as expected.

Also, with JOSM as your default editor, the edit Button doesn't do anything in Review mode.

**Comment by nrotstan** [comment]
Thanks, @govvin . This was fixed in v3.6.9, which has just been deployed to maproulette.org, so it should be working now.
