### ISSUE TITLE
[URGENT] Unexpected values from moustache tags in the Instructions box

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1354]
In Review mode, whenever I let MR choose a nearby task for me, the values displayed by the moustache tags inside the instruction box do not match the actual values from the task I'm supposedly reviewing. The values are actually from the previous task I was working on.

This is a new behaviour I haven't encountered before. As seen in the following screenshots, the tags I expect to should match what is when a marker is clicked.

![Screenshot_2020-08-07_13-31-52](https://user-images.githubusercontent.com/5821688/89614888-f046ad80-d8b7-11ea-8e1e-3b0af9ade711.png)

![Screenshot_2020-08-07_13-29-05](https://user-images.githubusercontent.com/5821688/89614892-f2107100-d8b7-11ea-9525-588b146cda22.png)

![Screenshot_2020-08-07_13-53-39](https://user-images.githubusercontent.com/5821688/89614879-ecb32680-d8b7-11ea-82e9-bfd85d720593.png)

If I choose a marker from the map of nearby tasks, there's no issue.

A fellow project contributor is experiencing the same issue, but it happens during the Task Completion mode. I will ask them to post their experience.

On an off-tangent issue related to this, there seems to be no way to put a challenge on pause. We wanted to do this until this issue is resolved, since we don't want users using the wrong attributes.

**Comment by maning** [comment]
I confirm this is happening to me on the same challenge: https://maproulette.org/browse/challenges/9413
![dups](https://user-images.githubusercontent.com/353700/89619517-a6ae9080-d8c0-11ea-905e-0c26c3add434.gif)

**Comment by nrotstan** [comment]
This will be fixed by PR #1355

**Comment by nrotstan** [comment]
This is fixed in v3.6.10 which has been deployed to maproulette.org. Thanks for reporting this, @govvin and @maning ! Much appreciated.
