### ISSUE TITLE
Ability for MapRoulette users to use Healthsites.io editor

### ISSUE THREAD

**Issue by markherringer** [osmlab/maproulette3#1367]
As a MapRoulette user
In order to accurately update health site information 
I would like to be able to choose Healthsites.io as my editor (from the editor dropdown)

Background:
Healthsites.io provides an OSM editor tailored for editing OSM attributes related to the health sector. These attributes are approved by the OSM community, so using Healthistes.io is less risky to use invalid or unused properties.

Add 'Edit in Healthsites.io' as a drop down option on the maproulette challenge page:
https://maproulette.org/challenge/13219/task/46815938

https://healthsites.io/

**Comment by markherringer** [comment]
We are trying to solve some problems we have and it seems that MapRoulette could be a viable option.
For example, we do get data from MoH and before we upload them to OSM, we would like to validate them using crowdsourcing technologies. It looks like MapRoulette is doing exactly this. Could you help us to understand what are the options?

**Comment by nrotstan** [comment]
Hi @markherringer , is there documentation on the URL parameters for the healthsite.io editor, equivalent to something along the lines of the [iD API document](https://github.com/openstreetmap/iD/blob/develop/API.md)? Or is it iD compatible?

Every editor is a little bit different with varying degrees of functionality, but in general here are the basic things we'll try to pass along when supported by the editor:
* the specific OSM node/way/relation to edit, when specified in a task
* bbox of the mapper's current map (or zoom level and centerpoint) -- important if there is no OSM element id specified
* prefilled OSM changeset/commit comment setup by challenge creator
* prefilled source tag setup by challenge creator
* the current imagery layer being used by the mapper when they clicked Edit (either Editor Layer Index id or custom basemap URL)
* any open photo overlays, such as Mapillary or OpenStreetCam imagery

Also, in regard to your specific use case you mentioned, we recently began supporting what we're calling [Cooperative Challenges](https://github.com/osmlab/maproulette3/wiki/Cooperative-Challenges) where the challenge creator can include in-progress (uncommitted) mapping work with each task that the mapper can then load into an editor to verify/fix/complete before uploading to OSM. We currently only support JOSM for these types of challenges.

**Comment by markherringer** [comment]
Hello @nrotstan here is the [Healthsites API document](https://github.com/healthsites/healthsites/wiki/API)

**Comment by nrotstan** [comment]
Thanks, @markherringer , but I'm not seeing anything in that document discussing interaction with the healthsites.io editor. Maybe I'm just missing it?

My understanding is that this request is for MapRoulette to support an option to send users to the healthsites.io editor when they begin editing a task (basically the equivalent of intiating an editing session with iD), so we need to know what healthsites.io is expecting on the URL for the various pieces of data mentioned in the above comment to properly initiate an editing session for the user when we send them to healthsites.io.

**Comment by timlinux** [comment]
Hi @nrotstan . We don't currently have an ID editor profile for Healthsites.io, but we could generate one (with the side benefit that it would be usable for other platforms too).  Is there any documentation or could you explain in high level terms the workflow for integrating with MapRoulette? Or is having an ID editor profile basically all we need to do from our side?

**Comment by mvexel** [comment]
Hi @timlinux -- sorry for the radio silence. Basically for each editor we add to the MR editor dropdown menu, we need to define what remote URL (and query parameters / payload) is being generated. At a minimum we would need to be able to pass in a map extent to display, but if you would want to 

As a general rule, we prefer to keep the editor list in the dropdown small and limited to general purpose OSM editors, so I am a bit hesitant to move forward with adding healthsites.io to the editor dropdown list. If you plan to have a sustained stream of MapRoulette challenges, and especially if you plan to do specific outreach to the OSM community, we'd definitely consider its but we would need to know how to call your editor from a specific task in a way that provides a continuous workflow. Feel free to reach out offline if you want to discuss and talk about your use case more.

**Comment by mvexel** [comment]
We had a brief discussion offline but no further follow up, so closing here but feel free to re-open if there is a future need that intersects with the needs of the OSM community.
