### ISSUE TITLE
Make website's with custom tags also clickable

### ISSUE THREAD

**Issue by thibaultmol** [osmlab/maproulette3#1370]
![Screenshot_20200815-073333](https://user-images.githubusercontent.com/1010226/90306064-b5e99b80-dec9-11ea-8216-95ee5f0f0064.png)
This website URL isn't a hyperlink while that would have been quite useful

**Comment by mvexel** [comment]
Thanks for the suggestion, @thibaultmol !

May I suggest using a Mustache Tag in the instructions to accomplish what you are after?

In the task instruction field, you would use something like

`[{{heritage:operator}}]({{heritage:website}})` which would turn into [OnroerendErfgoed](https://inventaris.onroerendgoed.be/dibe/relict/10129)

Would that solve your issue?

**Comment by hgcvm** [comment]
Thanks mvexel for the suggestion. I'm the one who made that challenge. 
I'm having some difficulties trying to get it to work. I can successfully use the Mustache Tag to get the URL (for example  {{heritage:website}}  ).  The URL shows up.
But then, it's not clickable. It seems like MarkDown doesn't convert the raw URL into a link.

Also, when I try using another methode, it doesn't make a link out of it:
[a link]({{heritage:website}})

It seems like MarkDown is applied first, and then only the Mustache Tags are processed?

Or am I missing something?

**Comment by nrotstan** [comment]
That's correct, we don't apply markdown processing to property/tag values, so the urls don't get turned into clickable links. Agreed it would be nice, though.

**Comment by nrotstan** [comment]
URL properties referenced via mustache tags in Task Instructions should now get turned into links correctly.

**Comment by hgcvm** [comment]
Thanks a lot for fixing this!
