### ISSUE TITLE
Markdown appears broken

### ISSUE THREAD

**Issue by tastrax** [osmlab/maproulette3#1371]
This text in the challenge setup

```
branch=LOCATION<br />
name=LOCATION Fire Station<br />
operator=Tasmanian Fire Service<br />
website=http://www.fire.tas.gov.au/
```

returns the following on screen

branch=LOCATION name=LOCATION Fire Station operator=Tasmanian Fire Service website=http://www.fire.tas.gov.au/

Same result if i use two spaces at the end of the line followed by return

**Comment by nrotstan** [comment]
Hi @tastrax , we use a variant of github-flavored markdown.  HTML (like br tags) isn't allowed. If you're trying to get line breaks, you can just hit Enter twice after each line. For example:

```
branch=LOCATION


name=LOCATION Fire Station


operator=Tasmanian Fire Service


website=http://www.fire.tas.gov.au/
```

Here's our wiki page with [more info and examples](https://github.com/osmlab/maproulette3/wiki/Markdown-text-markup-and-styling)

I'm going to close this issue, but feel free to re-open if you continue to experience problems.

**Comment by tastrax** [comment]
I still cant see a way to get a paragraph of text with set linebreaks - is this possible? (double return doesnt work as it adds another line between them)

branch=LOCATION
name=LOCATION Fire Station
operator=Tasmanian Fire Service
website=http://www.fire.tas.gov.au/

**Comment by nrotstan** [comment]
You might try making a table. There's an example on that wiki page, but something like this (I left headers blank, but you could add something in if it makes sense):

```
|         |                             |
|:--------|:----------------------------|
|branch   | LOCATION                    |
|name     | LOCATION Fire Station       |
|operator | Tasmanian Fire Service      |
|website  | http://www.fire.tas.gov.au/ |
```

**Comment by tastrax** [comment]
I dont need a table.
Also the link to the cheatsheet suggest three returns but that also fails
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lines

**Comment by tastrax** [comment]
So from all the above I gather that the answer is that the variant of Github Markdown used by Map Roulette does not support paragraph line breaks? I will add another issue requesting this as an enhancement.

**Comment by mvexel** [comment]
Sorry I didn't realize that you had opened an issue.
Here's another way to accomplish what you may be looking for.
Surround the entire block with three backticks so you get a 'code block'.
That would end up looking like this:

```
branch=LOCATION
name=LOCATION Fire Station
operator=Tasmanian Fire Service
website=http://www.fire.tas.gov.au/
```

**Comment by tastrax** [comment]
Many thanks - that works for me.
