### ISSUE TITLE
JsonValidationError when creating virtual challenge

### ISSUE THREAD

**Issue by shawat94** [osmlab/maproulette3#1373]
When attempting to create a virtual challenge by selecting the 'Work on [x] Mapped Tasks' on the 'Find Challenges' page, a JsonValidationError is consistently returned:

![image](https://user-images.githubusercontent.com/33205894/90803964-668edb00-e2ce-11ea-90dc-15b5bba612d0.png)

**Comment by nrotstan** [comment]
Thanks for the report, @shawat94 !

**Comment by nrotstan** [comment]
PR #1374 has been submitted to fix this bug. It only occurs when the map shows no clusters of tasks (only individual task markers), so as a temporary work-around @shawat94  you can try adjusting the map so that at least one cluster of tasks is shown before creating your virtual challenge.
