### ISSUE TITLE
Geojson challenges should not be converted to Overpass challenges

### ISSUE THREAD

**Issue by tsmock** [osmlab/maproulette3#1381]
I don't know how this happened, exactly, but it has happened to me twice in a row.

General steps to reproduce:
1) Create new geojson challenge (my challenges had ~6600 tasks)
2) Modify task instructions (`Detailed Instructions for Mappers`, specifically)
3) Save
4) Watch the project rebuild (may take awhile), see the following message:
```
Bad Request:<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" lang="en"/>
  <title>OSM3S Response</title>
</head>
<body>

<p>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</p>
<p><strong style="color:#FF0000">Error</strong>: line 1: parse error: Unknown type &quot;This&quot; </p>
<p><strong style="color:#FF0000">Error</strong>: line 1: parse error: An empty query is not allowed </p>
<p><strong style="color:#FF0000">Error</strong>: line 1: parse error: ';' expected - 'is' found. </p>
<p><strong style="color:#FF0000">Error</strong>: line 3: parse error: Unknown type &quot;`&quot; </p>
<p><strong style="color:#FF0000">Error</strong>: line 3: parse error: An empty query is not allowed </p>
<p><strong style="color:#FF0000">Error</strong>: line 3: parse error: ';' expected - 'separated' found. </p>
<p><strong style="color:#FF0000">Error</strong>: line 3: parse error: Unknown type &quot;concrete&quot; </p>
<p><strong style="color:#FF0000">Error</strong>: line 3: parse error: An empty query is not allowed </p>
<p><strong style="color:#FF0000">Error</strong>: line 3: parse error: ';' expected - '`' found. </p>
<p><strong style="color:#FF0000">Error</strong>: line 5: parse error: Unexpected end of input. </p>

</body>
</html>
```

Note: You may have to do steps 2 and 3 a few times, but it seemed to do it fairly reliably with one change for me. See challenge 14357 or 14358 for examples (I initially thought I was breaking something somewhere accidentally).

**Comment by nrotstan** [comment]
Thanks for the report, @taylorsmock . Just to confirm, you originally created the challenge through the website (and not the API), correct? And your tasks successfully built? Were you originally using a local GeoJSON File or a URL to a remote file? And finally, which browser were you using?

I haven't been able to reproduce this myself, but I'll continue investigating.

**Comment by taylorsmock** [comment]
I did create the challenge through the website (not an API -- I may try doing that, just to see what happens).

Browser: Firefox
Addons: Ublock origin

I'll see if I can make a video and post it somewhere (that will probably be more "precise" than text).

**Comment by nrotstan** [comment]
Thanks, that video is helpful

**Comment by nrotstan** [comment]
I notice you're cloning a challenge. If you create the challenge from scratch instead of cloning, does the problem still occur for you?

**Comment by taylorsmock** [comment]
Yes. I'll go ahead and double check though (I just cloned the previous challenge since that was faster, and the first one had the same issue, so it _shouldn't_ be dependent upon cloning).

**Comment by nrotstan** [comment]
PR #1383 will likely fix this, but I think if you avoid switching data sources on a challenge you'll be okay in the mean time. If that proves not to be case, please let us know.

**Comment by taylorsmock** [comment]
I don't think I was switching data sources (i.e., creating challenge with overpass and then switching to geojson), but its possible that I was. But that very well may fix my problem.

Thanks.

**Comment by nrotstan** [comment]
This should now be fixed. Feel free to reopen if you continue to experience it.
