### ISSUE TITLE
Flag tasks as outdated when last_edit_changeset is different. <feature request>

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/maproulette3#1390]
When importing a geojson file that includes issues to create tasks from in a challenge I thought it would be very interesting and worth while for maproulette to detect when an feature includes a last_edit_changeset value that is different from the currently available OSM object.

I just created a challenge using a tool that generates the geojson and had a few features that had already been fixed on the OSM map. When I looked at the task page that was generated from the feature in the geojson it did not alert me that the object that I am looking at is different from the one that the feature in the geojson file was created from. I just thought it would be really nice to have a flag somewhere that showed the "outdated" task, and maybe even a way to see a count of "outdated" tasks when looking at a challenge. 

Just a thought. Let me know if this is not interesting to others.

**Comment by nrotstan** [comment]
Hi @atiannicelli thanks for making this suggestion! One thing that occurs to me is that OSM elements can be modified for a number of reasons, and it's difficult to know if a modification actually impacts the changes requested by a given challenge unless a mapper manually inspects it and makes a determination (which is basically what they'd do today in their editor).

MapRoulette *does* currently fetch the latest task data from OSM for tag-fix [cooperative challenges](https://github.com/osmlab/maproulette3/wiki/Cooperative-Challenges) each time a task is loaded, as in that case MR understands exactly which changes are being proposed and can therefore intelligently determine whether updates to the OSM element have a bearing on the task.

But for standard challenges, the closest we currently offer is the "OSM Data" map layer, which loads the latest OSM data for elements shown on the task map. It'd certainly be possible to offer something similar but for just the OSM element in question. Do you think that'd be useful?

**Comment by atiannicelli** [comment]
I think that what is in place probably is enough for now. I'm going to close this as I didn't know about the cooperative challenges at the time I wrote this.

**Comment by atiannicelli** [comment]
After talking to others I am going to open this up. The issue happen when a challenge is created to flag an issue on a feature with last_edit_changeset of 5, and then while the task is sitting, waiting for someone to address it, the OSM mapping data is changed to update that feature to last_edit_changeset of 6. When a mapper open the challenge task that was created at changeset 5 then the task may be flagging an issue that was fixed in 6. Or the feature may have changed enough from 5 to 6 so that the task no longer applies. What we are asking for here is a visible flag on the task to indicate that the feature that the task was created to address is older than that latest version of that feature.  This may or may not indicate that the task is invalid, but it at least gives the mapper the heads up that they are looking at a task that was created using an older version of the map than they are now editing. It really is a "Heads Up" to the mapper.

The reason we are dealing with this is because some of the maps that we use to generate the challenges are a week to two weeks (or more) old since it may take that amount of time to perform a full test run and so the window for change between the OSM map version that was used to perform the scan and when this task gets worked on is bigger than normal. We have seen our mappers get confused when working on a task that asks them to make a change to a feature because when they open up the map to edit it the feature is different than was described in the task.

**Comment by nrotstan** [comment]
PR #1432 introduces a new, optional OSM History widget that can be used during task completion to view a history of the OSM element(s) in the task. If an element has been changed since the challenge data was sourced -- or has a version newer than that identified on the task via `osmVersion` or `last_edit_changeset` property -- then the history entry will show a warning icon indicating that the change was made after the task was created.

<img width="436" alt="osm_history_widget" src="https://user-images.githubusercontent.com/445970/97200258-3819fa00-176e-11eb-9be8-3ba967540981.png">
