### ISSUE TITLE
[SERVER DB] Missing column for cooperative work

### ISSUE THREAD

**Issue by tsmock** [osmlab/maproulette3#1395]
https://maproulette.org/api/v2/challenges/extendedFind?bb=-240.46875000000003%2C-62.43107423292092%2C240.82031250000003%2C62.2679226294176&cLocal=0&cStatus=3%2C4%2C0%2C-1&ce=true&limit=50&order=DESC&page=0&pe=true&sort=has_cooperative_work

`{"status":"KO","message":"ERROR: column c.has_cooperative_work does not exist\n  Position: 646"}`

Steps to reproduce (UI):
1) https://maproulette.org/browse/challenges
2) Change `Sort by` to `cooperative`.

**Comment by nrotstan** [comment]
This was fixed in v3.6.12
