### ISSUE TITLE
When deleting a challenge, repeat the challenge name in the confirmation dialog

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1407]
Currently, the confirmation dialog just asks if you're sure:

![image](https://user-images.githubusercontent.com/120452/95602681-7eebbe00-0a12-11eb-8cbb-730543861dd3.png)

It would be nice to repeat the action you are about to confirm. In this case, deleting a challenge. Especially on bigger / wider screens, the three dot menu can be quite a distance removed from the challenge name, so it is conceivable that the user would be less than 100% confident that they selected the challenge they wanted to act on: 

![image](https://user-images.githubusercontent.com/120452/95602857-c1ad9600-0a12-11eb-90a8-9a49eba01e4d.png)

**Comment by nrotstan** [comment]
This is now on maproulette.org
