### ISSUE TITLE
Move source of https://learn.maproulette.org/ from the wiki section into other repo or to a separate branch

### ISSUE THREAD

**Issue by Andygol** [osmlab/maproulette3#1437]
https://twitter.com/maproulette/status/1313577249086468096?s=21

Here ☝️ was a short conversation about possible translation of the Documentation placed in https://learn.maproulette.org/. I made several attempts to find the source of the documentation so that they can be translated. In the end, I managed to find out that _learn.maproulette.org_ is just a wrapper over the wiki from this repo. With the current state of affairs, it is mostly impossible to provide and manage translation. To do so, it would be great to extract all materials from the wiki and move them into a separate repo or branch as the first step towards further work for translation of the documentation.

**Comment by nrotstan** [comment]
Hi @Andygol , thanks for bringing this up! The docs repo is at https://github.com/maproulette/docs

**Comment by mvexel** [comment]
I will add a deprecation notice to the wiki home page as well.
