### ISSUE TITLE
Field `osmid` automatically added to the task

### ISSUE THREAD

**Issue by jbelien** [osmlab/maproulette3#1451]
Now that I have added a Feature id to my features used to create the tasks (see [`diff.geojson`](https://raw.githubusercontent.com/osmbe/road-completion/master/data/belgium/brussels/difference/diff.geojson)) a new field `osmid` has been added to my task (see screenshot below).

That's really confusing since the id I use is the id from the original source and NOT an osmid.

![image](https://user-images.githubusercontent.com/1150563/99358684-33002480-28ae-11eb-8bb3-ff3c07400fde.png)

**Comment by nrotstan** [comment]
Hi @jbelien , setting up non-OSM task ids in MapRoulette can be more confusing than it should be.

First, the id values have to be strings in the GeoJSON even if they are purely numeric. That doesn't appear to have been documented before, so I've updated the documentation to note that fact.

Second, I would give your id field a different name, such as `externalId` (So your new ids would look like `"externalId":"7171942"`), and then when you setup your challenge go into the "Configure property-based behavior" step and specify your fieldname for the "OSM Id Property" (even though it's not an OSM id -- we should update that label to clarify it applies to any external id).

<img width="1027" alt="externalId" src="https://user-images.githubusercontent.com/445970/99418912-5a57f100-28b0-11eb-8c01-b2d90e5d99bb.png">

I think that will do what you want.

**Comment by nrotstan** [comment]
I should note that with the above setup, your external id won't appear at all in the task properties you show in the screenshot, which I believe is what you want. But if you do want the external id to appear (as `externalId` or whatever you choose to call it), then you should move your ids from the feature into the properties in your GeoJSON.

**Comment by jbelien** [comment]
So, I shouldn't use `feature.id` but instead configure my MapRoulette challenge by setting "OSM Id Property" to the property used as unique identifier. Did I understand correctly ?

**Comment by nrotstan** [comment]
Correct, since it's not an OSM id, call your field something else (`externalId` as one example) and use the OSM Id Property setting on your challenge to tell MapRoulette its name (`externalId`). You can leave your field on the feature (`feature.externalId`) if you do not want it show up in the properties popup. If you do want it in the properties popup, then put it into properties instead (`feature.properties.externalId`).

And make sure your ids are strings in the GeoJSON, even if they are completely numeric.

**Comment by jbelien** [comment]
Thanks @nrotstan 👍 

Everything works fine now.
And I can confirm that it doesn't work if the field used as ID is an integer, thank you for updating the documentation.
