### ISSUE TITLE
Feature Request: Sort By Completion

### ISSUE THREAD

**Issue by homersimpsons** [osmlab/maproulette3#1460]
I guess some projects are close to be done but are just missing some tasks to be completed. It would be a nice feature to sort by completion in order to definitely end thoses.

In order to sort by completion one can have 2 approach:
- Remainig Tasks **Count**: This has the advantage to clearly show that this challenge is really close to be done
- Remainig Tasks **Percentage**: This avoid challenges without much tasks to be first but is not representative of the work to achieve if he challenge has a lot of tasks

**Comment by mvexel** [comment]
Thanks for the suggestion, @homersimpsons . We will consider it.

**Comment by jschwarz2030** [comment]
So far I'm not seeing a simple solution to this request.  Calculating remaining count and percentage completion would require querying the entire database of challenges and their associative tasks, and subsequently running filters and sorting methods from there.  I think the only plausible solution is to create a scheduler that runs these calculations and snapshots the results to the challenge table periodically.  Depending on how high demand this feature is, it may or may not be reasonable to do so.

**Comment by homersimpsons** [comment]
This is done with https://github.com/maproulette/maproulette2/pull/910 and in production.
