### ISSUE TITLE
Tasks from dates not in sync - challenges look outdated to users

### ISSUE THREAD

**Issue by Noki** [osmlab/maproulette3#1479]
Hi!

I added the phone number challenges to MapRoulette. A user complained that my challenges look outdated in the [user view:](https://maproulette.org/browse/challenges/4412)

![image](https://user-images.githubusercontent.com/198902/103437664-57c81580-4c2a-11eb-998c-42ee1f823c90.png)

In the admin view it looks like this:

![image](https://user-images.githubusercontent.com/198902/103437676-8219d300-4c2a-11eb-94e2-a9685a764159.png)

Expectations: The tasks from data in the user view should match the tasks from date in the admin view.

Best regards
Tobias

**Comment by nrotstan** [comment]
Thanks for the report, @Noki! I'm currently seeing "1 day ago" for that challenge as a user. Both the user-facing side and challenge-management side look at the exact same field on the challenge for display of the "Tasks From" date, so I'm not sure why different values would be shown unless maybe that user was running into some client-side caching (or inadvertently was looking at a different challenge). I'm going to close this issue, but feel free to reopen it if you see it again and I'll try to take a quicker look.

**Comment by Noki** [comment]
@nrotstan 

I created a new chrome profile, disabled caching in the chrome dev-tools. And I still see "tasks from: 1 year ago". I recorded a short video. It's not a client-side caching problem.

https://user-images.githubusercontent.com/198902/103625962-e47d1700-4f3b-11eb-88fd-871ef1de9d5e.mp4

**Comment by nrotstan** [comment]
Ah, that's a different challenge. Thanks, @Noki , I can now see the incorrect behavior. The video was helpful.

**Comment by nrotstan** [comment]
This appears to be an issue with the relative date formatting package we're using. The date itself is correct, which can be verified by hovering over the Tasks From and seeing it in the tooltip. We may just need to show the date itself, for now, instead of a relative time.

**Comment by nrotstan** [comment]
This should now be fixed on maproulette.org
