### ISSUE TITLE
Zoom-to-task button on Multi-select view goes to previous task

### ISSUE THREAD

**Issue by jgscherber** [osmlab/maproulette3#1481]
STR
1. Complete a task
2. In the multi-select view, click the zoom-to-task button

ER: Zooms to current task's location
AR: Zooms to previous task's location

![image](https://user-images.githubusercontent.com/6207661/103549594-3efb7200-4e6d-11eb-8ebc-7f914e7a7e3d.png)

**Comment by nrotstan** [comment]
Thanks for reporting this, @jgscherber! I've submitted PR #1482 to address it.

**Comment by nrotstan** [comment]
This should now be fixed on maproulette.org
