### ISSUE TITLE
Feature request: Let user to filter tasks

### ISSUE THREAD

**Issue by Miroff** [osmlab/maproulette3#1483]
Some of the mappers are concerned about their home region first. As a creator of a large Maproulette challenge I would like to let mappers more control about what tasks will be assigned to a user. I added property 'region' to a task, but there is no filter available for a user. It would be nice if I can mark some task properties as 'Discoverable' and the user will see bunch of multiple choice dropdown filters on the challenge start screen (https://maproulette.org/browse/challenges/15351)

I already split whole tasks list to several macro-regions, but users would like to see more granular separation.

**Comment by nrotstan** [comment]
Hi @Miroff , thanks for the feedback! If geographic region is the primary concern, users can use the map on the Find Challenges page to see tasks in their area of interest (and can use the Location (nominatum) search or Near Me button to navigate to a specific area quicker). If they only want to see tasks in your challenge, they can first search for your challenge by name.

**Comment by govvin** [comment]
We do something similar for more experienced contributors to our challenge by adding them as a project manager with read-only credentials.  With that, they can use advanced filter based on available challenge attributes.

The caveat is that if you keep multiple challenges in the same project, they'll end up getting the same rights for those, too.  So, the work around for that is to create a separate project for the specific challenge.

**Comment by nrotstan** [comment]
I'm going to close this, as I think it was prompted by a desire for geographic filtering and we currently offer that. But if there are strong use cases for additional filtering tools for mappers, we can certainly discuss those.
