### ISSUE TITLE
Coordinates found in location widget has changed from lat/lon to lon/lat

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1499]
![image](https://user-images.githubusercontent.com/5821688/104989716-fc818a00-5a55-11eb-9ca4-d6600329f158.png)

I just noticed now that the coordinates found in the location widget now uses lon/lat format whereas before it was lat/lon. 

The lat/lon format is readily understood in JOSM (e.g. copying them to jump to a specific location, or creating a node) while with the now lon/lat format you need to interchange the values.

Same goes when searching for coordinates in OSM. 

I hope you can revert them to the previous lat/lon order.

**Comment by nrotstan** [comment]
Hi @govvin , it's configurable now with the cog icon on that widget, so you can have it whichever way you want (or even switch back and forth).
