### ISSUE TITLE
line separator "---" causes the instruction widget to fail rendering (was: copyable shortcode causes widget failed error)

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1512]
**EDIT: **
The cause of the widget failure are not the shortcodes themselves, but the `---` in the text, which I happen to use while testing the copyable shortcode.

I'm preserving the original post below

The instruction widget fails to render when including the copyable shortcode:

![image](https://user-images.githubusercontent.com/5821688/105430668-017d4e00-5c8f-11eb-86c9-64a1d82355f3.png)

I'm using the code with multi-line text:
![image](https://user-images.githubusercontent.com/5821688/105430811-5de06d80-5c8f-11eb-8d49-7a0737fb3a09.png)

And trying out a simple [copyable "hello world"] generates the same issue
![image](https://user-images.githubusercontent.com/5821688/105430910-92ecc000-5c8f-11eb-9233-26fee338ca4c.png)

**Comment by nrotstan** [comment]
@govvin Does the "hello world" one fail on its own? This works for me as a simple example:  `Here is some [copyable "copyable text"]`

Or with mustache tags: `building is set to [copyable "{{building}}"]`

That first big copyable block you show is ambitious ;-) Something like that never even crossed my mind. I think there are at least two problems with it that I can see (1) you need double quotes around the whole copyable text and (2) you can't use markdown in the copyable value (e.g. the backticks). I'll update the documentation to make that clearer.

So you'd need something like:
```
[copyable "
addr:village = {{addr:village}}
addr:neighbourhood = {{addr:neighbourhood}}
"]
```
and so on. You could also separate them onto their own lines with their own copyable codes:

```
[copyable "addr:village = {{addr:village}}"]


[copyable "addr:neighbourhood = {{addr:neighbourhood}}"]
```

We may be able to add support for markdown in the copyable text, but then the markdown itself would also get copied to the clipboard (e.g. the backticks in your example), which I don't think is what you want either.

**Comment by govvin** [comment]
Hi Neil

I tried the shortcode on its own, and it didn't work for me. Same result with the double backticks. 

I also tried forcing a line break (use two spaces after a line) with markdown, but it didn't work, too.

I get the same error
![image](https://user-images.githubusercontent.com/5821688/105441096-cb49c980-5ca2-11eb-8ceb-ce3edfb6a6da.png)

If there's any additional information I can provide, please let me know.

**Comment by nrotstan** [comment]
Would it be possible copy the full instructions you're using into a text file and attach it to the issue so I can look at it? The raw text you see when editing the challenge.

**Comment by govvin** [comment]
Okay, it seems it's the `---` I added that's causing the widget to fail. By the way the line separator used to work just fine in the instruction widget, IIRC.

I'll get back to you with the shortcodes I'm still testing right now.

**Comment by govvin** [comment]
I got it working now :smile: 

Here's the text I use after removing the double spaces I had for markdown.
```
[copyable "
amenity=school
name={{SchoolName}}
old_name={{old_name}}
short_name={{short_name}}
isced:level={{isced:level}}
ref={{ref}}
start_date={{date_started
population:pupils:2012= {{population:pupils:2012}}
population:pupils:2015= {{population:pupils:2015}}
education_program={{education_program}}
specialized_education={{specialized_education}}
addr:province={{addr:province}}
addr:town={{addr:town}}
addr:city={{addr:city}}
addr:borough={{addr:borough}}
addr:village={{addr:village}}
addr:neighbourhood={{addr:neighbourhood}}
addr:hamlet={{addr:hamlet}}
addr:housenumber={{addr:housenumber}}
addr:street={{addr:street}}
addr:street:corner={{addr:street:corner}}
operator:type=public
operator={{operator}}
source= Department of Education, Philippines
source:date=2012
"]
```

It looks like this in the instruction widget: 
![image](https://user-images.githubusercontent.com/5821688/105443136-fda8f600-5ca5-11eb-9c4d-e48d5afbc403.png)

It's copyable and works as expected when pasted in JOSM, or the iD editor, but I think we could improve how the information is rendered on screen.

I'm wondering if we can hide the copyable text and use additional, optional text for use with rendering?

For example 
```
[copyable "Click the clipboard to copy tags to paste in your editor." "
addr:village = {{addr:village}}
addr:neighbourhood = {{addr:neighbourhood}}
"]
```

**Comment by nrotstan** [comment]
I think that suggestion makes sense. I'll leave this issue open.

**Comment by nrotstan** [comment]
PR #1519 fixes the horizontal rule (`---`) failure

**Comment by nrotstan** [comment]
This is now fixed on maproulette.org
