### ISSUE TITLE
saved filter causes x tasks widget to fail. 

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1513]
I just discovered the saved filter option, and after saving one, it immediately caused the task widget to fail 
![image](https://user-images.githubusercontent.com/5821688/105432608-e3b1e800-5c92-11eb-9a36-f4ed28620be5.png)

There seems to be no way to delete the saved filter, since the task widget doesn't work.

**Comment by nrotstan** [comment]
@govvin I think we've got this fixed and will be deploying a hotfix for it in a bit.

**Comment by nrotstan** [comment]
@govvin This fix has been deployed to maproulette.org now. You'll need to refresh your browser.

**Comment by govvin** [comment]
It now works as expected. Thank you for the quick fix
