### ISSUE TITLE
searching for tasks, using keyword, in the vicinity of a given coordinates stopped working

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1514]
Prior to v3.7, this [url](https://maproulette.org/browse/challenges?challengeSearch=124.8479461669922%2C8.5054795239734%2C124.95411872863771%2C8.562264507540178&keywords=osmapaaralan&location=intersectingMapBounds) will show available tasks for our [challenge](https://maproulette.org/browse/challenges/9413) in the vicinity of the given coordinates, with the keyword "osmapaaralan"

Now, it doesn't show anything:
![image](https://user-images.githubusercontent.com/5821688/105433791-41473400-5c95-11eb-9b1b-844790c0fb50.png)

Checking the challenge for the same general location, it shows that there are actually available tasks in the same area:
![image](https://user-images.githubusercontent.com/5821688/105433838-5b811200-5c95-11eb-8e22-d04238397252.png)

**Comment by nrotstan** [comment]
Backend PR maproulette/maproulette2#869 has been submitted to address this.

**Comment by nrotstan** [comment]
This is now fixed on maproulette.org
