### ISSUE TITLE
After last update images in description start fail entire description widget

### ISSUE THREAD

**Issue by AlexandrPro** [osmlab/maproulette3#1518]
So, i load my maproulette challenge (after 21 jan website update) and receive such image:
http://prntscr.com/xglb3h

Widget with challenge description shows "Widget Failed" instead of description itself. There was description with mardown, so i start to remove elements from description and reload page. So, issue was in part, that add image for my challenge:

`![намальовано @gontsa спеціально для ком'юніті OSM Ukraine](https://raw.githubusercontent.com/gontsa/osm-ua-week-task-cover/master/final-task-covers/osm-task-school-35_2.png)`

Without this line of markdown, widget work as before. 

File with original description (with markdown) is here:
[description.txt](https://github.com/osmlab/maproulette3/files/5857292/description.txt)

I have removed image from my challenge, but must warn you about broken part of your system.

**Comment by nrotstan** [comment]
Thanks for the report, @AlexandrPro ! I've submitted PR #1519 to fix this issue.

**Comment by nrotstan** [comment]
This is now fixed on maproulette.org
