### ISSUE TITLE
"Contact owner" does nothing for old challenges with no assigned owner

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/maproulette3#1520]
I was trying to use it https://maproulette.org/challenge/983/task/1245787 but nothing is happening - I expected at least some error.

I see nothing in browser console.

(I am trying to contact owner as challenge is misdesiged and generates large amount of false positives on crossing of oneways going in opposite directions, even if two way or other roads are present)

Note https://maproulette.org/browse/challenges/983 - 165 fixed, 436 not an issue - and 20230 tasks sitting since 2016. It should be fixed and regenerated

**Comment by nrotstan** [comment]
Thanks for the report, @matkoniecz , it looks like that challenge was created before MapRoulette tracked owners at the challenge level, but the project is owned by OSM user Valhalla-Routing: https://www.openstreetmap.org/user/Valhalla-Routing.

**Comment by nrotstan** [comment]
I've updated the issue title

**Comment by matkoniecz** [comment]
Thanks! I contacted also this (probably abandoned) account.
