### ISSUE TITLE
Maproulette website not working

### ISSUE THREAD

**Issue by ikid0** [osmlab/maproulette3#1538]
For several days I have been experiencing difficulties with accessing the site.
Errors:
Unable to search challenges on server.
Unable to retrieve latest challenge data from server.
Unable to retrieve latest project data from server.

![Screenshot_5](https://user-images.githubusercontent.com/3027212/106429521-ff33a480-6483-11eb-8d9a-a2ac69305adf.png)

**Comment by mvexel** [comment]
We're working on a fix for these intermittent loading issues, which should be deployed this week.

**Comment by nrotstan** [comment]
Things should hopefully be a lot better now. Thanks for your patience.

**Comment by ikid0** [comment]
Thank you guys you are the best =)
