### ISSUE TITLE
website is slower?

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1542]
I'm getting a lot of these errors when viewing the challenge dashboard:

![image](https://user-images.githubusercontent.com/5821688/106544900-4a60bc80-6543-11eb-825d-9164cb974aa9.png)

![image](https://user-images.githubusercontent.com/5821688/106544794-1daca500-6543-11eb-826f-a7d0d618d92e.png)

![image](https://user-images.githubusercontent.com/5821688/106544459-89424280-6542-11eb-8a62-837c1b97f423.png)

![image](https://user-images.githubusercontent.com/5821688/106544589-c575a300-6542-11eb-981a-6bb7a53007e5.png)

Also, when searching for tasks using the dashboard, the map markers will show up as expected but it will take a while for the task list (the items below the map) to show up.

**Comment by nrotstan** [comment]
Thanks for the report, @govvin . Some things are definitely slow, especially administration of larger challenges. There's a release planned for Wednesday at 20:00 UTC that should fix most of it.

**Comment by govvin** [comment]
Hi @nrotstan . I'll wait for changes until after the scheduled fixes then. Thanks.

**Comment by nrotstan** [comment]
Things should hopefully be a lot better now.
