### ISSUE TITLE
County in location box

### ISSUE THREAD

**Issue by boothym** [osmlab/maproulette3#1568]
See screenshot.

The location widget lists the town/city, county, country (guessing it's admin_level=6, 4, 2) - but it wrongly adds the word "County" after admin_level=6. This seems like an American-centric way of displaying the location and should be removed as the name of the county is just "Fife".

![Capture2](https://user-images.githubusercontent.com/16965772/108203005-d533e080-7119-11eb-8d4b-9892d91116d6.JPG)

**Comment by kjonosm** [comment]
same in Germany, there seems no need to add "county" to the location especially as the German equivalent "Landkreis" is already present.
![image](https://user-images.githubusercontent.com/51236777/108595280-47f1c580-737f-11eb-86ce-b3945f3e509e.png)
