### ISSUE TITLE
When working on multiple tasks together add ability to choose "I fixed it!" for some, and a different option for others.

### ISSUE THREAD

**Issue by ChrisEdits** [osmlab/maproulette3#1586]
Unless I've missed it, there isn't a way to change how you "complete" tasks when working with multiple. 

For example, if editing 10 tasks close together, 8 may be "not an issue" but 2 might require a fix. There's no easy way to set this before moving onto the next task.

If I have missed it, then happy to be corrected!

**Comment by mvexel** [comment]
The way to do that would be to unbundle them using the button in the multitask widget, and resolve them in MapRoulette separately, even if you edited them in one changeset. Does that help at all?

**Comment by ChrisEdits** [comment]
Hey @mvexel, thanks for your answer, that seems like to best way to deal with it for now! :)
