### ISSUE TITLE
Timezone error on CSV export

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1594]
I am trying to download task data as CSV. It gives me the following error instead of CSV data:

```
status | "KO"
-- | --
message | "Timezone is not a valid time zone. [null]"
```

Here's the timezone info MapRoulette shows me:

![Screen Shot 2021-04-09 at 9 51 25 AM](https://user-images.githubusercontent.com/120452/114207291-76b90080-9919-11eb-9c8f-229a90c23278.png)

![Screen Shot 2021-04-09 at 9 51 33 AM](https://user-images.githubusercontent.com/120452/114207303-79b3f100-9919-11eb-8a06-92d73e6fcf80.png)

**Comment by mvexel** [comment]
When I set the timezone to something sensible, the download goes through.

**Comment by jschwarz2030** [comment]
Unable to reproduce and couldn't locate the source challenge with @mvexel.  I will close for now and reopen if this issue pops up again.
