### ISSUE TITLE
Let users limit tasks to specific area

### ISSUE THREAD

**Issue by mnalis** [osmlab/maproulette3#1597]
I would like to solve some maproulette tasks **that are present in my city or country** (as those I'm familiar with, and those areas I primarily want to improve).

For example, I go to https://maproulette.org/, click on "Find challenges",  and zoom in to Croatia on big map using mouse wheel, and then choose one of the tasks I'd like to solve on the left screen side (say for example _"Profanity OSMCha detections"_ at  https://maproulette.org/browse/challenges/8113) and click on "Start". However, I'm immediately sent to some random task in China or Brazil, which I'm unable to solve as I'm not familiar with those languages (and I wanted to solves quests in Croatia, which is why I zoomed in there). I'm aware it is named _"map **roulette**"_, but some sort of spatial control about what I want to solve would be nice.

I haven't been to able to do it in UI, nor found a way in linked documentation. The closest I found was issue https://github.com/osmlab/maproulette3/issues/1483 which hints that _"If geographic region is the primary concern, users can use the map on the Find Challenges page to see tasks in their area of interest"_, but it does not seems to work for me. Am I doing something wrong?
Is there a way (for me as a user, not as a task creator) to limit / filter the area I want to be solving quests in?

**Comment by jschwarz2030** [comment]
Thanks for the feedback!  This is a great recommendation and worth considering with the MR team.  More discussion is needed, but we'll provide an update soon.

**Comment by jschwarz2030** [comment]
@mnalis it turns out there's a feature called Virtual Challenges that I believe accomplishes most of what you are looking for.

How to use:
1. Go to the `/browse/challenges`
2. Search/Zoom to the area on the map you'd like to filter by
3. On the mapping tools, click on the lasoo icon and draw around the desired area.
4. A button will appear titled "Work on ### selected Tasks".  Click it.
5. Name your virtual challenge and click "Start".  You'll be immediately taken to the first task.
6. If you want to bookmark your virtual challenge, be sure to click on your virtual challenge name in the header.

The last step is a recommendation in order to retain a reference to your virtual challenge for future use.

Let us know if this feature works for you and if you have any other problems.

**Comment by mnalis** [comment]
Thanks @jschwarz2030 for suggestion! I followed it (although I kept clicking on the wrong parts of the screen until I concentrated on each step and forbid myself on clicking the logical things instead of the ones exactly as you've written), and it does indeed allow me to select an area to solve quests in - but it does so indiscriminately for all quests in that area.

What was my intention (and what was misleading me when I tried to follow your tutorial) is that I want to solve some **specific quest** (for example [Profanity OSMCha detections](https://maproulette.org/browse/challenges/8113) in some **specific area** (for example, Croatia). Your solution seems to allow me only to solve **all quests** in **specific area**, is that correct? And just clicking on the quest name allows me to solve **specific quest** but then it must be in **whole world / all areas**, which is again not what I wanted.

So to rephrase - is it somehow possible to limit on _**both** the quest **and** the area at the same time_? For example, only solve "profanities" in "Croatia" ?

**Comment by mvexel** [comment]
@mnalis you can. Use the search box to narrow the list to profanity, then use the workflow @jschwarz2030 described above.

**Comment by mnalis** [comment]
Thanks @mvexel - it works that way! 

Critical peace of information is when I use top-middle search box to search for "Profanity", and Profanity challenge will show in the left panel, **I must _NOT_ click on Challenge in left panel** (otherwise whole thing will reset to whole world, which was happening to me)
