### ISSUE TITLE
Let users test their custom basemap URL

### ISSUE THREAD

**Issue by nrotstan** [osmlab/maproulette3#160]
Add an option for users and challenge owners to test their custom basemap URLs to make sure they are working.

**Comment by mvexel** [comment]
What would the test look like? Perhaps a 'challenge preview' screen?

**Comment by nrotstan** [comment]
It'd be nice to offer the test when the user is entering the URL during challenge creation, so we won't necessarily have any task data yet. I think it also makes sense to offer the same test for users setting up their own custom basemaps in their user settings.

I was thinking that the easiest thing might be to just load a single tile from their custom basemap that could be compared to a reference from OSM. As a random example, https://a.tile.openstreetmap.org/8/49/92.png will show Yellowstone National Park. If their basemap URL is correct, then they should see a more-or-less comparable tile. For example, here is OpenStreetMap vs OpenCycleMap. I'm sure we could pick a reference tile with clear and unique geographic features to make comparison easier:

![tilecomp](https://user-images.githubusercontent.com/445970/37346203-f5425cac-268b-11e8-98b1-ed652bc0be50.png)

This approach obviously only works if their basemap tiles have coverage of the reference region. For those who don't (or simply aren't sure of the reference comparison for some reason), we could offer additional input fields on the test dialog where the user could provide a lng/lat/zoom and we'll load that tile so they can spot-check it and make sure it's what they expect.

And, of course, users can always explore their challenge after creation to make sure the maps are rendering as they expect (just like today). This optional test would just hopefully help users identify common problems with formatting up-front.

Does that seem like a reasonable approach?

**Comment by mvexel** [comment]
Perhaps we can keep it simpler: in the background load one tile and confirm that it returns a 200 response with the correct content-type and a non-zero-length body, and display a little green checkmark if that checks out, a red x if it doesn't?

We can also direct users to JOSM to test their URL pattern.

**Comment by mvexel** [comment]
Or even simpler, we can just encourage folks to test their custom URL pattern in JOSM or iD first :)

**Comment by nrotstan** [comment]
We now fall back to a standard map layer (and show an error) if the custom basemap is problematic, so this isn't as important anymore. Closing.
