### ISSUE TITLE
Unable to do batch status changes in GUI

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/maproulette3#1613]
I am trying to change the status of all my "created" tasks to "disabled" or "skipped" and the batch status change is not working. Screen shots below show what I did. When I click on "proceed" nothing appears to change.

![Screen Shot 2021-05-28 at 10 07 16 AM](https://user-images.githubusercontent.com/5851115/119996395-b658ac00-bf9c-11eb-966c-e937f1291f7f.png)

![Screen Shot 2021-05-28 at 10 04 48 AM](https://user-images.githubusercontent.com/5851115/119995949-2581d080-bf9c-11eb-930b-d3196010d119.png)

**Comment by Sowmya-Nayani** [comment]
Hi, 
This issue is still open. 
Unable to proceed with this kind of action after this pop-up "**Are you sure? This action cannot be undone**". 

![image](https://user-images.githubusercontent.com/46376220/121189101-64aafe00-c887-11eb-9a2e-54e5f77680d4.png)

**Comment by Sowmya-Nayani** [comment]
Its Working now! Thanks for fixing :) Happy Mapping!

**Comment by jschwarz2030** [comment]
Sorry for not posting an update sooner.  Yes this issue has been fixed.  Thanks for your patience.
