### ISSUE TITLE
502 Bad Gateway errors

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1616]
We're seeing a lot of reports. Let's track root cause analysis and further user input here

**Comment by jschwarz2030** [comment]
Gateway issues should be resolved, but we've temporarily disabled push notifications.  Users will need to reload the page to see notifications for now.

**Comment by mvexel** [comment]
will close this

**Comment by Openstreetmapler** [comment]
Please reopen as the issue is quite annoying on my end!

**Comment by jschwarz2030** [comment]
We had two outages today, each was between 15 minutes to an hour.  leaderboard queries are hanging up the challenges table.  Please avoid the leaderboard page while we continue to investigate.
