### ISSUE TITLE
Clicking the linked version in the footer results in a 404 on GitHub

### ISSUE THREAD

**Issue by DavidMetcalfe** [osmlab/maproulette3#1621]
If I click the linked text in the footer reading `MapRoulette v3.7.8-rev1`, I'm brought to the following [page](https://github.com/osmlab/maproulette3/releases/tag/v3.7.8-rev1), but this is an invalid URL, and GitHub returns a 404.

**Comment by jschwarz2030** [comment]
The true version is v3.7.8rev1.  A `-` is being added to the URL mistakenly.  This will be resolved in our next patch, but for now please remove the hyphen and you should be directed to the right webpage.
