### ISSUE TITLE
Doesn't take into account lifecycle prefixes

### ISSUE THREAD

**Issue by wolfy1339** [osmlab/maproulette3#1633]
I am working on a challenge and it repeatedly offers some places that use the lifecycle prefix, and the tasks seem to include those features when they shouldn't

https://maproulette.org/challenge/429/task/496966

**Comment by jschwarz2030** [comment]
Thanks for reporting, @wolfy1339. I'm not quite following the issue, probably due to my inexperience.  Can you provide clarification, perhaps with a screenshot?  Thanks.

**Comment by wolfy1339** [comment]
There is a node tagged with `disused:railway=station`. Relevant [wiki article on OSM](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix)
It probably shoud not match `railway=station`
![image](https://user-images.githubusercontent.com/4595477/129421515-6f1053f0-510a-4d52-9cc6-3736cc92794c.png)

**Comment by mvexel** [comment]
Sorry for the late response! This is a problem with the Challenge, not with MapRoulette itself. If the Challenge shows irrelevant tasks, the Challenge owner used an incorrect query. The best step is to contact the challenge owner.
