### ISSUE TITLE
Cannot update challenge data

### ISSUE THREAD

**Issue by pedjas** [osmlab/maproulette3#1635]
I've set chalenge using overpass query that selects objects missing specific tag.
It keeps leading to edit objects that are fixed externally.

There should be an option to refresh challenge data so that those fixed externally are not offered for editing.

**Comment by jschwarz2030** [comment]
Thanks for reporting @pedjas.  I'm having trouble following if this is a feature request or a bug?  If it's a bug, can you provide steps to reproduce?  Thank you!

**Comment by pedjas** [comment]
It is more a feature request.

**Comment by mvexel** [comment]
@pedjas you can do this using the "Rebuild Tasks" button in your Challenge admin screen. See also https://learn.maproulette.org/documentation/rebuilding-challenge-tasks/#content
