### ISSUE TITLE
502 Bad Gateway errors

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/maproulette3#1644]
As reported by multiple users (Twitter, OSM World Discord).

![image](https://user-images.githubusercontent.com/67521919/131259468-4a83dc19-5f90-4d51-8d16-8ce6f5ea3322.png)

(Browser console is full of 502 Bad Gateway errors.)

**Comment by jschwarz2030** [comment]
site is back up.  investigating root cause

**Comment by jschwarz2030** [comment]
the system is encountering a heavy spike in usage since yesterday and API optimization investigation is still ongoing.  Working with @mvexel to discuss solutions.

**Comment by jschwarz2030** [comment]
I believe we are in the clear.  Will continue to monitor.  Sorry for the delay.

**Comment by jschwarz2030** [comment]
We will be temporarily disabling some of our scheduled jobs, including the leaderboard.  Our recent influx of new tasks is causing some CPU bottlenecks.

Regardless, the site has been fully functional for the past 3 hours.  Still monitoring.
