### ISSUE TITLE
OSM element not found -- should probably be caught at Task create time?

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1648]
see https://maproulette.org/challenge/21846/task/106166973 

![Screenshot_20210910_135148](https://user-images.githubusercontent.com/120452/132909976-7389173f-f338-4087-8d65-513892424fd0.png)

It's trying to fetch https://api.openstreetmap.org/api/0.6/way/-15632035

**Comment by atiannicelli** [comment]
I found the cause of this issue. When atlas checks creates tasks it is possible that the OSM ID can be negative for edges. Blah Blah, you don't need to know that - what you should know is that I have proposed a fix to atlas checks to fix this specific issue.
https://github.com/osmlab/atlas-checks/pull/622
