### ISSUE TITLE
[bug] getting a failure to save state when completing a task.

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/maproulette3#1652]
I tried to mark a task as "fixed" or "Not an issue" and I keep getting a failure screen pop up. I tried a few of my challenges and then tried a random public challenge and got the same results when trying to save state.

![image](https://user-images.githubusercontent.com/5851115/134058556-df1a8d79-7d6a-4f31-b2f9-2a00359bc053.png)

and when I tried to edit a task's status when inspecting it I got this screem.

![image](https://user-images.githubusercontent.com/5851115/134058584-313bb002-c4ed-48a6-ba7a-12f6dbb79062.png)

**Comment by jschwarz2030** [comment]
The issue's been diagnosed and we are back online.  We will be undergoing maintenance this evening as a result.  In the meantime, if you have any bots running, please disable them until further notice.

**Comment by atiannicelli** [comment]
working now...
