### ISSUE TITLE
question: adding maproulette task for relation 

### ISSUE THREAD

**Issue by chromekk** [osmlab/maproulette3#1654]
Hi

Is it possible to add maproulette task which after clicking on "edit" button will redirect to OSM editor and point to given relation?
So far I only managed to create tasks which point to nodes/ways (and it seems that type of the feature was taken depending on linestring/point in given geometry, ignoring my "osmid":"way/xxxxxx" indication).

Forgive me if that's not the right place to ask these, I didn't find clear answer to that issue.

Cheers

**Comment by mvexel** [comment]
Sorry for the late response!
MapRoulette does not support selecting relations as a task source.
