### ISSUE TITLE
Build warning: "caniuse-lite is outdated. Please run next command yarn upgrade"

### ISSUE THREAD

**Issue by ljdelight** [osmlab/maproulette3#1658]
When the front-end builds, it prints many outdated warning messages:
```
$ postcss src/styles/index.css -o src/index.css
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
```

A quick skim of the browserslist manual shows that maproulette deps should be updated to use a newer version of caniuse-lite to (1) not have issues with newer browsers and (2) version deduplication.
See here for more information https://github.com/browserslist/browserslist#browsers-data-updating

**Comment by mvexel** [comment]
@ljdelight @jschwarz2030 can we close this?

**Comment by ljdelight** [comment]
@mvexel should not close this yet, the outdated message is still printed during trunk builds (https://github.com/osmlab/maproulette3/runs/6476577768?check_suite_focus=true#step:5:11)
