### ISSUE TITLE
Broken map view behavior

### ISSUE THREAD

**Issue by Arcturuss** [osmlab/maproulette3#1659]
Currently, when viewing tasks on a map, any map movement (scrolling or zooming) triggers data reloading. When reload is complete, map is moved again to where it was when download started (to show all loaded data maybe).

This cause very annoying jumps and blinking when you just continue to scroll or zoom map before each download operation completes. Even more, it can cause a feedback loop (video below).

https://user-images.githubusercontent.com/465493/137378333-c8497de4-73f5-4baf-952f-9a2d23aed21e.mp4

Proposed solution: don't move the map after downloading data.

**Comment by jschwarz2030** [comment]
raising priority

**Comment by jschwarz2030** [comment]
A proposed fix is currently testable in staging (https://staging.maproulette.org/).  I haven't been able to reproduce the infinite loop.
