### ISSUE TITLE
GUI glitch in Firefox browser

### ISSUE THREAD

**Issue by voschix** [osmlab/maproulette3#1662]
There seems to be a glitch with the GUI in Firefox (latest version) on Windows 10 (latest version) that is not present on Chrome on  the same computer.
In the user dialogue, the menu for the selection of the editor opens only very briefly and closes before you can enter anything. Works on Chrome. I attach a screenshot of the opened submenu in Chrome.
![Ashampoo_Snap_2021 10 30_21h59m45s_045](https://user-images.githubusercontent.com/11076112/139557082-d0d0204c-39e0-4769-a139-a208a80c133f.jpg)

**Comment by jschwarz2030** [comment]
Strange, it seems to be specific to the Firefox/Windows combination.  No luck reproducing on a mac so far.

**Comment by mvexel** [comment]
@voschix is this still reproducible in the current release?

**Comment by voschix** [comment]
Cannot answer the question. 
Login to Maproulette fails for me in Firefox and Chrome on Windows 10 - looks like https://github.com/osmlab/maproulette3/issues/313
