### ISSUE TITLE
Chalenges are not loading properly

### ISSUE THREAD

**Issue by Filip10** [osmlab/maproulette3#1663]
https://maproulette.org/challenge/23176/task/118495908
https://maproulette.org/challenge/21911/task/116666345

After clicking on these tasks, there is only white screen and tasks never loads (see picture).

It happend me in Firefox and I tried to use Edge too, but it ended same.

![screenshot](https://user-images.githubusercontent.com/25711588/139581497-43226750-ed0e-4b72-a37a-24758f537761.jpg)

**Comment by jschwarz2030** [comment]
Reproduced.  Not seeing any API errors so perhaps the frontend isn't addressing a data exception for these specific tasks.  Will keep looking at it.

**Comment by jschwarz2030** [comment]
Visited https://maproulette.org/browse/challenges/21911.  "Challenge does not exist".

**Comment by Filip10** [comment]
> 
> 
> Visited https://maproulette.org/browse/challenges/21911. "Challenge does not exist".

Here are still two tasks from this challenge

https://maproulette.org/browse/challenges?challengeSearch=21.191854476928714%2C48.697475704914616%2C21.309185028076175%2C48.743342295063776&location=intersectingMapBounds

**Comment by Filip10** [comment]
It is happening me again. I think, that I already completed this tasks, but I´m not 100% sure.

https://maproulette.org/challenge/23478/task/120022535
at
https://maproulette.org/browse/challenges?challengeSearch=21.709156036376953%2C48.362294300089644%2C21.943817138671875%2C48.454595033885546&location=intersectingMapBounds

https://maproulette.org/challenge/23478/task/120022533
at
https://maproulette.org/browse/challenges?challengeSearch=20.81394195556641%2C48.882892478137464%2C21.04860305786133%2C48.97424539741496&location=intersectingMapBounds

https://maproulette.org/challenge/23478/task/120022532
at
https://maproulette.org/browse/challenges?challengeSearch=19.59274291992188%2C48.77768651234782%2C20.062065124511722%2C48.96060946834901&location=intersectingMapBounds

https://maproulette.org/challenge/23478/task/120022530
at
https://maproulette.org/browse/challenges?challengeSearch=18.31558227539063%2C48.30603417645622%2C19.254226684570316%2C48.6746400785837&location=intersectingMapBounds

https://maproulette.org/challenge/23478/task/120022529
https://maproulette.org/challenge/23478/task/120022528
at
https://maproulette.org/browse/challenges?challengeSearch=18.073024749755863%2C48.79142893336246%2C18.190355300903324%2C48.8372098277736&location=intersectingMapBounds

**Comment by jschwarz2030** [comment]
Challenge 23176, 21911 and 23478 are flagged as deleted.  Their tasks still show up on discoverability, and that shouldn't be happening.  Looking into.
