### ISSUE TITLE
Cannot open / login to MapRoulette

### ISSUE THREAD

**Issue by T0meky** [osmlab/maproulette3#1664]
Hi,
there is an issue with MR in general. I cannot sign in or even look into the project:

![image](https://user-images.githubusercontent.com/89768710/139827779-ab52f88b-2a75-468f-9395-7d0b58c50a37.png)

Could you look into this issue?

**Comment by jschwarz2030** [comment]
Services should be restored for the moment.

**Comment by T0meky** [comment]
Thank You
