### ISSUE TITLE
[FEATURE REQUEST] Allow users to prioritize challenges with cooperative work

### ISSUE THREAD

**Issue by tsmock** [osmlab/maproulette3#1665]
Moved from maproulette/maproulette2#919

Let us say you have a challenge where some tasks with fixes that are almost certain to be right, and then some tasks where the user has to make a decision on their own.

An example would be a challenge fixing New Zealand waterway directions (the LINZ import done for them didn't properly directionalize the ways).
The challenge generator uses SRTM data (~90m GSD, IIRC), which means that *most* of the time the new waterway direction is correct, but there may be edge cases. Often, the user will be able to overlay the LINZ topo map and just apply the change in JOSM after finding the relevant contour lines.
I would like to be able to prioritize those since they are (a) low hanging fruit and (b) the mapper can do them fairly quickly.

**Comment by mvexel** [comment]
If you're able to add a property to the tasks that would distinguish the 'low hanging fruit' from the rest, you could filter on that. See [docs](https://learn.maproulette.org/documentation/task-priority-rules/). But I may be misunderstanding what you're trying to accomplish?

**Comment by mvexel** [comment]
I *think* I addressed your question, so I am going to close this, but apologies if I haven't and feel free to re-open in that case.
