### ISSUE TITLE
GeoJSON not being processed entirely

### ISSUE THREAD

**Issue by joostschouppe** [osmlab/maproulette3#1670]
Hi,
I've generated about 400 tasks for [a new project](https://github.com/osmbe/play/blob/master/traffic_signs_project/). I haven't been able to load all tasks to MapRoulette just yet.
* First try: I add the tasks as a remote URL, without reading the docs. Eh, my bad: it took "name" as a unique identifier, and that wasn't unique at all. [V1](https://github.com/osmbe/play/blob/master/traffic_signs_project/traffic_signs_maproulette.geojson)
* Second try: I changed the names of the field, so "name" would have the actual unique identifier. Because I thought perhaps some parsings was going wrong, I replaced non-separating comma's with semicolons. [v2](https://github.com/osmbe/play/blob/master/traffic_signs_project/traffic_signs_maproulette_nocomma.geojson), [maproulette challenge here](https://maproulette.org/challenge/23548/). This one is being tested by some experienced mappers
* Third try: I made a much sparser file [v3](https://github.com/osmbe/play/blob/master/traffic_signs_project/traffic_signs_maproulette_newname.geojson) and tried to create a challenge with it: https://maproulette.org/admin/project/46823/challenge/23550 . This one at least gave me an error:
JsResultException(errors:List((,List(JsonValidationError(List(error.expected.jsobject),ArraySeq())))))

I've validated the geojson's with two different validators, and they say all is good. Do you know what is wrong with the data? And is there a tool that can give feedback about what is wrong exactly?

**Comment by joostschouppe** [comment]
Turned out something went wrong when processing the data, and the field with the unique ID wasn't unique anymore. After fixing that issue, it did work!

**Comment by Cj-Malone** [comment]
I also hit this with `"geometry": null`. Removing those or changing to 0, 0 worked.
