### ISSUE TITLE
MaoRoulette challenge not working if there are some rules set up for it

### ISSUE THREAD

**Issue by acamat** [osmlab/maproulette3#1673]
When you have some rules set up for the task it will not load, there are messages like "Oops! Unable to fetch map-bounded tasks" , "Failed to release task lock. Your lock or your session may have expired", "Unable to retrieve latest challenge data from server", "Unable to fetch a task to work on". 
![image](https://user-images.githubusercontent.com/56536271/144382958-31d82833-e234-4bb4-8e18-9e735d7bfbf0.png)

If you remove the rule, challenge works without errors. This started happening a week ago, since then everything was working with rules set up. Can you investigate what is the issue?

**Comment by jschwarz2030** [comment]
This doesn't appear to be reproducible locally and may be prod specific.  Can you provide a specific challenge/task?  Thanks.

**Comment by jschwarz2030** [comment]
This may have been due to the outages during that period of time.  If you do see this issue spring back up, feel free to re-open.  Thanks for reporting!
