### ISSUE TITLE
MapRoulette not working properly

### ISSUE THREAD

**Issue by T0meky** [osmlab/maproulette3#1674]
Hi,
I have a problem with MapRoulette lately.
Most of the time I am not able to even log in to the tool, reviewing my project/challenges or any kind of action like challenge creation is not working without any error like below:

![image](https://user-images.githubusercontent.com/89768710/144405930-ee2b4c99-00de-4de2-9a59-7bc4993214a7.png)

Is there any global problem or it is a case on my side?

Thank You in advance for the feedback and support!

Regards,
Tomasz

**Comment by acamat** [comment]
This is a global issue, I have reported also, this started about a week ago

**Comment by T0meky** [comment]
Saw your issue, but thought it is about a challenge settings, not the global situation.

**Comment by jschwarz2030** [comment]
There's been a lot of investigation this week.  In particular, taskClustering and updateLocations services seem to be taking longer than normal and locking up certain tables for longer periods of time.  Thanks for your patience as we continue to look into this.

**Comment by jschwarz2030** [comment]
There will be a maintenance window tonight at 1 am UTC to resolve system performance.

**Comment by T0meky** [comment]
Thank You!
