### ISSUE TITLE
Translation completed in french

### ISSUE THREAD

**Issue by overflorian** [osmlab/maproulette3#1675]
Hi,
Yesterday in France, me and @gendy54 managed to gather the energy of the community and reviewed the whole translation of MapRoulette.
We are glad to say that we managed to do it! We also reviewed already translated chains and corrected a lot of them too.
We did review and double-check our work together and managed to translate almost all of the chains.
We also populated the glossary https://www.transifex.com/osmlab/maproulette3/glossary/fr/ which is extra-useful when you'd like to do the job seriously.

We still have some questions remaining, see the comment section of these chains https://www.transifex.com/osmlab/maproulette3/translate/#fr/en-us-json/170937372?q=issue%3Aopen

I don't have the status of translators' reviewer so I wonder how to validate all the translation that has been done. If there is a need, I agree to become a translation's validator for french.
Thanks

PS: as part of a small team of french contributors, we will begin to use a lot your great tool in the upcoming months, so expect some feedback from us!

**Comment by jschwarz2030** [comment]
Thank you so much for this contribution!

**Comment by overflorian** [comment]
You're welcome. We are now waiting for the team's help to get it approved/integrated as stated in my first message.

**Comment by jschwarz2030** [comment]
A deployment is going out this Tuesday (Dec 14) and will include translation updates (https://github.com/osmlab/maproulette3/commit/7fc64e125ccb09b5393897f65525852959dc6c15#diff-c4e2a9d0bd1f8543073aa55692f5225d5249dd3beeb87eab8a5b335de327a1b8R2).  

As for review/approval, @mvexel may be the right person to go through your remaining questions (https://www.transifex.com/osmlab/maproulette3/translate/#fr/en-us-json/170937372?q=issue%3Aopen).

**Comment by overflorian** [comment]
Thanks for this deployment. @gendy54 @PanierAvide and I will double check it.
@mvexel could you please provide some useful context directly in the Transifex interface?

(for the story, I really discovered advanced features of transifex in the process. We pushed the limit: populated the glossary, check the automatic errors... I believe we made some great job here)

**Comment by overflorian** [comment]
Thanks @mvexel for your replies. We are adding new suggestions, please check Transifex tomorrow
