### ISSUE TITLE
Two usernames for one MapRoulette account 

### ISSUE THREAD

**Issue by Wetterauer** [osmlab/maproulette3#1676]
I have changed my OSM username.  In MapRoulette the new name is used since then.
Only in the menu item "Create & Manage" the old username is still displayed and used.

**Comment by jschwarz2030** [comment]
I am unable to reproduce this.  Which specific page (URL would be helpful) and location on the page are you seeing this?

**Comment by mvexel** [comment]
Closing after inactivity.
