### ISSUE TITLE
Are the MR tags really needed?

### ISSUE THREAD

**Issue by overflorian** [osmlab/maproulette3#1680]
Hi, I discovered recently the "MR tags" that could add extra meta-data while working on a challenge.
I still don't understand why it would be needed. I asked various other experienced french contributors and we, collectively, can't really figure out why this feature exists.

Sometimes, "less is more": we suggest to remove the "MR tags" because it pollutes the interface and stop the contributors from focusing on the really important buttons on the interface.

If you find a real use to the MR tags, an alternative could be that you make it optional as a new option while creating a challenge. In this case, I suggest you turn it off by default.

**Comment by mvexel** [comment]
The MR tags have been added after feedback from users to have a more flexible way to add tag-style metadata at the task level. They are in active use and we have no plans to deprecate them. I appreciate your 'less is more' remark, and we always try to be mindful of feature creep, but in this case, we will not consider removing this feature at this time. I do appreciate your thoughts on the topic though!

**Comment by overflorian** [comment]
OK, that's duly noted. Regards
