### ISSUE TITLE
Correction for a translatable string

### ISSUE THREAD

**Issue by overflorian** [osmlab/maproulette3#1681]
Hi,
Following a discussion on transifex (cf. https://www.transifex.com/osmlab/maproulette3/translate/#fr/en-us-json/306664640?q=translated%3Ano), I suggest that this translated sting https://www.transifex.com/osmlab/maproulette3/translate/#fr/en-us-json/170938013 would be the only one used on the homepage.
In consequence, the string https://www.transifex.com/osmlab/maproulette3/translate/#fr/en-us-json/306664640?q=translated%3Ano would be deleted.

This is the catch-phrase of the website, it seems to me to be a big deal enough to deal with this issue.
Thanks

**Comment by mvexel** [comment]
Makes sense to me. @jschwarz2030 can you determine why the string `Be an instant` is in the localization base strings?
