### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by overflorian** [osmlab/maproulette3#1682]
Hi, "Mondial classement" as a french translation for "worldwide ranking" does not make any sense:
![image](https://user-images.githubusercontent.com/11553211/146646056-2494a8b4-3b26-4b67-ac44-52ade3be7849.png)

For us, we would need: "Classement mondial"
and for other countries, it would be: "Classement : France" or "Classement : Algérie"

Could you please fix that?

**Comment by jschwarz2030** [comment]
Should be resolved with the tagged PR.  Feel free to reopen if you see further problems from the changes.  Thanks for reporting!

**Comment by overflorian** [comment]
Thank you
