### ISSUE TITLE
Missing translatable string

### ISSUE THREAD

**Issue by overflorian** [osmlab/maproulette3#1683]
On the page https://maproulette.org/browse/challenges the "show archived" string should be translated:
![image](https://user-images.githubusercontent.com/11553211/146646208-9e51eba8-8075-4c03-975a-e389ff26c42d.png)

Is it missing in Transifex? Of maybe this string should be used? https://www.transifex.com/osmlab/maproulette3/translate/#fr/en-us-json/328033109
You tell me! Thanks

**Comment by jschwarz2030** [comment]
Should be resolved with the tagged PR.  Feel free to reopen if you see further problems from the changes.  Thanks for reporting!
