### ISSUE TITLE
Missing translatable string (2)

### ISSUE THREAD

**Issue by overflorian** [osmlab/maproulette3#1684]
In the page https://maproulette.org/user/profile the string "should match format "email" is not included in the transifex translation.
![image](https://user-images.githubusercontent.com/11553211/146647114-e755322d-95a6-4606-be1b-d1602855cf99.png)
Please add it to transifex so we can translate it.

**Comment by overflorian** [comment]
There is also this bit:
![image](https://user-images.githubusercontent.com/11553211/146647166-d9902607-e57b-4876-a85f-b12c9265d277.png)
Thanks

**Comment by jschwarz2030** [comment]
Should be resolved with the tagged PR.  Feel free to reopen if you see further problems from the changes.  Thanks for reporting!
