### ISSUE TITLE
Missing translatable strings (3)

### ISSUE THREAD

**Issue by overflorian** [osmlab/maproulette3#1685]
On the page https://maproulette.org/admin/projects/new the following strings are missing as translatable strings:
![image](https://user-images.githubusercontent.com/11553211/147068340-2aef1074-9dc8-4105-8f15-4d82dc22c355.png)
Please add them to Transifex.

**Comment by overflorian** [comment]
Also, on this same page:
![image](https://user-images.githubusercontent.com/11553211/147069272-14c6c2e3-e2f1-48f7-88e4-6fcc34550044.png)

**Comment by jschwarz2030** [comment]
Should be resolved with the tagged PR.  Feel free to reopen if you see further problems from the changes.  Thanks for reporting!

**Comment by overflorian** [comment]
Thank you
