### ISSUE TITLE
Approve french translation suggestions

### ISSUE THREAD

**Issue by overflorian** [osmlab/maproulette3#1693]
Hi,
There is a lot of french translation suggestions waiting in Transifex https://www.transifex.com/osmlab/maproulette3/translate/#fr/en-us-json/170937385?q=user_suggestions%3Ayes
Could you please make me admin (or change my status in a way that I could approve these suggestions)?
As you can see I'm a lot into translating the tool and I feel to be legitimate to improve it any way possible.
Thanks in advance

**Comment by jschwarz2030** [comment]
I went ahead and approved everything.  I'm working with @mvexel to see if we can add you to the project.  Thanks for your continued contributions.

**Comment by mvexel** [comment]
@overflorian I added you as a language coordinator for French, let me know if that gives you the tools you need to move the French localization forwardn

**Comment by mvexel** [comment]
And thanks for all your work on this!!

**Comment by overflorian** [comment]
You are welcome. That's a pleasure to help such a great project.
Thanks for giving me the rights. I translated some more content and made them reviewed by other french speakers before approving them.
