### ISSUE TITLE
Mapillary Data Layer

### ISSUE THREAD

**Issue by thomersch** [osmlab/maproulette3#1704]
It seems to me that the Mapillary data layer has stopped working, I am guessing due to an API change on Mapillary's side...?

When I select it from the layer selector:
<img width="323" alt="Screenshot 2022-02-11 at 14 09 42" src="https://user-images.githubusercontent.com/948605/153597092-839e6e1e-5b7b-40f1-8ae8-d8374a37ffd1.png">

I get:
<img width="353" alt="Screenshot 2022-02-11 at 14 09 45" src="https://user-images.githubusercontent.com/948605/153597113-65f61da9-beb8-42a0-9886-c98731fbf8f2.png">

On the console: `GET https://a.mapillary.com/v3/images?bbox=-122.05928564071657,37.67168603836614,-122.054500579834,37.675193212931696&per_page=1000&client_id=NFM4WmEtVTJ1MkREaHBTUTN1VDZ5ZzozYjA0NTQwNGYzMDM4NWUy net::ERR_NAME_NOT_RESOLVED`

**Comment by jschwarz2030** [comment]
Looks like you're correct.  V3 is no longer supported and we'll need to upgrade to V4.
