### ISSUE TITLE
Add import guidelines notice for GeoJSON and URL task types

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/maproulette3#1718]
For the GeoJSON and URL task type choices, or when otherwise importing(/using) data, mention to authors to be aware of import guidelines and compatible license requirements https://wiki.openstreetmap.org/wiki/Import/Guidelines .

This can be done using a notice (say a yellow text box) underneath the task type choices when choosing the GeoJSON or URL option.
A similar text block can also be added in the documentation section for these task types and optionally #1316 can be added (avoid duplicate links).

**Comment by mvexel** [comment]
MapRoulette cannot perform imports [as defined on the OSM wiki](https://wiki.openstreetmap.org/wiki/Import) as "the process of uploading external data to OSM.". So the import guidelines as such do not apply.

MapRoulette can be used to evaluate and manually add data from external sources on a feature-by-feature basis, which is not the same. The Challenge author should take responsibility to point out to the mapper that their challenge uses an external data source and add the appropriate changeset source comments to the Challenge metadata. There is no way MapRoulette can determine if a Challenge uses external data or not.

**Comment by danieldegroot2** [comment]
> The Challenge author should take responsibility to point out to the mapper that their challenge uses an external data source and add the appropriate changeset source comments to the Challenge metadata.
You could add this text somewhere regardless.
