### ISSUE TITLE
Add source notice to Detailed Instructions

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/maproulette3#1719]
Add a notice/mention to Detailed Instructions for authors (of mainly local tasks) to specify what imagery/data layers or other sources mappers should preferably(/could) use.

**Comment by mvexel** [comment]
There's already two solutions for this:
1. Challenge authors can pre-set the imagery layer to show by default, and even provide their own custom tile server
2. The challenge description and task instructions are free form fields where the challenge author can include this information.

**Comment by danieldegroot2** [comment]
Many authors forget to do 2. when they want to suggest multiple layers -they may or may not still do 1.-. Including a mention of this somewhere would be helpful. Especially for areas with DEMs etc. (sometimes not in iD) which mappers may not know of.
