### ISSUE TITLE
Add validation notice

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/maproulette3#1721]
Add a notice to Create & Manage -and/or send an email ( #1543 ) once a ~~project~~ challenge is done- to remind authors validation of completed tasks is important to ensure data quality. A notice/mention can also be added at the documentation page (under 'Create a Challenge').

**Comment by mvexel** [comment]
This already exists for Challenges -- are you suggesting to add notifications when an entire Project is completed, too?

**Comment by danieldegroot2** [comment]
I meant challenge. Could I review the text for this anywhere?

**Comment by mvexel** [comment]
Here: https://github.com/osmlab/maproulette3/blob/9995d67975f9db7edbda4a99b895101e3c0b6c45/src/pages/Inbox/Messages.js#L134

In your MR inbox / email, it would be followed by the name of the challenge.

**Comment by danieldegroot2** [comment]
This is simply a notification which congratulates users one of the challenges they manage has been completed. It does not say anything in order to encourage them to validate/verify (part of) their challenge. For example:
> Try reviewing some tasks.
A longer description could be
> Have a look at some of the tasks and comments in your challenge to see if users understood the instructions you provided and to make sure there are no inappropriate contributions / vandalism. This step will help make your challenges even better.
