### ISSUE TITLE
Blank map with Maxar Imagery Standard (Beta) layer 

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1726]
Outdated API id?

![image](https://user-images.githubusercontent.com/5821688/160220291-2e9c8feb-843b-404e-9d5c-c88e84f63e83.png)

Other layers for the same region appear to be working alright:
![image](https://user-images.githubusercontent.com/5821688/160220315-5e3049af-007f-4f03-bff7-c77dd84f7866.png)

**Comment by mvexel** [comment]
I think we may need to re-pull from the [imagery database](https://github.com/osmlab/editor-layer-index). @jschwarz2030 do you think that would solve this problem?

**Comment by jschwarz2030** [comment]
Maxar Standard is no longer in service and we are switching to Maxar Premium.  After changing our configuration, it appears to be working in staging and production.  This should be fully resolved.  Thanks for reporting!
