### ISSUE TITLE
Impossible angle in a highway

### ISSUE THREAD

**Issue by marsip** [osmlab/maproulette3#1729]
What are the criteria for "imposssible angle in a highway"?

In project https://maproulette.org/browse/challenges/27178, there lot of these.

What I mean is the junctions between the main and the link roads, where the link road become an own osm-way. Many of these are flagged as errors. But they are mapped according to https://wiki.openstreetmap.org/wiki/Key:lanes (examples last on the page).

The wiki doesn't say anything about how sharp the bend is allowed to be, so I assume this is a subjective decision.

**Comment by mvexel** [comment]
Hi, for a question about a particular challenge, please [contact the challenge owner](https://learn.maproulette.org/documentation/reporting-a-challenge/#content).
