### ISSUE TITLE
Custom Basemap setting ignored

### ISSUE THREAD

**Issue by 1ec5** [osmlab/maproulette3#1730]
The map widget on the task page always defaults to the Standard layer, even if I specify a custom basemap URL in the challenge settings. When launching iD, MapRoulette omits the `background` parameter from iD’s URL:

https://github.com/osmlab/maproulette3/blob/e785c0e49af2b0bfcd9ffadbcbb199da6cca2ee5/src/services/Editor/Editor.js#L286-L292

Reproduces in [this project](https://maproulette.org/challenge/25951/task/127160810).

**Comment by jschwarz2030** [comment]
should be resolved with https://github.com/osmlab/maproulette3/pull/1746
