### ISSUE TITLE
Way is not way?

### ISSUE THREAD

**Issue by Filip10** [osmlab/maproulette3#1732]
Can somebody help me please with this query? [Overpass turbo](https://overpass-turbo.eu/) is giving me ways out of this query, but maproulette challenge with **Overpass target type** set to _**ways**_ is giving me error. 
![obrázok](https://user-images.githubusercontent.com/25711588/166226575-2d10a814-8249-4d44-8244-2b38206023d1.png)
When I choose **_any_**, than it make tasks from each point of these ways.
![obrázok](https://user-images.githubusercontent.com/25711588/166226408-9b6b945b-b8b8-426c-a72d-e8798c54e0e8.png)

```
[out:json][timeout:200];
area(id:3600014296)->.searchArea;

(
  way["name"~"štál"]["place"!="locality"]["office"!="notary"]["highway"!="residential"]
  ["natural"!="peak"]["natural"!="cave_entrance"]["place"!="hamlet"]["amenity"!="pharmacy"]
  ["tourism"!="information"]["highway"!="bus_stop"](area.searchArea);
);

out body;
>;
out skel qt;
```

**Comment by danieldegroot2** [comment]
See **Beware of Recursions** under "[Using Overpass to create Challenges](https://learn.maproulette.org/documentation/using-overpass-to-create-challenges/)"

This page is located in the Documentation ("Learn" in the top menu of Maproulette itself) and is shown to users when creating a challenge using  an Overpass query.

I hope this resolves your issue. If so, feel free to close this issue yourself using the purple :heavy_check_mark:  "Close issue" button located under the comment box below. You can always re-open or comment on this issue if needed.

![image](https://user-images.githubusercontent.com/67521919/167299270-d566ed68-b454-4af1-840c-4d850366b435.png)

**Comment by Filip10** [comment]
Great. Thank you very much :)
