### ISSUE TITLE
German translation "Next task:" * Random * Nearby

### ISSUE THREAD

**Issue by wolfgang-8** [osmlab/maproulette3#1735]
In the option fields "Nächste Aufgabe" and "Lade nächste", the English terms "Random" and "Nearby" are currently translated to "Random" and "Proximity". 

These terms are not very common in German usage and this can lead to comprehension difficulties. So, I'd like to suggest the German term "Zufällig" for "Random" and "In der Nähe" for "Nearby". I think, that's more intuitive for German speaking people.

![Screenshot_Fertigstellung](https://user-images.githubusercontent.com/105060323/167153369-aa365399-fc4f-4462-b78a-c5ba7058cc3c.jpg)

![Screenshot_Bitte_Bestätigen](https://user-images.githubusercontent.com/105060323/167154300-ee5f1e01-eda2-421f-865c-9f194ed4f545.jpg)

**Comment by danieldegroot2** [comment]
Hey @wolfgang-8,

Translating Maproulette 3 to locales other than en-US is done on Transifex. (From the [README.md](https://github.com/osmlab/maproulette3/blob/main/README.md#internationalization-localization-and-translation))
* [German translations on Transifex](https://www.transifex.com/osmlab/maproulette3/viewstrings/#de/en-us-json/311982842)

You can find the edit button in the top right; you'll have to register with Transifex.
_Note, it may take a while for translations to come through (they may come through with the next major update, or at the end of the month)._
_Also, some of your translations may get saved as "Suggestions" - they should come through eventually. If not, and you are translating numerous strings (lines of text), you can ask someone to validate them and/or additional permissions in a new GitHub ticket._

When you are unsure whether to contribute a translation, or if a translation has multiple favourable translations in use, you may want to discuss them with your (local) community using their [Contact channels](https://wiki.openstreetmap.org/wiki/Contact_channels).

I hope this resolves your issue. If so, feel free to close this issue yourself using the purple :heavy_check_mark:  "Close issue" button located under the comment box below. You can always re-open or comment on this issue if needed.

PS: If you want to translate Maproulette 3's [documentation](https://learn.maproulette.org/), please get in touch with the MapRoulette team at [maproulette@maproulette.org](mailto:maproulette@maproulette.org).

_For other, unrelated OpenStreetMap translation projects, see the [Translation](https://wiki.openstreetmap.org/wiki/Translation) page on the OpenStreetMap Wiki._
