### ISSUE TITLE
Line-by-line GeoJSON yields 1 task instead of expected 4897

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#1748]
A MR user noted that they tried to create a challenge with a line-by-line geojson file and it yielded only 1 task instead of the 4897 lines worth of features in the file. 

Looking at the file I thought the cause might have been that the GeoJSON `Feature`s were not wrapped in a `FeatureCollection` but after fixing this, the result is still a challenge with 1 task. 

When I upload the GeoJSON and create the challenge, the interface does suggest that all tasks are being created (the task counter goes up).

Attached the original GeoJSON as the user supplied it to me and my 'fixed' `FeatureCollection` version.

The challenge I tried to create [is on staging](https://staging.maproulette.org/browse/challenges/23720).

[geojsons.zip](https://github.com/osmlab/maproulette3/files/8765006/geojsons.zip)

**Comment by mvexel** [comment]
A quick update. I replaced the standard line endings with  (`0x1e`) as [required by MapRoulette](https://learn.maproulette.org/documentation/line-by-line-geojson/) but that yields an error:

<img width="914" alt="Screen Shot 2022-05-24 at 12 21 43" src="https://user-images.githubusercontent.com/120452/170105694-93a22731-36b4-4773-a13c-8e296a68505e.png">

See attached JSON:

[line-endings.zip](https://github.com/osmlab/maproulette3/files/8765326/line-endings.zip)

**Comment by jschwarz2030** [comment]
The api considers `name: null` a unique identifier and should be omitted from the json.  This does conflict with our documentation so i'll investigate a fix for the api to drop null names

**Comment by mvexel** [comment]
`null` is a [valid JSON literal](https://datatracker.ietf.org/doc/html/rfc7159#section-3) so we should treat it as a proper null value. I suggest we drop any keys from the source JSON that have a `null` value. (That is, a `null` literal, not the string `"null"`.

Separately, treatment of the `name` field as an external identifier is [documented](https://learn.maproulette.org/documentation/setting-external-task-identifiers/#content), however, since this JSON also has an `ID` field, that should have taken precedence and the `name` key should have been ignored when looking for an external identifier, unless this is a case-sensitive key lookup?

**Comment by jschwarz2030** [comment]
> `null` is a [valid JSON literal](https://datatracker.ietf.org/doc/html/rfc7159#section-3) so we should treat it as a proper null value. I suggest we drop any keys from the source JSON that have a `null` value. (That is, a `null` literal, not the string `"null"`.

Correct.  I rushed my last comment, so for clarification, my fix would account for this.

> Separately, treatment of the `name` field as an external identifier is [documented](https://learn.maproulette.org/documentation/setting-external-task-identifiers/#content), however, since this JSON also has an `ID` field, that should have taken precedence and the `name` key should have been ignored when looking for an external identifier, unless this is a case-sensitive key lookup?

Good catch.  This was part of the root cause of the issue as well.  JSON is case-sensitive and should arguably be treated as such, especially keys.  We could certainly add capitalized values as acceptable externalIDs, but they will probably need to be identified as separate keys.

**Comment by mvexel** [comment]
> Good catch. This was part of the root cause of the issue as well. JSON is case-sensitive and should arguably be treated as such, especially keys. We could certainly add capitalized values as acceptable externalIDs, but they will probably need to be identified as separate keys.

I am leaning towards only accepting lowercase keys for the external IDs, just to keep things simple.

We will want to clarify key case sensitivity [in the documentation](https://learn.maproulette.org/documentation/setting-external-task-identifiers/#content) as well. I will take care of that.

**Comment by jschwarz2030** [comment]
Going to close in favor of https://github.com/osmlab/maproulette3/issues/1761 as an enhancement to our MR ID tooling.  For the time being, the reported issue can be avoided by not including `{"name": null }` in the geojson.

Also, I've confirmed that the original issue is not related to line-by-line record separators. However, @mvexel if you are still seing this https://github.com/osmlab/maproulette3/issues/1748#issuecomment-1136301215, we should create a specific bug report with repro steps.  Currently I am able to create a challenge in staging just fine with the geojson you provided, as long as `{"name": null}` is removed, whether record separators or new-line separators are provided.
