### ISSUE TITLE
Nearby option relative to first task

### ISSUE THREAD

**Issue by boothym** [osmlab/maproulette3#1750]
Basically, I would like to be able to fix each task within a certain area - let's say within a 10 mile radius of the first task.

However what usually happens is that if you select "next task: nearby" on each task, it is likely you will end up miles away in one direction from your first task. Presumably because your second task is off in one direction, then your third task is relative to your second task and so on.

Instead it would be good if there was a "nearby first task" option, which would find unresolved task nearby your first task.

Hope I've explained this correctly! 😄

**Comment by mvexel** [comment]
You could create a virtual challenge for that purpose. In the Find Challenge screen, zoom and pan the map to the area you want to work in, use the filters to narrow down to the challenge(s) you want to work on, draw a lasso on the map, and start your challenge.

I realize the documentation about virtual challenges is pretty minimal.. I opened a [ticket on the docs repo](https://github.com/maproulette/docs/issues/21) to remind us to do something about that.

**Comment by boothym** [comment]
Wow, interesting - didn't know this featured existed. The +/- lasso on the right hand side of the map is not obvious at all, only now that you have pointed those buttons out did I realise they were there!

However once draw with the lasso, click work on selected tasks then add a name - I get the following error:

Oops!
Unable to create a virtual challenge{details}
