### ISSUE TITLE
[question] Trying to change the status of 800 tasks to disabled, but getting an error

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1764]
Hello. I'm trying to change the status of some tasks to "disabled" but I often I get this error message:

![image](https://user-images.githubusercontent.com/5821688/174225223-264de59f-3255-4d09-a61e-a7824d7b3bed.png)

I get this error 4/5 times, and for those times I'm successful I try to select less than 10 tasks -- but even with that, I get inconsistent results.

**Comment by govvin** [comment]
I tried this again just now, and everything worked as expected.  

I'm not sure what happened. Maybe the server was busy earlier? I'll  update the ticket again the next time I clean-up the challenge.

**Comment by govvin** [comment]
I tried this again today, and I'm still getting the same error message. 

I also observed that although I get the error notification, it appears that some of the tasks that are affected by the operation is carried out, but not everything that I selected.

**Comment by jschwarz2030** [comment]
I'm testing with a challenge with over 4000 tasks and can definitely reproduce this issue.  Looks like I'm hitting the API timeout threshold in the frontend, however, ultimately, all of the tasks statuses do get updated (at least for me).

Not quite sure what the proper fix is yet, but will keep this in mind.

The workaround appears to be to:
1. keep using the call
2. ignore the error if it pops up
3. filter out the status your updating to to see if there are remaining unchanged tasks
4. select-all again and update
5. repeat if necessary

In all of my tests, eventually all tasks get updated on the first attempt.  it just takes a little longer than expected.

**Comment by govvin** [comment]
Unfortunately for me, the tasks don't get updated. So, the tedious "workaround" is to keep updating the tasks until they're, well, updated.

Sometimes, no matter how many tasks are selected, only 1 or 2 gets updated. If I get lucky, perhaps, a dozen gets updated -- and I'm rarely lucky. Tried doing the same on different hours, perhaps, when the server is less busy, but no luck there.

Updated the ticket name to "bug".
