### ISSUE TITLE
[feature request] Layout template behavior. Wish it's possible to set one as default.

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1765]
![image](https://user-images.githubusercontent.com/5821688/174517462-fecc6f2e-6de3-4db3-99df-0e02468f739f.png)

I use different tasking templates that is most appropriate (or comfortable) for whatever device I'm using. I wish there's a way to either select a specific template as default, or to re-arrange the order of the templates.

As it is, the first template is always the default, even if prefer something else that I might use more often.

**Comment by govvin** [comment]
By the way, the workaround I use now is to reset the first template as "default" -- but exporting the settings first, and re-importing it to a new one.

**Comment by jschwarz2030** [comment]
@govvin is the solution here https://github.com/osmlab/maproulette3/pull/1776 sufficient to your needs (A selected layout will now persist)?  Or do you still want the functionality expanded upon?

**Comment by govvin** [comment]
@jschwarz2030 , thank you for that. It's working well for me!
