### ISSUE TITLE
shortcut legend are not coherent with quickfix buttons

### ISSUE THREAD

**Issue by Binnette** [osmlab/maproulette3#1804]
Hello,

The shortcuts legends are not coherent with QuickFix challenge buttons
![image](https://user-images.githubusercontent.com/6597721/185711804-ab3eaa99-3add-4247-b266-b22fc105bd40.png)

Here instead of `f I fixed it`, it should be `f yes` or `y yes`. Same for no, etc.

TY for this great app and TY for fixing my issue :heart:

**Comment by mvexel** [comment]
Yes, the legend should be context dependent. We'll size this and fix it either in 3.11 or the release after that.

**Comment by Binnette** [comment]
Great thank you @mvexel
