### ISSUE TITLE
Every page has the same title

### ISSUE THREAD

**Issue by 1ec5** [osmlab/maproulette3#1807]
Every page has the same HTML page title, “MapRoulette”. This makes it difficult to distinguish multiple tabs open to various MapRoulette pages or find a certain challenge in browser history. Most pages have an `<h1>` tag that would be suitable for `<title>` as well.

**Comment by aawiseman** [comment]
This is a good suggestion! I've noticed that too, also when I have multiple tabs open

**Comment by mvexel** [comment]
agree this needs to be addressed. Tagging for 3.11

**Comment by jschwarz2030** [comment]
Going to go with the following implementation:

For all pages, refer to the url for a user friendly page name

For example: https://staging.maproulette.org/browse/challenges 's page name should be `Maproulette - Browse - Challenges`

There is one exception:  For specific projects and challenges, we want to swap ids out for their actual names

For example: https://staging.maproulette.org/admin/project/46942/challenge/23697 's page name should be `Maproulette - Admin - {Project Name} - {Challenge Name}`
