### ISSUE TITLE
Changeset comment not included

### ISSUE THREAD

**Issue by angoca** [osmlab/maproulette3#1828]
I have created a couple of challenges, but they never include a predefined text as part of the commit, even if I have specified.

This is one of the challenges: https://maproulette.org/admin/project/46513

This is the changeset description: #ColombiaDivisionPolitica #maproulette

What should I do to include a template for the commit message?

**Comment by mvexel** [comment]
Hi @angoca - I cannot reproduce. I tried [this task](https://maproulette.org/challenge/23102/task/137155472) and get the following upload dialog in iD:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/120452/193902376-54638aaf-6fca-4589-b04b-28d1f52c75ee.png">

Is this not what you were expecting?

**Comment by angoca** [comment]
I was trying from JOSM, not iD.

**Comment by mvexel** [comment]
In JOSM I get 

![image](https://user-images.githubusercontent.com/120452/194148150-98e6d775-b50c-427d-8ab7-d1147ad0b757.png)

which looks pretty similar. Is this not what you were expecting to see?

**Comment by angoca** [comment]
I see there should be an issue from my side. Thank you for the support.
