### ISSUE TITLE
Can't open projects anymore

### ISSUE THREAD

**Issue by lovelyfurball88** [osmlab/maproulette3#1840]
https://user-images.githubusercontent.com/81121578/195992671-b949843f-848d-4094-bb11-2a1f9f2562bf.mov

For some reason, when trying to open a project, Maproulette doesn't allow you to see it and takes you to the management screen.

**Comment by jschwarz2030** [comment]
Thanks for reporting!  I've confirmed this is a regression from our recent deployment.  I'll deploy a hotfix as soon as possible.

**Comment by mvexel** [comment]
Did the hotfix fix this for you @lovelyfurball88 ?

**Comment by lovelyfurball88** [comment]
Yes, thank you for getting this fixed!
