### ISSUE TITLE
modal window where you're asked to select your next task is now "full screen"

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#1856]
I'm not sure if this has to do with my recent Firefox (v106.02) update, but now, the modal window where you select your next task is now shown in "full screen" rather than a window.

![image](https://user-images.githubusercontent.com/5821688/200993896-79193ba2-6c94-4ce3-b08b-dcf3d844d27e.png)

**Comment by govvin** [comment]
Additional details.

It appears to be only happening if "nearby" option is selected.

When "random" is selected, it works as expected:
![image](https://user-images.githubusercontent.com/5821688/201040864-77e79ce6-e4a4-4504-b854-34a31e3a4803.png)

But not when "nearby" is selected:
![image](https://user-images.githubusercontent.com/5821688/201040801-73c8b14f-4185-45ae-b464-202be59b8ac7.png)

**Comment by jschwarz2030** [comment]
yes.. this is a new feature in response to the issues reported in https://github.com/osmlab/maproulette3/issues/1778.  I implemented a full screen modal to maximize use of the screen to make it easier to find new tasks.  Is this causing a new issue for you?

**Comment by govvin** [comment]
hi @jschwarz2030 .

Nope, I don't feel that it's an issue but the change between the two windows was so different from the previous behavior I thought it was a bug. :smile_cat:  I actually like the huge map, although I thought it would be sufficient to zoom (and size) in the area around the displayed tasks?

**Comment by jschwarz2030** [comment]
yeah i follow ya.  i don't see a straightforward approach to solve your ticket directly and was the fullscreen modal would mitigate most of the trouble you reported.
