### ISSUE TITLE
Find challenges in Colombia

### ISSUE THREAD

**Issue by JuanMeloColombia** [osmlab/maproulette3#1866]
I write because since the weekend I can't find any challenges in Colombia, even the challenges that I have created are imposible to find using the "search box", in Colombia there are many projects created for other users to be solved and with this problem I can't work in it.
![Error_Mapillary](https://user-images.githubusercontent.com/118753175/203096808-dcdadc74-1d8c-4b92-bde0-82646c516d6f.JPG)

**Comment by jschwarz2030** [comment]
Thanks for reporting.  I've confirmed this is a regression from last week's deployment.  Hotfix underway.
