### ISSUE TITLE
Rethink Project view

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#221]
If you look at the metrics at the level of your user's project, you see a nice turndown chart.

<img width="583" alt="screenshot 2018-03-26 10 59 51" src="https://user-images.githubusercontent.com/120452/37920707-da2b2972-30e4-11e8-8b25-2e2495cff9f6.png">

Sweet! My challenges received some love. But which ones?

It would be great to be able to know this somehow. More generally this means some thinking about what and how to visualize in the Project section. I don't know if any of this was addressed in #207 but let's use this ticket to explore ideas.

**Comment by mvexel** [comment]
Exploring the current Projects overview:

![screenshot 2018-03-26 13 27 17](https://user-images.githubusercontent.com/120452/37928238-6e143dd6-30f9-11e8-8baa-911aeecab88e.png)

The first thing that strikes me is that the information density is low here. For an administration screen I'd want it to be higher. 

What I'd expect from my Project screen:
* Quick access to my Challenges, such as a list that is sortable by salient properties (% fixed, % skipped, etc, like in MR2), and with quick actions (edit challenge, see metrics, make visible / invisible, download comments, download tasks + status as GeoJSON, perhaps other...)
* Overall metrics of how all my Challenges are doing (tasks remaining, numbers fixed / skipped etc in past week / month / custom)
* Notifications about Challenges recently completed, if any
* How many people 'saved' my challenges

I'd love to hear others' input on this!

**Comment by mvexel** [comment]
I renamed this issue to reflect the broader topic I am looking to address.

**Comment by mvexel** [comment]
Another thing that's missing in the Challenge list is whether the Challenge still has Tasks left to work on. I think in the previous version we set the Challenge to invisible when the last task was solved (didn't we @mgcuthbert ?) so if we still do that it would be reflected in the visible / invisible status -- but I'd still want to distinguish between manually set to invisible and set to invisible automatically because of no tasks left.

**Comment by mvexel** [comment]
I toyed around a bit with a Challenge list for the project page. This sort of mimics the MR2 list style, but a bit more concise. 

<img width="874" alt="screenshot 2018-03-27 15 35 47" src="https://user-images.githubusercontent.com/120452/37996603-7cef7d2a-31d5-11e8-85da-53e2cf329e17.png">

**Comment by mgcuthbert** [comment]
@mvexel A challenge is not set to invisible when it is complete, however it is removed from some of the search and browse API's based on the fact that there are no more available tasks.

**Comment by nrotstan** [comment]
Last-activity date has been added in the develop branch, which I believe completes the data requested in the mockup above, so I'm marking this issue as fixed in develop. Having said that, a table is not ideal and we're in the process of moving to an alternative layout that will be practical on laptops and smaller screens while still preserving the needed information density.
