### ISSUE TITLE
Offer search by task id/name when challenge owner viewing a challenge

### ISSUE THREAD

**Issue by nrotstan** [osmlab/maproulette3#232]
When a challenge owner is viewing a challenge (with the table of tasks), offer the ability to search for a task by task id or task name.

**Comment by mgcuthbert** [comment]
Is this needed, considering that during creation of tasks from geojson or overpass query the ids and names can be somewhat random. Maybe there is a use case I am not thinking about, but I can't imagine it being used much.

**Comment by nrotstan** [comment]
I mostly found myself wanting it when looking up a problematic task to view administrative details (like the GeoJSON) or edit it, but maybe the right way is to provide administrative-related info on the Task Review screen and make it easy for challenge owners to get there when needed (via comment links, and perhaps an option to switch to review mode from a standard task link someone sent them, etc). Or maybe that doesn't happen often?

Mainly, my thinking was that when there is a problem reported with a task (probably via comment or a direct end-user link in external communication), I wanted it to be easy for a challenge owner to pull up the information for that task and/or edit it without having to track the task down.

**Comment by mgcuthbert** [comment]
No I kind of see you point in that. Search probably would be the easiest approach, I simply had not considered that use case.

**Comment by mvexel** [comment]
Going over stale issues. I would still like this :)

**Comment by nrotstan** [comment]
Closing, as this is now mostly addressed by the feature-property search functionality (PRs #959 and #1040), which makes it much easier to locate specific tasks within a challenge.
