### ISSUE TITLE
Unable to Save 

### ISSUE THREAD

**Issue by DrishT** [osmlab/maproulette3#282]
Indonesia team is seeing this message once they have fixed the issue. 20 or so people are working on the same task. Internet does not seem to be Intermittent.

[WhatsApp Video 2018-04-02 at 13.04.10.mp4.zip](https://github.com/maproulette/maproulette3/files/1873906/WhatsApp.Video.2018-04-02.at.13.04.10.mp4.zip)
<img width="1548" alt="screen shot 2018-04-03 at 5 18 42 pm" src="https://user-images.githubusercontent.com/7559566/38282093-19e0523e-3763-11e8-8256-85ef423aef5a.png">

**Comment by DrishT** [comment]
That could possibly be the issue. Attached the video sent with the dev console to see if that helps identify the issue better.

[can not save the changes in MR old version (1).mp4.zip](https://github.com/maproulette/maproulette3/files/1877532/can.not.save.the.changes.in.MR.old.version.1.mp4.zip)

**Comment by mvexel** [comment]
ping @mgcuthbert and @nrotstan on this issue.

**Comment by mgcuthbert** [comment]
The task is locked the moment it is served to the user on the backend. So unless a locked task is accidentally being served to a user, which through some API calls that is altogether possible. However the API calls that the UI makes to get the next task, requires that it retrieves only unlocked tasks. 

I wouldn't imagine that you are doing this, however if you are sharing an openstreetmap user, then it could. As the task is locked based on the user, and not the browser session. You can recreate this type of scenario by simply opening two different tabs in your browser, or two different browsers.
