### ISSUE TITLE
Don't redraw map if next task is located within the bounds of the current task.

### ISSUE THREAD

**Issue by mgcuthbert** [osmlab/maproulette3#298]
Whenever you click on the next task, the Map will essentially redraw itself. For a lot of cases this is probably ok, however if you get a task within the current bounding of the task you are working on (maybe you zoomed out maybe it is just really close - ie. using the proximity option) then it is strange and annoying that the map has to redraw itself to essentially display the same thing.

**Comment by nrotstan** [comment]
This makes sense. We actually started making a big show of redrawing the map in response to #75, as people weren't sure if a new (nearby) task had been loaded when the map didn't appear to change. We probably just need to implement a better way to visually indicate that the next task has been loaded without necessarily involving the map.

**Comment by mgcuthbert** [comment]
Oh interesting, I remember viewing that bug. I agree I think there needs to be some more specific indication of something happening, and some sort of transition that is clear but not jarring.
