### ISSUE TITLE
Additional information on file export comment

### ISSUE THREAD

**Issue by adiatmad** [osmlab/maproulette3#310]
Question: Could we get all information timestamps & non-commented tasks on file Export/Extract Comment? Thank you.

**Comment by mvexel** [comment]
Hi @adiatmad , sorry for the late response to this question.

Right now we export: 

* Task ID
* Challenge ID (probably redundant)
* Task Name
* Task Status
* Task Priority
* OSM Username (of person who changed status most recently)

If I understand you correctly, you would also like to see:

* Timestamp of last change to a task
* Number of comments on a task

Is this correct?

**Comment by adiatmad** [comment]
Hi @mvexel thank you for response and mark it as enhancement, no worry about late.
You are correct but I mean number of tasks without comment. I used to count total task everybody in my team.

**Comment by mvexel** [comment]
To get the number of tasks without comment, you could just count the rows that have 0 for the field that has the number of comments per task, right?

**Comment by adiatmad** [comment]
I definitely missed that, I see. Correct. Thank you for your explanation.
