### ISSUE TITLE
Updates to Task Admin list

### ISSUE THREAD

**Issue by mgcuthbert** [osmlab/maproulette3#315]
The task admin could benefit from a couple more pieces of information that may be useful to challenge owners at first glance. For any tasks that have had their status set (ie. not CREATED) should include a date column of when the status was last set, and a user column with the name of the user that last set the task status. It would also be useful to allow some sort of click drop down or something akin to that in the admin task list that will allow the user to see the comments that are associated with that specific task.

**Comment by mvexel** [comment]
The user column would be useful so people can derive the top users for their challenges. I wonder if we need to enable folks to opt out of that being shown though. Not sure yet

**Comment by mvexel** [comment]
I mean end users being able to opt out of having their usernames appear in those types of metrics, as is the case in the main leaderboard #254 .

I realize that this data could probably still be retrieved with API calls, or other creative ways.

**Comment by mvexel** [comment]
Agree on adding the timestamp and user column. Related to #310 where a user asked for this information, as well as the number of comments to a task, be included in the CSV export.
