### ISSUE TITLE
Challenge takes forever to load in admin screen

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#325]
I am trying to load http://maproulette.org/mr3/admin/project/45/challenge/85 but it takes forever and seems to hang my browser.

Not sure if there's something specific to this challenge configuration that causes that? It has a custom basemap.

**Comment by mvexel** [comment]
Perhaps it was partly a glitch, after clearing my browser it seems to load a little better now. But there is definitely something going on with the way this challenge is being loaded into the admin view. The initial map view is set to the south pole (or something close to it) while the actual tasks are all in Texas.

**Comment by mvexel** [comment]
The problem here seems to be that the map centers on Antarctica initially instead of on the task bounding box. Something corrupted with this challenge?

**Comment by nrotstan** [comment]
The challenge does load correctly, but it's using a custom basemap that doesn't show much outside of North America, and the challenge contains a few tasks with some odd locations that causes the weird repositioning of the map into an area that appears grey on the custom basemap. For example: `{"type":"Point","coordinates":[173.111777803834,-90]}` for task [89364](https://maproulette.org/challenge/85/task/89364)

Closing this issue.
