### ISSUE TITLE
Bulk change task status in Challenge admin

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#326]
When a user downloads a CSV of their challenge, would it be interesting to enable them to re-upload it after changes were made?

A potential use case would be that a user wanted to set all tasks marked too hard back to created. Currently there is no way to do that without going into the API. Perhaps there's a better way to approach this use case though. Ideas?

**Comment by mgcuthbert** [comment]
For that particular use case, maybe just allow user to select multiple tasks and then set the status for all selected tasks to "created" or some other value.

**Comment by mvexel** [comment]
That works too!

**Comment by nrotstan** [comment]
This requires the backend to begin allowing challenge owners to set task status to any desired status, rather than enforcing the usual progression rules. maproulette/maproulette2#427 will allow that.
