### ISSUE TITLE
Pre-filled source and comments field

### ISSUE THREAD

**Issue by mihaii-telenav** [osmlab/maproulette3#361]
Right now you can only add custom text only for the comment field when creating a challenge. Would be nice to have the option to add custom changeset comment and changeset source texts.

**Comment by mvexel** [comment]
JOSM remote control does [support](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#load_and_zoom) this using the `changeset_source` parameter of `load_and_zoom`. Let's add a field in the challenge creation screen.
