### ISSUE TITLE
Unable to Authenticate - Service provider responded in error: 301 (Moved Permanently)

### ISSUE THREAD

**Issue by osmCL** [osmlab/maproulette3#368]
I am unable to authenticate in MR2 and MR3. 

There is a 500 error with this message: 

> Oops! Something went wrong.
> 
> We will work on fixing that right away.
> Click on the Map button to start mapping again right away.
> Error: Internal Server Error: Communication with the service provider failed: Service provider responded in error: 301 (Moved Permanently) 
> 
> 

I guess it is HTTPS related. if I remember right there was an only HTTPS policy enforced a little while ago that caused problem with other OSM authenticated services.

**Comment by nrotstan** [comment]
This should now be resolved.
