### ISSUE TITLE
Add control to reset filters on admin view-challenge page

### ISSUE THREAD

**Issue by nrotstan** [osmlab/maproulette3#389]
Add a control to the admin View Challenge page that will reset the filters and map back to their original settings. This can be especially useful for the map: since it remembers the last place it was left, if it was left in a location with no tasks showing, it can be confusing when the challenge owner returns to that challenge at a later time and doesn't see any of their tasks listed even though all the statuses appear to be enabled.

**Comment by mvexel** [comment]
I think this is still useful, @nrotstan agreed?
