### ISSUE TITLE
Please include Level 0 as one of the editor options

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#423]
Kindly add support for the Level 0 Editor: http://level0.osmz.ru/i

Some tasks are quickly fixed using Level 0, compared to other editors.

See more: https://wiki.openstreetmap.org/wiki/Level0#Common_Tasks

**Comment by nrotstan** [comment]
Thanks for the suggestion, @govvin. Support will be included in the 3.0.7 release.
