### ISSUE TITLE
Can't log in: Communication with the service provider failed: PKIX path building failed

### ISSUE THREAD

**Issue by hfs** [osmlab/maproulette3#427]
* I go to http://maproulette.org, the greeter modal comes up, I click “Get Started”
* The start page is shown. I click “Sign in” in the top right corner
* I would expect to be taken to the OSM OAuth page. Instead an error message is displayed:

Communication with the service provider failed: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This seems to be a backend error, because I see in the network tab in the developer tools that the first request to `/auth/authenticate?redirect=/mr3/` directly results in a 308 redirect to `/mr3/error?errormsg=Communication+with+the+service+provider+failed…`.

This happens in Firefox 61.0 and Chromium 67.0.3396.87 on Linux.

Other OAuth clients work for me, e.g. http://umap.openstreetmap.fr/

**Comment by govvin** [comment]
I encounter the same issue since yesterday on: Chromium 66.0.3359.181 and Firefox 61.0

**Comment by MRVDH** [comment]
Same here

**Comment by mvexel** [comment]
I can reproduce this. Hang on while we look into it..Thanks for reporting!

**Comment by mgcuthbert** [comment]
This is resolved now. Please try again. If you see the same issue again, first try clearing your cookies and then logging in again. If it persists please reopen this bug so that we can look into it again.

**Comment by MRVDH** [comment]
I get a different error now.

1. I click 'sign in' (either on the comments section or top right corner)
2. It takes me to the OSM auth page where I then authorize access to my account.
3. It takes me back to the MapRoulette website with the Error message: "Please sign in to continue."

I cleared Cookies, Cache, Hard Reload, everything there is to clear. Using the latest Chrome version 67.0.3396.99 (Official Build) (64-bit)

**Comment by hfs** [comment]
http://maproulette.org/ works for me now, thanks!

The remaining problem can be discussed over at #313.
