### ISSUE TITLE
Failed to connect to maproulette.org port 80: Connection refused

### ISSUE THREAD

**Issue by tordans** [osmlab/maproulette3#432]
I get 

> $ curl http://maproulette.org/
> curl: (7) Failed to connect to maproulette.org port 80: Connection refused
> curl https://www.maproulette.org/
> curl: (7) Failed to connect to www.maproulette.org port 443: Connection refused

and cannot open the webpage.

**Comment by mvexel** [comment]
https doesn't work yet.
maproulette.org is (back) up
