### ISSUE TITLE
Project owner not given admin permission when new project created

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#433]
Case: http://maproulette.org/mr3/admin/project/2613/challenge/3056 

Challenge: Visible
Project: Visible
Not created in the past few hours

When searching for 'Durham' (part of title) -- not found.
When visiting challenge user endpoint http://maproulette.org/mr3/challenge/3056/ -- task is served

Why is the challenge not discoverable?

**Comment by nrotstan** [comment]
@mvexel the server reports the project (2613 - "tiger_cleanup" ) is not enabled/visible. Is it showing as visible in the admin ui?

**Comment by rivermont** [comment]
@nrotstan The Project is not visible, and changing it to so in the settings seems to have no effect. A spinning loader appears for a second but the project remains invisible.

**Comment by nrotstan** [comment]
Thanks, @rivermont. Just to confirm, you're clicking the "edit" link to the right of the project name on the lefthand sidebar, being taken to the edit form, switching Visible to "yes", and then clicking Save at the bottom of the form?

When you say the spinning loader appears for a second but the project remains invisible, are you referring to the spinner on the Save button when you click it? And does it just leave you on that form afterwards, or does it take you back to the project dashboard but the project is still not visible?

**Comment by mvexel** [comment]
Yes

**Comment by rivermont** [comment]
@nrotstan Mostly correct.
On the project page, I click that 'edit' link, change 'visible' to 'yes', and save. It then takes me back to the project page, where there's a spinner next to both 'Projects and Challenges' and 'TIGER cleanup' (project title). The little `item-visibility` svg is still 'disabled' and the visibility switch back in 'edit' is reset.
Hope this helps.

**Comment by nrotstan** [comment]
@rivermont I'm beginning to suspect this is a permission issue, even though you're the project owner. The server does a special check on the visibility setting to ensure the user is an admin of the project, and silently leaves that setting unmodified if not.

As an experiment, click on the Managers tab for that project, and then re-add yourself as a manager and give yourself the Admin role. It'll still look the same afterwards, showing you as an owner. Then refresh the page and try editing the project visibility again. I'm curious to know if that solves the problem.

**Comment by rivermont** [comment]
That solved it @nrotstan! The Managers list was empty, added myself as Admin and can make the project public. Thanks!

**Comment by nrotstan** [comment]
Awesome, glad to hear it! I'm going to rename this issue to reflect the real problem of you not receiving admin permission when you created the project, and will leave it open while I investigate why that occurred.

**Comment by mvexel** [comment]
@nrotstan did we resolve this?

**Comment by nrotstan** [comment]
I'm going to close this issue as it's been well over a year and I haven't been able to reproduce the problem nor have received any other reports of this happening. Please feel free to reopen if needed.

**Comment by kriswema** [comment]
I've just come across this bug. I created a new project and found myself unable to set it to visible, this issue gave me the idea to add myself as project admin, which allowed me to change project visibility.

**Comment by nrotstan** [comment]
Thanks, @kriswema , PR #1114 should address this.

**Comment by danielduhh** [comment]
@nrotstan I'm having trouble adding people to new projects I create, and am curious if #1114 will fix that.
Steps to reproduce.
1. Create project
2. Add yourself as admin (I beleive #1114 ) will fix this
3. Add someone else as admin
This produces the following message:

![Screen Shot 2020-02-18 at 3 24 20 PM](https://user-images.githubusercontent.com/1947857/74787008-f04be600-5262-11ea-9ec0-bc7ed646110d.png)

**Comment by nrotstan** [comment]
@danielduhh Yes, it should.
