### ISSUE TITLE
When showing individual tasks, filter challenge list to only show challenges that have visible tasks within viewport

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#434]
As a user, when zoomed in far enough on the map that the map view shows individual tasks, we should filter the challenge list to only show challenges that have visible tasks within viewport.

Additionally, the filters should work to further narrow down the visible tasks.

This will help users create more meaningful virtual challenges.

**Comment by mvexel** [comment]
The filtering already works, scrap that comment.

**Comment by nrotstan** [comment]
I believe this is fixed. Feel free to reopen if not.
