### ISSUE TITLE
Re-use open iD window / tab

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#439]
We are already re-using an existing open iD tab, so this is not about that.

Here is my use case: I have iD open with custom map overlay, because the Challenge requires that layer to be visible. Specifically, [this challenge](http://maproulette.org/mr3/challenge/3068) requires the TIGER roads overlay to be visible. However, when we reload the iD tab for the next task, the overlay disappears and I have to go back into the iD layers menu to re-add it to the visible layers.

@bhousel do you have any suggestions on how to enable this use case?

**Comment by bhousel** [comment]
Oh yeah adding custom raster overlays is something I need to add support for - I'm tracking it on https://github.com/openstreetmap/iD/issues/3773

**Comment by mvexel** [comment]
Once that is resolved we should enable this in MapRoulette. Perhaps we can use the Editor Layer Index to populate a list we can serve in the Challenge create screen.
