### ISSUE TITLE
Add metric for 'most popular'  / 'most active' in Challenge list

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#447]
When thinking about sorting challenges #211 the concept of 'most active' challenges suddenly made new sense to me. We could use this in various ways / places but the challenge list would be a great start. That requires us to think about what constitutes 'most popular' or 'most active' In its simplest form it could be '% of total tasks that changed status in the past X days'.

**Comment by nrotstan** [comment]
Backend PR maproulette/maproulette2#457 adds server-side support for this.

**Comment by nrotstan** [comment]
We don't show popularity for each challenge yet, but it is now possible to sort challenges by popularity in search results.
