### ISSUE TITLE
Add an option to load only the OSM object rather than all data within the viewport

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#452]
For some select challenges, the Task may refer to a large object, like a long OSM way or a relation.
In such cases, when using JOSM, the bbox may be too large for the API to load, resulting in a 
bad request' error in JOSM. 

For such cases, we should include a toggle in the challenge creation to load only the OSM object rather than all map data within view. 

For an example see http://maproulette.org/mr3/challenge/373/task/373224

**Comment by mvexel** [comment]
As mentioned in #577 (which I opened as a duplicate) it may be better to have this as a sticky option at the task level that the user can set rather than a challenge option. Discuss?

**Comment by nrotstan** [comment]
PR #559 just adds it as another editing option when completing tasks (alongside opening in a new layer, etc).

But I agree about the stickiness, and I think it might make sense at this point to break out the editing options into their own separate control. If the user has a default editor set in their user preferences, we'd default to that editor option, but -- unlike today -- it could be changed when completing a task and we could subsequently stick to the user's most recent choice as they work through that challenge.
