### ISSUE TITLE
Browse challenges on map

### ISSUE THREAD

**Issue by cascafico** [osmlab/maproulette3#462]
I know that for the gamification sake only random challenges should me displayed, but sometimes could be useful to take advantage of local knowledge.
Are planned other challange pick criteria?

**Comment by nrotstan** [comment]
Hi @cascafico thanks for the question. if you click the "Location" filter at the top and choose "Intersecting Map Bounds" and then zoom in far enough on an area in the map, you will see local challenges in that area. If you want to further restrict it to challenges fully contained within the visible map (not just intersecting it), you can switch to "Within Map Bounds".

You can then click on a marker on the map to see what challenge it is.

<img width="911" alt="intersecting_map_bounds" src="https://user-images.githubusercontent.com/445970/45224931-17317a80-b270-11e8-89c0-4a21319c48f3.png">

<img width="378" alt="challenge_marker" src="https://user-images.githubusercontent.com/445970/45225109-9921a380-b270-11e8-8358-9fd6724433b8.png">
