### ISSUE TITLE
User settings show empty options

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#465]
Unable to change settings because user settings show nothing. I'm using Firefox 61.0.1

![image](https://user-images.githubusercontent.com/5821688/45250060-2ee72c80-b35e-11e8-997e-7e8637ee54d1.png)

**Comment by govvin** [comment]
This issue was encountered on Firefox 62, but works fine in Chromium. 

In Firefox, if you hit the tab button to navigate by keyboard to the option for default user settings, the options will appear.

![image](https://user-images.githubusercontent.com/5821688/45333385-7f51ca80-b5a8-11e8-899e-50066ba8116b.png)

**Comment by nrotstan** [comment]
Thanks for the report, @govvin. I haven't been able to reproduce this on Firefox for Mac 61.0.1, 61.02, or 62.0, but it sounds like you're on Linux, correct?

**Comment by govvin** [comment]
Yes, on Linux.

**Comment by mvexel** [comment]
Is this related to / the same as #437 ?

**Comment by nrotstan** [comment]
The missing user settings should now be fixed, but please do reopen if you experience problems again. Thanks again for reporting.
