### ISSUE TITLE
Importing OSM files for tasks

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/maproulette3#476]
I'm looking for a tool to help the OSM community work together on imports, and I'm not sure if Map Roulette can help with that.

Typically we'd create a bunch of OSM XML files, where each of those would be a task within a challange. Users could choose to import our OSM XML file into JOSM via the [import command](https://wiki.openstreetmap.org/wiki/JOSM/RemoteControl#import_command) as part of the RemoteControl, review and task comments, and either import, correct and import, or reject it.

Can Map Roulette do this? It seems like it has all the infrastructure already for users to see what open tasks there are and keep track of challenge progress, but it looks like it's missing the ability to pass an OSM XML file per task, even if we converted it to GeoJSON, we still want that geometry to be opened in JOSM for the user to work on the talk...

**Comment by mvexel** [comment]
Hi Andrew. 

What I think you are looking for is for one MR task to comprise multiple OSM objects. MR is designed as a micro-tasking tool and as such would only deal with 1 or 2 OSM objects at a time. If you're looking for validation of larger groups of objects to be imported in OSM, you may be better off using Tasking Manager or something similar.

But perhaps I am misunderstanding your intent.

Something that may help is the Suggested Fixes (#367) we are currently implementing. This would enable the following workflow:

1. The user is presented with a suggested change in OSM
2. If the change looks good, the user validates and OSM is immediately updated (no roundtrip to JOSM or iD needed)
3. If the user rejects the change, nothing happens and the next suggested fix is served up.

This workflow would allow for rapid validation of new features for a human-curated import, among many other things. The first iteration would only allow for tag changes, not new / changed geometries, but that is in the pipeline as well.

Does this help you at all?

**Comment by andrewharvey** [comment]
Each task would be one real world feature, it could just be one OSM object or it could be a few.

The use case I'm working on is a government department which manages assets is looking help provide their as constructed GIS data for newly constructed assets to help the OSM community get these into OSM. They would publish geometry + osm tags as a OSM XML file. The community can then review this with any local knowledge, correct any tagging issues as well as merging with any existing data in OSM.

I was hoping that MR could provide the infrastructure to manage this collection of tasks and keep track of the community progressing through these tasks.

It does sound like the Suggested Fixes feature would help this use case, however instead of it being a tag change for an existing OSM object, it would be a whole new feature and merging with any existing data is left to the mapper in their editor.

**Comment by mvexel** [comment]
I understand, thanks for explaining more @andrewharvey. I think we are a little ways out on supporting adding new geometries directly through MapRoulette. So the short answer is no 😢 

Theoretically we could use the [`add_way`](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#add_way) / [`add_node`](https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#add_node) functionality of the JOSM remote control. I don't know if iD supports adding objects through the query string (I suspect not).

My take on this is it could be implemented in MapRoulette, but I would rather hold off and make sure this use case is covered by Suggested Fixes eventually. Sorry I can't be of any more immediate help here!
