### ISSUE TITLE
In task browse mode, only show challenges in list that have visible tasks

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#478]
In task browse mode (zoomed in), the challenge list should only show challenges that have tasks currently shown on the map.

This has UX implications @ryanscherler , because it 'overrides' filter settings, or rather, adds an invisible filter. Needs some thought in that regard.

**Comment by ryanscherler** [comment]
Ok sounds good - I'll talk with @nicolescherler and @nrotstan to see how we can better clarify the filter being applied.

**Comment by nrotstan** [comment]
This is now the behavior as of v3.5
