### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by Synesso** [osmlab/maproulette3#479]
Attempting to sign in via OAuth with my OSM account results in a modal box:

```
ERROR
Please sign in to continue
```

I've disabled all ad blockers, but the error continues.

I remember I saw this a month or two ago and gave up. Now I'm trying again and the problem still exists.

Network console shows `401 Unathorized` on http://maproulette.org/api/v2/user/whoami
Javascript console shows 
```
Server.js:44 GET http://maproulette.org/api/v2/user/2830 401 (Unauthorized)
Server.js:44 GET http://maproulette.org/api/v2/user/whoami 401 (Unauthorized)
Server.js:151 Uncaught (in promise) Error: Unauthorized
```

Chrome Version 69.0.3497.100 (Official Build) (64-bit) on OS/X Mojave.

**Comment by nrotstan** [comment]
Hi @Synesso, thanks for the report. This is a bug we have for `www`. Can you try just maproulette.org (no `www` in front) and see if that solves the issue? Thanks again.

**Comment by Synesso** [comment]
Thanks. Yes, that works (http only, https is not available).  I expected a prior issue, but didn't find it. Sorry about that.
