### ISSUE TITLE
Give challenge authors the option to open task with metadata popup visible

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#517]
In some challenges the salient information is in the metadata of the geometry. Like in https://maproulette.org/mr3/challenge/3031. We should give the challenge author the option to have tasks loaded with the popup visible.

Now that we have #456 this is not as critical but still some challenge owners may prefer this as it is more directly visible to the user.

**Comment by nrotstan** [comment]
We don't support a way to force the task properties open, but we do offer a Task Properties widget now for mappers.
