### ISSUE TITLE
Get users to map more AKA stickiness 

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#520]
I think there is some low and higher hanging fruit to get mappers AND challenge owners to be more engaged with MapRoulette and fix more things in OSM :) 

I created a tag [stickiness](https://github.com/osmlab/maproulette3/issues?q=is%3Aissue+is%3Aopen+label%3Astickiness) to flag existing issues that could contribute to this.

Some other ideas (can break out into separate tickets):

* Give challenge owners more feedback on how mappers interact with their challenges
* Collect users email addresses (needs great caution to not spam people and has potential GDPR impact) so we can inform people of new / interesting / popular challenges, send newsletters, etc
* Dashboard / landing page (@nrotstan you mentioned there is already a ticket for this?)
* Highlight 'popular' challenges more
* Do a better job suggesting something (else) to work on

**Comment by nrotstan** [comment]
I was thinking of ticket #438 which I've been interpreting as separating the user settings from the other info (favorite challenges, saved tasks, etc.) and moving the latter to a dashboard / landing page for logged-in users. Then adding more to that dashboard, like you mention (featured, popular, and new challenges; tasks the user has commented on; etc). I'm not seeing a specific ticket for a dashboard, though, so I'll add one.

**Comment by mvexel** [comment]
Most of this we have in the mean time. There's still #762 to resolve if we want to give the challenge owner more feedback about timing of tasks. Emails we collect. Dashboard we have. Popular challenges are highlighted. Suggesting something else to work on is something we could still think about, but I think we have enough for now to satisfy the purpose of this ticket, so I'm going to close this
