### ISSUE TITLE
Set Completed challenges to invisible automatically

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#524]
When there are no remaining tasks in a Challenge, set that challenge to invisible automatically.

This was the behavior in MapRoulette 1 and also 2, I believe.

**Comment by nrotstan** [comment]
While we still don't change the visibility, I believe PR maproulette/maproulette2#633 will help keep these challenges out of search results. It's been included in backend release 3.6.7, but not yet deployed to maproulette.org
