### ISSUE TITLE
Make 'tasks from' in challenge detail and 'modified' in admin show the same thing

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#525]
'Modified' in challenge admin seems to show the last time any task was touched in the challenge.
It would be better if it showed when the tasks were last updated (and let the label also reflect this)

<img width="395" alt="screenshot 2018-11-07 15 57 01" src="https://user-images.githubusercontent.com/120452/48166460-dc66b580-e2a5-11e8-90e2-5976f656fe99.png">
<img width="418" alt="screenshot 2018-11-07 15 56 55" src="https://user-images.githubusercontent.com/120452/48166462-dcff4c00-e2a5-11e8-9e14-21c2947b0357.png">

**Comment by nrotstan** [comment]
v3.1.1 Added a "Tasks Refreshed" field to the challenge admin that is consistent with the "Tasks From" end-user field seen when browsing a challenge.
<img width="366" alt="tasks_refreshed" src="https://user-images.githubusercontent.com/445970/49315028-29067080-f4a1-11e8-9b71-1479e34210c4.png">
