### ISSUE TITLE
Multiple trash cans UI confusing

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#529]
There is a red trash for...removing something from UI (unclear) and a grey one for deleting the challenge, right next to each other. Issues with this:

1) deleting a challenge is more 'dangerous' and should have a red trash can
2) it should be clear (different / smaller icons) that the bottom row of icons is for tweaking the challenge admin UI.

<img width="388" alt="screenshot 2018-11-08 12 45 31" src="https://user-images.githubusercontent.com/120452/48223563-93ba0580-e354-11e8-880e-9d4d52805175.png">

**Comment by nrotstan** [comment]
Yeah, I can see how that'd be confusing. The lower trashcan is for removing a dashboard configuration (you can setup multiple configurations of a dashboard with various widgets and filters -- e.g. one just for metrics and another for management).
