### ISSUE TITLE
Public challenge / project based leaderboard

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#536]
I think we have all the components for this already so I hope this would be somewhat straightforward.

How about if a challenge or project owner wants to share their leaderboard publicly. A use case would be if the challenge / project owner is running a mapathon or contest of some sort. All participants can then track their performance on this leaderboard.

The admin interface already has a leaderboard that is visible only to the project / challenge administrators.

What I propose is to create a separate public (if enabled) page to this leaderboard info. So if you have https://maproulette.org/mr3/admin/project/PROJECT_ID your leaderboard would sit at https://maproulette.org/mr3/project/PROJECT_ID/leaderboard or something like that .

Am I oversimplifying ? 🌭

**Comment by mvexel** [comment]
Great.

We're not doing this for Projects yet, are we?

Since we do not really have public 'project' pages this would need some thinking, but I'd like to do that thinking :) 

Use case is multiple challenges that are around the same topic or city in one Project. In that case the Project owner would want to expose a leaderboard for that.

One possible place to link to it is here: 

![image](https://user-images.githubusercontent.com/120452/48372632-6afb7e00-e67c-11e8-844d-2c68481b9101.png)

**Comment by nrotstan** [comment]
Sure, are you thinking it'd be the leading contributors overall for the project (like what's currently available in the admin), or showing the individual challenge leaderboards for the project's challenges on one page, or a combination of the two?

**Comment by mvexel** [comment]
just aggregate for the entire project, as is shown in the admin page currently.
