### ISSUE TITLE
Email collection

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#544]
Let's collect email addresses on a strict opt-in basis.

## Types of email we'd send
* MapRoulette news (release notes / newsletter) -- Manual
* Notifications -- Automatic (later)
  * Tracked task changed / commented on
  * Tracked challenge completed
  * Challenge owner: challenge completed, new comments
  * Weekly metrics email (both challenge owners and mappers)

## Implementation

* For first time auth: post auth dialog asking people for valid email (ensure UI is clear about opt-in)
* Email confirmation flow
* Show dialog to existing users who haven't seen the dialog before
* Opt in / out in user profile
* Delete user account in user profile
* Way to send automatic emails (later)

**Comment by nrotstan** [comment]
UI/UX: We need to add email form fields and subscription-management controls to the user profile page. We also need to design the modal presented after initial signup via OpenStreetMap oauth, as well as a one-time modal we might present to existing users to let them know they can now provide their email address and optionally receive email notifications.

**Comment by nrotstan** [comment]
Included in v3.3
