### ISSUE TITLE
Support scheduled rebuilds of challenge task data

### ISSUE THREAD

**Issue by nrotstan** [osmlab/maproulette3#546]
Allow challenges using remote GeoJSON or Overpass sources to be automatically rebuilt on a scheduled basis, including pertinent settings (such as whether to remove unmatched tasks on rebuild).

Based on discussion from #430

**Comment by nrotstan** [comment]
Closing due to age.

**Comment by Noki** [comment]
Please reopen this one. It is still a big issue. My update scheduler that uses the API broke with some software updates and currently I don't have the time to fix it, but I'm getting complains from users about outdated challenges.

**Comment by mvexel** [comment]
I would consider it an enhancement rather than an issue. We're considering a similar enhancement now in #1910 .
