### ISSUE TITLE
horizontal access reversed on tasks remaining chart

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#548]
I don't know exactly how this happened but I created a new dashboard view for my project focusing on just metrics and now the Tasks Remaining chart has the X axis reversed..

<img width="462" alt="screenshot 2018-11-15 12 50 21" src="https://user-images.githubusercontent.com/120452/48577778-3e8e6e80-e8d5-11e8-8b9a-1202003ca36a.png">

Entire dashboard:

<img width="1463" alt="dashbaord-messed-up" src="https://user-images.githubusercontent.com/120452/48577958-b0ff4e80-e8d5-11e8-99de-596623a3744a.png">

**Comment by nrotstan** [comment]
I believe PR #1076 will address this
