### ISSUE TITLE
Cannot reuse  name for a deleted challenge

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#550]
If I delete a challenge, I expect the name to become available again for re-use for a new challenge. This is currently not the case.

**Comment by nrotstan** [comment]
Deleting a challenge can be a time-consuming operation, so when a challenge is "deleted" it's simply marked for deletion and isn't actually removed from the system until later. This also makes undo possible, though I don't believe we're offering that in the front-end currently.

Perhaps showing deleted challenges with an undo option would at least make it clearer to challenge owners that the challenge is still around in some form (until it is ultimately removed), and thus the name is unavailable.

We could also offer a  "delete permanently immediately" control if the challenge owner really wants to remove the challenge and reuse the name. That'd potentially involve waiting for a few minutes while the challenge is removed (which is one of the reasons we moved to the asynchronous deletes -- see #108).

**Comment by mvexel** [comment]
Gotcha. I don't think it's common enough of a use case to do much about it at the moment. 
The undo option is interesting but I also don't see it as a high priority.
