### ISSUE TITLE
Challenge creation fails

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#551]
Trying to create a challenge with attached GeoJSON. Getting the following. 

<img width="510" alt="screenshot 2018-11-17 14 52 19" src="https://user-images.githubusercontent.com/120452/48666115-8f8a9800-ea78-11e8-8151-b198133cced1.png">

[maproulette_stops.geojson.zip](https://github.com/osmlab/maproulette3/files/2592288/maproulette_stops.geojson.zip)

**Comment by nrotstan** [comment]
The error messaging needs to be improved, but the underlying issue seems to be a few features with null geometries. E.g.
```json
{
	"type": "Feature",
	"properties": {
		"id": "198326",
		"StopName": "RIVERSIDE RD @ 3514 S",
		"City": "SOUTH SALT LAKE",
		"Lon": 1,
		"Lat": 1,
		"County": "SALT LAKE",
		"Update_": "8/28/2018"
	},
	"geometry": null
}
```

Looks like that stop actually appears twice consecutively in the file, and there is also another stop `900 W @ 3514 S` that also has null geometry that I see.

**Comment by mvexel** [comment]
Boo. I didn't expect this, since it was official government (agency) data and I expected it to curate their data properly.

So what remains doing is create a better error message indicating that some row could not be parsed because of invalid geom.

**Comment by mgcuthbert** [comment]
We could also ignore any features with null geometry, although if we did something like that we would either have to implement a stronger result message from the creation process in general, or accept some silent failures that a user probably wouldn't know about.

**Comment by mvexel** [comment]
A null feature is [technically valid](https://tools.ietf.org/html/rfc7946#section-3.2) so we should handle them gracefully. Since a null feature indicates that the Feature is unlocated, we should probably ignore it, since we depend upon the Task having at least a defined location.

**Comment by nrotstan** [comment]
PR maproulette/maproulette2#479 will cause features with null geometry to be skipped during task creation. No warning or notification of skipped tasks is presented to the user, which isn't ideal, but it will at least allow challenges to be successfully created from data containing an occasional null geometry.
