### ISSUE TITLE
Changing status of multiple tasks does not work

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#555]
When I use the checkmark to select all tasks in the current list and use the dropdown to change their status to 'deleted' nothing happens.

<img width="527" alt="screenshot 2018-11-20 14 43 09" src="https://user-images.githubusercontent.com/120452/48804734-ad533980-ecd2-11e8-8605-02cdf47365c5.png">

**Comment by nrotstan** [comment]
That is actually for selecting tasks that are already in a specific status (Deleted in this case) or have a specific priority. The only bulk status change we currently support is resetting back to Created status, which is done with a separate control. We could certainly enhance that to allow to setting to additional statuses.

<img width="920" alt="reset" src="https://user-images.githubusercontent.com/445970/48805171-86453980-eccb-11e8-92bd-b774b00dea82.png">

**Comment by nrotstan** [comment]
We now support bulk changes to nearly every status.
