### ISSUE TITLE
Global metrics view

### ISSUE THREAD

**Issue by giblet22** [osmlab/maproulette3#560]
In MR2 there was https://maproulette.org/ui/metrics where metrics across all projects and challenges could be seen publicly. Something similar would be useful to have in MR3.

![image](https://user-images.githubusercontent.com/7945333/49389058-6cf0b400-f6f3-11e8-80f3-f5d7ea2a803a.png)

**Comment by mvexel** [comment]
That metrics view is still current, since MapRoulette still uses the MapRoulette 2 codebase for the back end. So you can use that for now. But I agree, it would be good to carry over.

**Comment by mvexel** [comment]
Since nobody has asked about this sice, I am closing this as stale. @giblet22 Feel free to re-open if this is something you feel strongly about and we can discuss.
