### ISSUE TITLE
Mapillary integration

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#563]
This needs to be broken down further, but capturing ideas here after discussing with @cbeddow.

1) The Mapillary API call for detections outputs JSON that has a `url_mly` pointing to the Mapillary web site at that image location, and a `url_raw` pointing directly to the raw image URL. We could detect the presence of these keys and offer Mapillary integration accordingly. See [this task](https://maproulette.org/mr3/challenge/3226/task/5842325) as an example having these keys.
2) A next level of integration could consist of simply allowing challenge creators to say "here's the area I am interested in, and here's the class of detections I am interested in, create a Challenge based on what Mapillary has in this area. @cbeddow had a demo showing a all images pointing to a certain detected object, which we could use in some form.
3) We can allow challenge creators to set a flag 'only include tasks that have imagery' which would result in challenge post-processing, querying the Mapillary API for all task locations and flagging the ones that don't have imagery (yet) as 'too hard' or some new status, or simply ignoring them. We can also return the locations of tasks without imagery to the challenge creator so they can incentivize people to cover these locations with Mapillary.

**Comment by cbeddow** [comment]
We now have point features available in the API also:

a.mapillary.com/v3/map_features?client_id=<client>&bbox=<lng1,lat1,lng2,lat2>&values=<value>

Particularly useful for trash bins, crosswalks, benches... full list here: https://www.mapillary.com/developer/api-documentation/#points

If this is interesting we could pursue it, but seems to me the actual addition of points would have to happen through iD still? in detections and point feature cases?
