### ISSUE TITLE
Elements in task view sidebar

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#571]
Currently we have the following items in the sidebar when viewing a task:

* Challenge Info
  * Challenge name
  * Parent project
  * Contact owner
* Task Instructions
* Comments
  * Existing comments
  * Add comment
* Actions
  * Edit
  * Not an Issue
  * Skip
* More Options
  * Track / Untrack task
  * Load tasks randomly / by proximity switch
  * Keyboard Shortcuts
  * Management options (if you're the owner)
    * Review
    * Modify 
* Location
  * Map
  * Minimap
  * Reverse geocode
  * Lon/Lat + copy to clipboard
* Challenge Progresss
* Social sharing

This ticket is to capture the following as we're working towards a more configurable / modular layout

* What more / other information or actions do users care about when in task view?
* How should items be grouped?
* What is a sensible default layout?

**Comment by nrotstan** [comment]
Here are a couple more items:
* Current task status
* OSM changeset associated with (completed) task, if available

Right now we only show those to end users if the task has been previously marked with some kind of status. We always show them to challenge owners when reviewing tasks in their challenge.

**Comment by nrotstan** [comment]
Closing this as complete. Additional ideas can be submitted as individual issues going forward.
