### ISSUE TITLE
Deleted challenge still appears in projects view

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#574]
I recently deleted https://maproulette.org/mr3/admin/project/8/challenge/3375 but it still appears in my project view. When I click on it I get a message that the challenge does not exist.

![image](https://user-images.githubusercontent.com/120452/49887410-7a93f100-fdf9-11e8-98fe-538f5b9802b1.png)

**Comment by nrotstan** [comment]
I believe this has been fixed. Please reopen if you experience it again.
