### ISSUE TITLE
Change keyboard shortcut for Level0 editor

### ISSUE THREAD

**Issue by nrotstan** [osmlab/maproulette3#578]
The current keyboard shortcut for editing a task with the Level0 editor is `l` (lowercase L), but that is also the keyboard shortcut for navigating to the next task (presumably inspired by the vi keys :neckbeard: ) when the current task already has an existing status or is being reviewed by the challenge owner. Both of these can be available simultaneously in some situations and conflict.

> See [wiki](https://github.com/osmlab/maproulette3/wiki/Keyboard-Shortcuts-for-Task-Completion) for a full list of keyboard shortcuts available during task completion

I propose changing the Level0 shortcut (versus the next-task shortcut) for two reasons:
1. The Level0 shortcut is the newer addition
2. next-task is part of a set of related shortcuts -- including previous-task -- all based on the vi keys, and changing it would break that consistency

I propose we change the Level0 shortcut to `v`

**Comment by govvin** [comment]
Hi @nrotstan . I have no objections to changing the keyboard shortcut.  And, TBH, I didn't even know there's one. :grin:
