### ISSUE TITLE
[feature request] MR mobile interface for selecting challenges and tasks

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#585]
Vespucci v12 scheduled for release on Q1 2019 (and beta 3 already supports working on MR tasks), it would be nice to have a better interface where a contributor would like to find challenges/tasks they'd like to work on from the MR website.

Currently, the interface is not optimal, and leaves plenty of room for improvement. 

Here's how the task view looks like:
![image](https://user-images.githubusercontent.com/5821688/50433847-b197f580-0915-11e9-843e-443436cb1392.png)

All buttons appear functional (and sparse), except for missing editing button - and on mobile, it would be nice to find mobile-friendly editors listed: Level 0 and (soon) Vespucci.

**Comment by govvin** [comment]
Would it be possible to add `geo: URIs` as an edit link? This will allow mobile editors (Vespucci, Osmand, etc) to edit supported features, and support the MapRoulette workflow.

# Examples of how geo: URI may be used
----
## OSM website - sharing locations using geo: URI 
The geo: URI can be used to edit an area using a editing app in your mobile device.

 ![image](https://user-images.githubusercontent.com/5821688/50871105-89b88f80-13f5-11e9-8f0a-d83f835f5c4b.png)

----
## OsmAnd location sharing - can be used to launch other mapping apps, but especially useful when editing with a supported mobile OSM editor
![image](https://user-images.githubusercontent.com/5821688/50871248-09def500-13f6-11e9-90fd-2e8bd940ba24.png)

**Comment by nrotstan** [comment]
Thanks, @govvin, I think this would be desirable. The mobile support is very experimental right now (and not really functional for editing tasks, as you mention).

**Comment by mvexel** [comment]
..but it's being worked on at the moment. @govvin if you have any other feedback on mobile UX let us know. thanks.

**Comment by mvexel** [comment]
Let's collect further feedback and ideas for mobile support in #856 . I'll carry over the `geo:` scheme suggestion to there. Thanks for the suggestion!
