### ISSUE TITLE
allow map wrapping

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/maproulette3#593]
https://github.com/osmlab/maproulette3/blob/6d44d5f538520c237aeab7211c00e2ae4bae5ef2/src/components/EnhancedMap/EnhancedMap.js#L185-L186

This line makes viewing maps around the 180deg longitude line very stressful as the map keeps pushing back when you try to pan across the line.

Is there a reason for this?

Would worldCopyJump suffice instead?

> worldCopyJump | Boolean | false | With this option enabled, the map tracks when you pan to another "copy" of the world and seamlessly jumps to the original one so that all overlays like markers and vector layers are still visible.

**Comment by nrotstan** [comment]
That looks like a good suggestion, @andrewharvey, thank you.
