### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by losuler** [osmlab/maproulette3#599]
**Describe the bug**
Attempting to sign in displays the following error message.

```
Communication with the service provider failed: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**To Reproduce**
1. Navigate to `https://maproulette.org/mr3`.
2. Click the `Sign in` button at the top right.
3. Error message appears.

**Troubleshooting**
Error still appears after clearing cache/cookies and on other browsers (Firefox, Chromium).

**Comment by nrotstan** [comment]
Thanks, @losuler, this should be fixed now.

**Comment by crossaction** [comment]
The problem still persist.

**Comment by nrotstan** [comment]
Thanks for the report, @crossaction, this should be resolved now.

**Comment by typicalTYLER** [comment]
Seems to be happening again.

**Comment by nrotstan** [comment]
Thank you, @typicalTYLER, it's now fixed.
