### ISSUE TITLE
Add donation button

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#607]
I set up a Liberapay account to accept donations to offset server costs: https://liberapay.com/MapRoulette/

Let's add a button in the top bar and / or on the homepage to enable this.

Additionally and optionally let's add a user profile checkbox 'I have donated' to hide the button.

**Comment by raphaelpe** [comment]
I fully agree with this donation button to keep the maproulette site servers in the air

**Comment by raphaelpe** [comment]
Tip for Donation Button in Version v3.2.4! 

Put the button for donation in this new version v3.2.4?
