### ISSUE TITLE
When filtering Projects by name, Challenges and Managers tabs are not visible

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#622]
When viewing the projects list at https://maproulette.org/mr3/admin/projects, the project cards have three tabs: Challenges, Details and Managers.

<img width="425" alt="screenshot 2019-02-06 10 29 17" src="https://user-images.githubusercontent.com/120452/52360806-19a02800-29fa-11e9-91e2-994540dca313.png">

However, when you filter by name, these columns disappear.

<img width="841" alt="screenshot 2019-02-06 10 30 13" src="https://user-images.githubusercontent.com/120452/52366821-e369a500-2a07-11e9-900b-431c96f51c2c.png">

I suspect this is because the filter is supposed to work on both Projects and Challenges at the same time, but as a Super Admin 🚀  I would like to be able to drill down to just projects I'm interested in and see who the admins are.

**Comment by nrotstan** [comment]
Tabs on the project card have been removed in PR #653 as they were proving to be too confusing. Cards will now just show the list of challenges in the project and those will be filtered as expected when performing a search.
