### ISSUE TITLE
Getting error "Unable to save your changes" in ongoing Challenge (and list of finished challenges)

### ISSUE THREAD

**Issue by sfkeller** [osmlab/maproulette3#625]
When starting ongoing challenge "Missing Crosswalks of Vaud (Switzerland)" https://maproulette.org/mr3/browse/challenges/1434 an error occurs "Unable to save your changes".

In addition, "Missing Crosswalks of Southern Switzerland" seems to be vanished:
Is threre a view or a way to see finished challenges (at least as owner - Samuel Kurath in this case)?

**Comment by nrotstan** [comment]
Thank you reporting the "Unable to save your changes" error, @sfkeller. I am able to reproduce it and will investigate.

For "Missing Crosswalks of Southern Switzerland", what search are you trying? `Missing Crosswalks`, `Southern Switzerland`, and `Vaud` all worked for me. The challenge is here: https://maproulette.org/mr3/browse/challenges/1434

**Comment by sfkeller** [comment]
> The challenge is here: https://maproulette.org/mr3/browse/challenges/1434

That was the challenge I found and mentioned above already. I referred to "Missing Crosswalks of Southern Switzerland" and about 6 other challenges I and Samuel submitted months ago. I opened #626 for that.

**Comment by nrotstan** [comment]
The "Unable to save your changes" error will be addressed by maproulette/maproulette2#496

**Comment by sfkeller** [comment]
Thanks!
