### ISSUE TITLE
When one challenge was "Saved", search of challenges only shows this one

### ISSUE THREAD

**Issue by sfkeller** [osmlab/maproulette3#626]
How to access finished Challenges?
@nrotstan wrote
> For "Missing Crosswalks of Southern Switzerland", what search are you trying? Missing 
> Crosswalks, Southern Switzerland, and Vaud all worked for me. The challenge is here: 
> https://maproulette.org/mr3/browse/challenges/1434

Months ago Samuel (and I) submitted several Challenges about missing crosswalks in Switzerland, from which currently only the one mentioned above is still running and accessible.

What happened to the others? Can't find any more:

![grafik](https://user-images.githubusercontent.com/43340/52431795-3bd49b80-2b09-11e9-9bb9-30382a656dc1.png)

Is there any statistics available?

**Comment by nrotstan** [comment]
Hi @sfkeller, I am seeing a whole bunch of them (18 or so). Is it possible you have a search filter on that is excluding results? If not, are there specific examples that you're looking for?

<img width="1027" alt="crosswalks" src="https://user-images.githubusercontent.com/445970/52433479-05bff900-2ac2-11e9-9e08-43893dac17d6.png">

**Comment by nrotstan** [comment]
Also, to specifically answer the question about finished challenges, they will always appear in the "Create & Manage" area for the challenge owner.

**Comment by sfkeller** [comment]
I think I found the problem: 
I "saved" one challenge, specifically 1434 (having title "...crosswalks..."). 
Now search of challenges, like this https://maproulette.org/mr3/browse/challenges?query=crosswalk only shows this saved one, not the others.
This happens even when logged out.

**Comment by nrotstan** [comment]
Closing this due to age. Feel free to reopen if it's still an issue.
