### ISSUE TITLE
CAPTCHA widget that uses maproulette 

### ISSUE THREAD

**Issue by arthurlogilab** [osmlab/maproulette3#642]
CAPTCHAs are "completely automated public Turing test to tell computers and humans apart" commonly used on websites to make sure the submission of content is being done by a human and not a robot (and sometime even just to access content). The main implementation right now is Google's ReCAPTCHA which can be viewed as "working for free for Google" which a growing number of people are having problems with. 

It would *awesome* to have a captcha technology that improves the commons instead of improving a company. 

A paper by Stefan Keller talks about ReMAPTCHA for this problem https://wiki.hsr.ch/StefanKeller/wiki.cgi?ReMAPTCHA but the code is unavailable. Maproulette seems similar in certain ways. 

Would it be possible to adapt maproulette for this kind of use ? 

* having an "anonymous" usage (no need for registration) 
* providing a iframe/js widget to do this task
* probably have a way to put changes in an "incoming" queue that is checked by OSM contributors

By the way kudos for the excellent work on maproulette :heart:

**Comment by nrotstan** [comment]
Hi @arthurlogilab, I haven't had a chance to read the paper yet, but off the top of my head you might be interested in #367 (suggested fixes), which seem like they'd be more friendly to a captcha-style workflow

**Comment by mvexel** [comment]
This will become more attainable once we have #367 in place. 
Still many things to figure out, for example:

* How to allow 'anonymous' actions in MapRoulette
* The scope of such actions
* How do we know what the 'right' answer is?

**Comment by nrotstan** [comment]
Closing this due to age.
