### ISSUE TITLE
Show place in leaderboard with points in top bar?

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#667]
Cool that you can see the points -- cooler perhaps if you could see your place in the leaderboard, or even how many more points you need to overtake the next person up.

**Comment by raphaelpe** [comment]
very good this option with the direct points at the top of the site! This update was great!

**Comment by JLZIMMERMANN** [comment]
Maybe it would be good to see in a dataviz way, not only a vertical displaying.

**Comment by JLZIMMERMANN** [comment]
Another thing is that it would be great to be able to find leaderboard of several challenges directly from Leaderboard link at the top and not only a general leaderboard.

**Comment by raphaelpe** [comment]
but the leaderboard is well organized now, with the option to search by country, I'm enjoying the update!

**Comment by raphaelpe** [comment]
the removal of the administrative area from the top of the site was also very good! left the site more organized!

**Comment by JLZIMMERMANN** [comment]
If I select a challenge it doesn't appears, I need to scroll down a lot to find th echallenge I chose and then find 
![image](https://user-images.githubusercontent.com/4929752/53915068-788ba800-405f-11e9-9a19-2dfdf349ce22.png)

**Comment by nrotstan** [comment]
Thanks for the bug report, @JLZIMMERMANN, I've opened a new issue #668 to track it.

**Comment by nrotstan** [comment]
Closing this due to age. Note that all leaderboards show your standing for that particular leaderboard.
