### ISSUE TITLE
adjust widgets in dashboard

### ISSUE THREAD

**Issue by JLZIMMERMANN** [osmlab/maproulette3#669]
I tried a 3 columns in my layout and it's displayed without optimzation
![image](https://user-images.githubusercontent.com/4929752/53916823-6f043f00-4063-11e9-9cd7-ab30dfb760ba.png)

**Comment by mvexel** [comment]
The widgets are designed to need a certain minimum amount of space.. Some of them could be optimized further (perhaps the completion one). 

Some of these issues may be fixed as we revisit some of the UI design and programming in #856

**Comment by nrotstan** [comment]
I think many of these issues, such as a lack of minimum widths, have been largely addressed. If you are still running into specific layout problems, please feel free to reopen with specifics.
