### ISSUE TITLE
share a project has disapeared

### ISSUE THREAD

**Issue by JLZIMMERMANN** [osmlab/maproulette3#671]
We are no more able to share a project while going in admin displaying.

**Comment by nrotstan** [comment]
@JLZIMMERMANN, there is now a new "Project Managers" widget on the admin Project page (when you click on a project name in the admin area to administrate that project). If you don't see that widget, try clicking Edit Layout and then Add Widget and choose Project Managers.

<img width="724" alt="project_managers" src="https://user-images.githubusercontent.com/445970/53981412-59286580-40c7-11e9-8c27-4b2f342121ac.png">

Let me know if you're referring to something different.
