### ISSUE TITLE
save a challenge has disapeared

### ISSUE THREAD

**Issue by JLZIMMERMANN** [osmlab/maproulette3#672]
We cannot save a challenge we wish to use later.

**Comment by nrotstan** [comment]
Hi @JLZIMMERMANN, there should be a Save button when you've clicked on a Challenge from the Challenges page:

<img width="565" alt="save_challenge" src="https://user-images.githubusercontent.com/445970/53980831-27fb6580-40c6-11e9-8a55-0e38968bda84.png">

You can see a list of your saved challenges from your Dashboard on the Saved Challenges widget. They should also appear at the top of challenge results on the Challenges page (with a pink Saved label) if you're using a Default sort.
