### ISSUE TITLE
Make Enhancements to the option to mark the tasks Started, stopped or Completed.

### ISSUE THREAD

**Issue by raphaelpe** [osmlab/maproulette3#679]
Good afternoon everyone. I get confused when I start a task on the maproulette site and I want to stop and start again later, because when I click on finished task and I click on several tasks I do not know which option to click finish after completing several tasks. the button below does not load for 100% is and a doubt!

**Comment by mvexel** [comment]
Hi, you can save / copy the URL for the task and re-load it later. Unless someone else fixed the task in the mean time the screen should look the same.
