### ISSUE TITLE
'Almost finished' challenges

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#686]
Here's an idea inspired by microfunding sites like https://www.kiva.org/

When a challenge is almost finished, people are likely to want to chip in to push it across the finish line.
If we can find a way to highlight 'almost finished' challenges (based on % of tasks still available to resolve) that would give mappers more ideas for where to contribute.

**Comment by matkoniecz** [comment]
Replaced one of featured by "almost complete" selected randomly from challenges where:

- challenge is visible, % of remaining tasks is below 5%
- challenge is visible, number of remaining tasks is below 100 and % of remaining tasks is below 30%

or

- % of remaining tasks is lowest of all visible challenges (to always have at least 1 candidate)

?

![screen01](https://user-images.githubusercontent.com/899988/107947662-fa4a1700-6f92-11eb-9aa3-aef31568b3b4.png)
