### ISSUE TITLE
Mass delete tasks

### ISSUE THREAD

**Issue by giblet22** [osmlab/maproulette3#700]
On the challenge management page, if I zoom into a geographic area (and the list of tasks reduces to what's visible) it'd be useful to be able to mass edit tasks, ie. "remove selected from challenge", so the challenge manager wouldn't need to go through one by one to edit

![image](https://user-images.githubusercontent.com/7945333/55368480-05d7e600-54c0-11e9-8a85-874d0440275d.png)

**Comment by nrotstan** [comment]
We still don't offer mass delete, but we do now offer mass "disable" functionality. Disabled tasks won't be served to mappers.

![disable_tasks](https://user-images.githubusercontent.com/445970/67136778-13e12000-f1e0-11e9-8585-80a1727aded6.gif)

**Comment by nrotstan** [comment]
Closing this issue given that we have mass disable. I think mass delete could prove too dangerous.
