### ISSUE TITLE
Help link

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#72]
Let's add a help link to the top bar (content TBD)

**Comment by mvexel** [comment]
See also #96

**Comment by mvexel** [comment]
We can create this screen / modal now and build it out later. I suggest we link to the two blog posts that exist already (see #96) and the API documentation @mgcuthbert knows the link to that.

Let's collect resources [on the wiki](https://github.com/osmlab/maproulette3/wiki/Help-and-Resources)

**Comment by nrotstan** [comment]
PR #446 adds a help link that just points to that wiki page for now. We should probably discuss how we want to actually add in user documentation (read the docs, github pages with jekyll, stick with a wiki, custom page, something else, etc.).
