### ISSUE TITLE
Can't modify task

### ISSUE THREAD

**Issue by avataranedotas** [osmlab/maproulette3#731]
After clicking on inspect in an individual task, then modify task, if changing the status from Skipped or Too Hard to Fixed I get the error:

Unable to save your changes: ERROR: function create_update_task(character varying, bigint, character varying, integer, bigint, integer, bigint, character varying, unknown, integer, bigint, bigint, unknown) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 8

**Comment by nrotstan** [comment]
Thanks for reporting this, @avataranedotas! PR maproulette/maproulette2#536 has been submitted to fix it.

**Comment by nrotstan** [comment]
This should be fixed now, but please feel free to post here if you continue to have trouble.
