### ISSUE TITLE
Community translation using Zanata or similar

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#734]
There are various platforms for collaborative translation that offer free service for open source projects. https://www.quora.com/Are-there-any-good-open-source-collaborative-translation-apps has an incomplete list. Connecting with such a platform will make it easier for people to contribute to MapRoulette localization.

What are other OSM applications (iD, osm.org) using?

**Comment by mvexel** [comment]
For now I created https://docs.google.com/spreadsheets/d/1oqpSboEEJQuAh5Noa9KBZgcbqIe1JqDQSN_3UCf5wtk/edit#gid=1513950876 to help the user who wants to create translations in German and Romanian with a team of helpers.
This is not a final solution :)

**Comment by mvexel** [comment]
Okay, after some back and forth with the folks who want to help translate it sounds like a spreadsheet is too unwieldy at this size. And as mentioned it doesn't scale anyway. 

They offered some advice and potentially help setting up Transifex:

> It is pretty straight forward to set up a project on transifex. It requires a .tx directory containing the correct reference to the translation project, and links to the source file, the source language and the available languages (translations). I don't know if your are on Linux, Mac or Windows, but it requires the transifex cli https://docs.transifex.com/client/installing-the-client from the client you can push and pull translations and sources, given they are configured correctly. 

@nrotstan do you have experience with this? Does it look easy enough to integrate into our release practice?

**Comment by mvexel** [comment]
see also #737

**Comment by nrotstan** [comment]
PR #1180 integrates transifex.

**Comment by nrotstan** [comment]
This is now on maproulette.org
