### ISSUE TITLE
Valid JSON example to create challanges using the API

### ISSUE THREAD

**Issue by Noki** [osmlab/maproulette3#744]
I want to split the phone and fax number challenges into smaller areas because I worked on automating rebuilds using the API and some of the countries always run into timeouts. Since I would have to create quite some of them I want to use the API. However I couldn't figure out how to create a valid JSON that creates a new challenge. There are simply too many undocumented fields or fields that probably get filled automatically anyway.

Can you please provide an example JSON that creates a overpassQL based challenge so I can adapt?

Best regards
Tobias

**Comment by nrotstan** [comment]
Hi @Noki , here's a pretty minimal working example. It does include a few empty fields, some of which you may be able to omit (you'd need to experiment). This JSON was successfully POST'ed to the /api/v2/challenge endpoint and created a new challenge.

```json
{
  "blurb": "",
  "checkinComment": "#maproulette",
  "defaultBasemap": -1,
  "defaultBasemapId": "",
  "description": "This is the challenge description",
  "difficulty": 2,
  "enabled": false,
  "featured": false,
  "highPriorityRule": "{}",
  "instruction": "These are the challenge instructions",
  "lowPriorityRule": "{}",
  "mediumPriorityRule": "{}",
  "name": "My Example Challenge",
  "overpassQL": "way[\"building\"][amenity=community_centre](47.585808835927374,-122.34752655029297,47.61452673188984,-122.30813026428223);\nout body geom qt;",
  "parent": 756,
  "tags": ""
}
```

**Comment by Noki** [comment]
@nrotstan thanks a lot! Works now!

**Comment by Noki** [comment]
@nrotstan One thing is kind of unsuspected:

```
{
status: "KO",
message: "Challenge with name <Example> already exists in the database"
}
```

I deleted my test challenge. However the unique name is even enforced once I deleted my test challenges. It would be nice if this would not take into account challenges with a `"deleted": true` status. Otherwise some challenge names are now blocked.

**Comment by nrotstan** [comment]
Challenges are just marked as deleted initially and then are really deleted by a server job. Partly that is to allow undelete in case of a mistake, and partly because deleting challenges can be expensive. Once the challenge is really deleted, the name is freed up.

**Comment by mvexel** [comment]
@Noki I sent you a message through OSM about the phone number project which I made invisible for the time being because of the very large number of challenges. Feel free to get in touch on the OSM message thread about that. Thanks for understanding.
