### ISSUE TITLE
Project Admin Dashboard does not work well with a lot of Challenges

### ISSUE THREAD

**Issue by Noki** [osmlab/maproulette3#750]
I splitted the phone challenges into a lot of smaller challenges. While this works great to automatically rebuild them using the API, the number of challenges now causes issues with the Admin-UI:

![image](https://user-images.githubusercontent.com/198902/57476521-16396880-7297-11e9-91bb-f1182157a79d.png)

![image](https://user-images.githubusercontent.com/198902/57476544-205b6700-7297-11e9-97c8-973dfa7b8d04.png)

The URL to request the leaderboard exceeds the maximum lenght for URLs allowed in a GET request.

Instead of using the challenge IDs it might be a good idea to use the project id instead or switch to a POST request.

**Comment by nrotstan** [comment]
It's still not probably going to be great, @Noki , but hopefully performance of basic administration is a little more tolerable now on maproulette.org

Even so, we're going to begin capping the number of challenges per project (probably to around 100) as well as the number of tasks per challenge. See #1535 and #1536 for open discussions on that -- your feedback would be appreciated.
