### ISSUE TITLE
Can't change editor

### ISSUE THREAD

**Issue by mds08011** [osmlab/maproulette3#759]
When I try to change the editor being used in a task, I see a spinning wheel next to the “Current Editor” field but it never seems to complete.  If I click edit, Maproulette still tried to open my previous editor.  In the screenshot below I am trying to change from opening in JOSM to iD. 

![image](https://user-images.githubusercontent.com/8010709/57944752-cce7ab00-788c-11e9-89b0-ed33ac4bf192.png)

I was able to work around this by changing the default editor in my user settings but I cannot change editors within a project.

**Comment by InsertUser** [comment]
I am seeing the same issue. Made worse by overriding OSM user default preferences in favour of MapRoulette default 😒.

**Comment by Sosha1996** [comment]
try this way:
click on your Profile on top-right Screen > open User Settings > Default Editor
![image](https://user-images.githubusercontent.com/16008585/58139542-6083f780-7c50-11e9-8552-77898d4c5283.png)

\- oh lol, now i see you said this solution :D
