### ISSUE TITLE
Including start-stop mapping timestamps in CSV

### ISSUE THREAD

**Issue by herriotto** [osmlab/maproulette3#762]
When downloading the CSV files from a challenge there is a column for 'Mapped on', which contains the time and date. It would be nice to also have  columns indicating Start/stop (or submitted) in order to understand the amount of time taken for a task in a challenge.

**Comment by mvexel** [comment]
A task could be 'started' / 'stopped' by multiple users as long as it's not marked as 'fixed' or 'too hard'. Are you interested in the time it takes between opening in marking 'fixed' by the user who *fixes* the challenge?

**Comment by herriotto** [comment]
thanks! I was referring to when a task was 'opened' and then the resolution state was changed to 'fixed' , 'too hard', ' skipped', or any other resolution state, rather than 'stopped' for some external reason.

**Comment by mvexel** [comment]
Okay, that data should already be in the database. We can consider adding something like the following to CSV output:

* One column `last_started` that is the timestamp of the last user starting this task
* One column `last_closed` that is the timestamp when that same user applied the current resolution state to the task.

**Comment by reichg** [comment]
this is something that we can hopefully implement in a task_history table similar to tasking-manager. That way we can record all of the interactions with a task and have it stored. Makes for more detailed analysis which helps derive ongoing metrics and goals.

**Comment by nrotstan** [comment]
@reichg The timing data is largely already captured in the database. Some of the work for efficiently surfacing that data has been completed and will likely be in the next release, with additional iterations to follow.

**Comment by nrotstan** [comment]
Addressed by PR #1141

**Comment by nrotstan** [comment]
This is now on maproulette.org. Please note, however, that task-completion times in CSV exports will only apply to tasks completed going forward -- not to historical tasks.
