### ISSUE TITLE
Make clearer that overpass query can't be edited on challenge

### ISSUE THREAD

**Issue by CloCkWeRX** [osmlab/maproulette3#783]
Scenario:
I create a challenge to identify all "Bakers Delight" stores and develop an overpass query. I realise later there is an alias - "Baker's Delight", and wish to modify the original challenge query.

I also accidentally set the timeout to 25s on the query, but want to increase that to 60s.

 1. Edit challenge
 2. GeoJSON tab

Expected:
 * The query textarea is editable or
 * The query textarea is not editable, but also styled as disabled with an explanation as to why / a prompt this risks a mismatch in generated tasks.

Actual:
 * The query textarea is readonly, but looks editable.

https://maproulette.org/admin/project/4202/challenge/8118/edit

![image](https://user-images.githubusercontent.com/365751/59083995-a9b69580-8938-11e9-996e-096b107b2c88.png)

![image](https://user-images.githubusercontent.com/365751/59084027-c6eb6400-8938-11e9-8641-141f409d01a0.png)

(It's also very small)

**Comment by nrotstan** [comment]
We could definitely add an explanation and make it visually clearer that it's not editable.

The overpass query cannot be edited once tasks have been generated for the challenge. You would need to create a new challenge if you wished to use a different query (you can clone the original challenge if you want to keep most of the setup the same).

**Comment by nrotstan** [comment]
I've updated the title of this issue

**Comment by tordans** [comment]
I ran into the same issue, just now with my first challenge.

I will have to remove it now … which does not feel great. Is there really no way to make the query editable and re-run the background tasks again?

For the current state of think, changing the text on the page should be enough:
Once I look at https://maproulette.org/admin/project/ID/challenge/ID/edit
- All help text can be removed, it only needed for the creation process
- A new info can explain "no edit possible; if edit needed, please clone this challange and delete the old one"

**Comment by nrotstan** [comment]
@tordans a challenge can be cloned if you need to create a similar one with a different query. Can you elaborate on the scenario where you are trying to modify the query for an existing challenge?

**Comment by hbruch** [comment]
I just created my first challenge and immediately ran into a not editable overpass query. After publishing the challenge, I edited a few tasks and noticed, that I should refine the query as it included too many false positives. While I should perhaps have been more careful when creating the challenge, this might happen to others as well.

However, if it a query can not be changed, this should be clearly stated (I thought this to be an error, too).

What is the technical background behind this constraint?

**Comment by nrotstan** [comment]
Thanks for discussing your situation, @hbruch, it's helpful. Given the current constraints, the clone option is what you want: clone your challenge, provide a new query, and then delete the old challenge if desired.

We started preventing edits to queries mainly to keep things clean and sane, as we've seen challenges get messed up through augmentation of tasks with a modified query, and -- even when tasks are wiped clean -- we've also seen "challenge creep" whereby old challenges get recycled for related, but different, purposes.

**Comment by CloCkWeRX** [comment]
I'd be keen on removing the readonly attribute in favour of perhaps a 'preview in overpass' link or a few "are you absolutely sure you need to edit this" UI nag; to discourage the other behaviours.

A common mistake: recursing instead of using out geom; so adding a regex detection of that to queries and warning users might be worth while looking at too.
