### ISSUE TITLE
Starbucks renaming challenge problems

### ISSUE THREAD

**Issue by jarek** [osmlab/maproulette3#787]
Hello,

In https://www.openstreetmap.org/user/mvexel/diary/46863 you've introduced good challenges as "Do not require local knowledge".

Unfortunately the Starbucks challenge https://maproulette.org/browse/challenges/4046 is not that. Many of our Starbucks Coffee shops are named, well, Starbucks Coffee. Perhaps they will be renamed soon, but the signs on the walls have not been changed as of now. Going by what brand uses globally vs what is signed on the store breaks OSM's principle of on-the-ground verifiability. Together with various iD "validations" you are encouraging remote mass editing.

In last couple of days I have seen two editors who have never edited in Ontario before go in and incorrectly rename coffee shops.

I have reverted https://www.openstreetmap.org/node/6419764357 (please see the Mapillary link) and will have to do the same to https://www.openstreetmap.org/node/902313985 (see https://www.mapillary.com/map/im/Ml6aboNNAdr-qJ9zqQbOVQ).

Please limit these challenges to geographical regions where you are certain all stores have been renamed, or at very least require users to confirm edits via streetside imagery like OpenStreetCam or Mapillary.

**Comment by mvexel** [comment]
I get your point and the challenge owner should probably change this. Could you message the challenge owner to have them fix this, please?

**Comment by jarek** [comment]
Where can I find who the challenge owner is?

**Comment by jarek** [comment]
Thanks to https://github.com/osmlab/maproulette3/issues/791#issuecomment-501092948 I found out that the project owner can be found only on individual task pages like https://maproulette.org/challenge/4013/task/14271708 via the "Contact Owner" link which discloses the owner's OSM username. This seems suboptimal but a better solution would probably be provided by https://github.com/osmlab/maproulette3/issues/791

The question is meanwhile moot as the Starbucks project has been "completed".
