### ISSUE TITLE
Provide more information about challenges in changesets, and have a centralized challenge feedback system

### ISSUE THREAD

**Issue by jarek** [osmlab/maproulette3#788]
Hello,

My experiences while researching https://github.com/osmlab/maproulette3/issues/787 could have been improved.

My process was:
- see that a store has been incorrectly updated
- try to figure out why this change was made
- go into the changeset, in this case https://www.openstreetmap.org/changeset/71005069
- read the message "Rename Starbucks Coffee to just Starbucks #maproulette"
- look for extra metadata and find none other than imagery_used="Maxar Premium Imagery (Beta)", an imagery set I am not familiar with as a local editor
- go into the editor's profile to see if they are also a local editor, but instead see edits all over continental United States in most recent editing history
- check my own survey imagery and confirm that the edit was incorrect and I'm not going crazy

Some of the things I would have liked to see:

1. Link to the MapRoulette challenge that prompted this change, in this case https://maproulette.org/browse/challenges/4046

2. A clearer changeset message to indicate that this is a worldwide/continent-wide challenge and not based on local knowledge or surveys

3. Strongly encourage editors to only make changes that are the object of the challenge, to avoid having remote mappers make changes like https://www.openstreetmap.org/changeset/70708636

4. Provide a centralized feedback channel for the challenges.
My first instinct was to complain to the editor who made the edit, and indeed I had at first done so on https://www.openstreetmap.org/changeset/70696907 and https://www.openstreetmap.org/changeset/70640323. This doesn't work very well - there is no centralized tracking of all comments made on changesets made for a given challenge, and even if the user responds, what will they say - "sorry, I was just doing what MapRoulette and iD told me to do"?
If you are going to ask remote editors to make edits based on a set specification, it would be much better to provide a forum to give feedback on these changes in a centralized way, like a comments field on https://maproulette.org/browse/challenges/4046 itself, and link to it in the changeset metadata. I ultimately found my way to this issue tracker where I created the issue. I still don't know if that's the right venue. Should I write to some mailing list instead? There is nothing on the MapRoulette page, nor on the wiki page linked under "Learn".

**Comment by mvexel** [comment]
Hi @jarek , thanks for these suggestions!

I think we should definitely add a link to the challenge to the changeset comment, and in fact there is already an issue open about this #178 . So we will handle that part under that issue. If you have any further suggestions on that part please add them to that ticket.

Generally the assumption with MapRoulette is that the mapping is 'armchair' and not survey, so to my mind the `#maproulette` hashtag should already indicate that the edits in this changeset are not survey based. 

I think the option of having comments on challenges could be a good idea to centralize discussing challenges as a whole rather than individual tasks. Could you please open a separate ticket for that?

**Comment by jarek** [comment]
To be honest, I personally don't think that adding "#maproulette" to the changeset comment is a great solution. There is already a lot of internal OSM terminology that a new user needs to know to "get" OSM - and #maproulette is yet another one. What makes #maproulette special as compared to a longer-established "armchair"?

I have created #791 for the feedback forum as requested.
