### ISSUE TITLE
Empty mustache tag values should return nothing

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#837]
For example, if you have the following as part of your instructions:

> amenity={{amenity}}    
> name={{name}}    
> source={{source}}    

and the value of {{name}} in your source is empty, your contributor will see something like:
```
amenity=fire_station
name={{name}}
source=Bureau of Fire Protection
```

While ideally, one could expect something like:
```
amenity=fire_station
name=
source=Bureau of Fire Protection
```

Maybe empty mustache tags should return nothing, instead of the tag itself.

**Comment by govvin** [comment]
This behavior changed recently, and now an empty variable returns the a string, "null." Would it be possible to just returning nothing, like:
```
amenity=fire_station
name=
building=yes
```

Instead of 
```
amenity=fire_station
name=null
building=yes
```

which used to be
```
amenity=fire_station
name={{null}}
building=yes
```

**Comment by nrotstan** [comment]
They should now show empty if missing, e.g. 
```
amenity=fire_station
name=
```

**Comment by govvin** [comment]
Hi again. I was drafting a new challenge today, and noticed that this behavior is back.

When a empty value is encountered for a mustache tag, it again returns "null"

**Comment by nrotstan** [comment]
PR #1465 overhauls the implementation of the templating system used in the Task Instructions, and should permanently address this issue.
