### ISSUE TITLE
Small bounds navigation bugs

### ISSUE THREAD

**Issue by Matthias84** [osmlab/maproulette3#838]
I work on all tasks when I monitor my local area. Thus I use the intersecting map bounds filter a lot and noticed two odd bugs

1. If you pick a task from the list, the zoom is reset to the full bbox of this task, but not the current area
2. After picking a tasks and working on it, the map bounds filter got reset.

Would be cool, if you could fix it, to make the roulette of a particular area more fun.

**Comment by nrotstan** [comment]
These should be fixed. Feel free to reopen if you continue to experience issues.
