### ISSUE TITLE
When creating a challenge, pressing [Enter] inthe first screen cancels, losing anything you already entered

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#851]
When not in a text area, ENTER cancels out of the first screen, losing any information you already typed. Since this can be quite a lot of effort already made (crafting description, instructions) this can be pretty frustrating.

Suggest to either have enter do nothing or advance to the next screen instead.

**Comment by nrotstan** [comment]
This should now be fixed as of v3.4.3 (addressed by PR #941)
