### ISSUE TITLE
"Unable to render the map" Error

### ISSUE THREAD

**Issue by unkind-spirit** [osmlab/maproulette3#852]
https://maproulette.org/challenge/3754/task/23126158
"Unable to render the map. This may be caused by a problematic custom basemap." dialog is shown.

There is an error in browser console:
Error: Invalid GeoJSON object.
Stack trace:
zn@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:108817
addData@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:107694
addData@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:107603
initialize@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:107441
t@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:27123
Gn@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:109560
t/a.updateFeatures@https://maproulette.org/static/js/main.205d3bf9.chunk.js:1:504157
value@https://maproulette.org/static/js/main.205d3bf9.chunk.js:1:505193
Ua@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2892153
$a@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2894831
ks/<@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2908060
t.unstable_runWithPriority@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2918806
ks@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2907993
js@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2907771
Ms@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2907116
Ss@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2906137
Ja@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2905011
enqueueSetState@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2854266
w.prototype.setState@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2804556
O/</s</u.onStateChange@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:172334
v@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:400151
r/</</<@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:2744441
dispatch@https://maproulette.org/static/js/2.c49919e4.chunk.js:1:403159
pe/</<@https://maproulette.org/static/js/main.205d3bf9.chunk.js:1:586905
  react-dom.production.min.js:4408
	ha react-dom.production.min.js:4408
	xa/n.callback react-dom.production.min.js:4797
	ia react-dom.production.min.js:4271
	ra react-dom.production.min.js:4257
	Ua react-dom.production.min.js:4983
	$a react-dom.production.min.js:5123
	ks/< react-dom.production.min.js:5975
	t.unstable_runWithPriority scheduler.production.min.js:274
	ks react-dom.production.min.js:5974
	js react-dom.production.min.js:5958:3
	Ms react-dom.production.min.js:5925
	Ss react-dom.production.min.js:5860
	Ja react-dom.production.min.js:5787
	enqueueSetState react-dom.production.min.js:2790
	w.prototype.setState react.production.min.js:72
	O/</s</u.onStateChange connectAdvanced.js:205
	v createStore.js:175
	r/</</< index.js:11
	dispatch applyMiddleware.js:46
	pe/</< Challenge.js:299:6

And also a warning
Loading failed for the <script> with source “https://piwik.rtijn.org/piwik.js”.

**Comment by mgcuthbert** [comment]
Are you the owner of the challenge? It seems that the task referenced in the bug has been deleted.

**Comment by unkind-spirit** [comment]
No, unfortunately. I am not the owner. But it worked perfectly yesterday
night.
My assumption - something went wrong after the upgrade (mentioned on the
site).

**Comment by Andygol** [comment]
@mgcuthbert 
The problem still exists. It is related to the settings of the base map, but not to the absence of tasks.

![image](https://user-images.githubusercontent.com/369696/62851640-7523d900-bcef-11e9-844a-86cadb1d1f06.png)

Data for the task https://maproulette.org/browse/challenges/3754 is borrowing from QA/QC tool - http://pavlo-dudka.github.io/osm-pg-tests/test.html?map?highway.crossings and even is shown on the challenge page

![image](https://user-images.githubusercontent.com/369696/62851853-3d696100-bcf0-11e9-94d3-4444f1f65a59.png)|![image](https://user-images.githubusercontent.com/369696/62851864-478b5f80-bcf0-11e9-97ee-997e0b5dbfc3.png)
---|---

The same problem is observed with other tasks.
- https://maproulette.org/browse/challenges/3657
- https://maproulette.org/browse/challenges/3754 (task reported in this ticket)
- https://maproulette.org/browse/challenges/3758
- https://maproulette.org/browse/challenges/3763
- https://maproulette.org/browse/challenges/3764

All these challenges have `User Default` as a value for  "Challenge Basemap". 
"Rebuild Tasks" doesn't solve the issue.

**Comment by mgcuthbert** [comment]
This issue will be resolved by checkin for the API https://github.com/maproulette/maproulette2/pull/596. Once it is merged and deployed which will be a little later today then this will be resolved.

**Comment by nrotstan** [comment]
This should now be resolved. Please reopen the issue if you continue to experience problems.
