### ISSUE TITLE
Error when exporting the tasks as geojson

### ISSUE THREAD

**Issue by nlehuby** [osmlab/maproulette3#854]
I get the following error when I try to export tasks from my challenge as geojson:
`ERROR: missing FROM-clause entry for table \"tr\"\n  Position: 3157`

https://maproulette.org/api/v2/challenge/view/4208?status=1,2,3,4,5,6&priority=0,1,2&reviewStatus=0,1,2,3,4,-1

**Comment by mgcuthbert** [comment]
This issue will be resolved by checkin for the API https://github.com/maproulette/maproulette2/pull/596. Once it is merged and deployed which will be a little later today then this will be resolved.

**Comment by nrotstan** [comment]
This should now be resolved. Please reopen the issue if you continue to experience problems.

**Comment by nlehuby** [comment]
thanks!
