### ISSUE TITLE
Improve "Find Challenges" functionality

### ISSUE THREAD

**Issue by Noki** [osmlab/maproulette3#859]
The default settings for the "Find Challenges" page are currently far from ideal. Some projects have a lot of challenges and with the current settings often a lot of challenges from the same project show up:

![image](https://user-images.githubusercontent.com/198902/63211797-5b71ff80-c0fc-11e9-96ac-cd888e0d3769.png)

![image](https://user-images.githubusercontent.com/198902/63211761-f1595a80-c0fb-11e9-865b-45b5d6933f97.png)

Exactly due to this behaviour @mvexel made my Inconsistent Tags Project (1141) invisible some months ago. In my opinion nothing is wrong with having a high number of specialized challenges within a project. Therefore I propose the following changes to fix this issue:

- Add limits that only show a couple of challenges (e.g. 2) from the same project in search
  - show more, once the total results are below e.g. 10, which would happen if you zoom in to certain areas
- Switch to “Within Map bounds” as default location setting in addition
- Show the whole world as default bounding box

**Comment by mvexel** [comment]
Hi @Noki 

You're right, things could be improved for 'global' challenges which you suggested in #251 some time ago. 

How about this:
* A challenge can have a flag saying that it is a 'global' challenge (this could even be detected automatically by MapRoulette based on some minimum tasks bounding box). 
* When this flag is set, the challenge will show up as 'global' in the challenge search.
* Users would be able to filter out global challenges when searching for challenges as well as on the map when zoomed in.

This will also make it necessary to potentially deal with (very) large challenges (tens of thousands of tasks).

**Comment by Noki** [comment]
Hi @mvexel,

I don't think that filtering for global challenges is a thing. Usually users want to fix stuff in a certain area and this is simply done with a bounding box filter of the map. For most people it only matters that ther is an effective way to select only tasks within a certain area. So there is not really a need to filter out global challenges.

In case of the phone number challenges it was necessary to split it into a lot of local challenges to deal with overpass api timeouts and to have an automated rebuild process triggered using the api. There is currently no good process to have the phone number challange as a single global challenge.

Also I would always implement a global flag in a way, that it is automatically set based on the data instead of having someone to flag it. With the 3482 phone number challenges it is totally unpractical to flag anything by hand anyway. ;-)

Best regards
Tobias

**Comment by nrotstan** [comment]
I think most of these suggestions have been included in recent releases, so I'm going to close this issue. Feel free to open new, specific issues if desired.
