### ISSUE TITLE
Add RapiD as editor option

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#883]
RapiD is Facebook's iD version optimized for adding ML-generated roads to the map quickly. It can be a very useful alternative editor for some challenges. 

[Here's the RapiD editor in action](https://mapwith.ai/rapid#background=Maxar-FB&disable_features=boundaries&map=16.74/47.42241/-120.28503).

More info at [mapwith.ai](https://mapwith.ai)

Further integration opportunities with the data underlying RapiD definitely possible in the future, especially working towards geometry quick fixes.

**Comment by mvexel** [comment]
See https://github.com/osmlab/maproulette3/pull/917 for the corresponding PR

**Comment by nrotstan** [comment]
Added in v3.4.2
