### ISSUE TITLE
unable to change source

### ISSUE THREAD

**Issue by iriman** [osmlab/maproulette3#890]
I created a challenge using overpass api query and now I decided to source it from local/remote file, but these options are not available anymore at the 2nd step. even editing the query was not possible normally and I did it via browser inspector.

I've decided to do this due to a change in query that  have increased amount of results   and this causes query timeout.

thanks

**Comment by nrotstan** [comment]
The easiest thing might be to clone the challenge and then choose a different source on the clone. You can then delete the original challenge if desired. Once tasks are created, we don’t currently allow changing of the source.
