### ISSUE TITLE
iD doesn't open the map at the correct location

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#892]
The latest version introduced a bug where iD doesn't open at the task location when clicking 'edit' and iD is selected as the editor of choice.

See also https://twitter.com/JLZIMMERMANN/status/1173831586007191552

**Comment by nrotstan** [comment]
Can you provide an example challenge? It seems to be working correctly for me when I try it.

**Comment by mvexel** [comment]
https://maproulette.org/challenge/3637/task/11532704 drops me in Florida. Basically it drops me where I last had iD open.
