### ISSUE TITLE
JOSM Remote Control doesn't work on ChromeOS

### ISSUE THREAD

**Issue by weech** [osmlab/maproulette3#902]
From what I could tell, the actual requests to Remote Control are sent at [this point](https://github.com/osmlab/maproulette3/blob/master/src/services/Overpass/Overpass.js#L27). In that line, the address `127.0.0.1` is hardcoded. Unfortunately, that address doesn't work on ChromeOS as JOSM is forced to run on a special VM. Instead, it needs to be accessed through `penguin.linux.test`. Perhaps a snippet like
```Javascript
var localhost = window.navigator.userAgent.contains("CrOS") ? "penguin.linux.test" : "127.0.0.1";
sendJOSMCommand(`http://${localhost}:8111/import?new_layer=true&layer_name=` +
                     adjustedDateString + '&upload_policy=never&download_policy=never&url=' +
                     encodeURIComponent(overpassApiURL))
```
added to that function would fix the problem, but I don't know enough to be sure of myself.

**Comment by nrotstan** [comment]
Thanks, @weech , I don't have a Chromebook to test this on but will look into it. Out of curiosity, if you install a browser on the VM and use it for MapRoulette, will it contact JOSM correctly?

**Comment by weech** [comment]
I gave it a try running Vivaldi in the VM, and it works correctly from there.

**Comment by nrotstan** [comment]
Closing as there is a work-around, and we're not likely to fix this anytime soon. I'd be happy to consider a PR if someone wants to submit one.
