### ISSUE TITLE
Challenge only shows tasks in high priority, although there are other tasks available in the challenge.

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#904]
I made a [challenge](https://maproulette.org/challenge/9370) with several priorities, but it only shows those set with high priority -- and these tasks were already marked as hard or skipped by other mappers.

 I wonder if this is related to an error I encountered earlier, #901 . 

My understanding is that when lower priority tasks are still available, contributors should be able to continue doing other tasks other than the one they already skipped.

**Comment by nrotstan** [comment]
The way things stand today, skipped higher priority tasks will be served before any lower priority tasks are served unless a user has gone through them all within the past hour, in which case lower priority tasks will be served to that user (but other users would get the skipped higher-priority ones unless they went through them all within an hour too).

The same is also true of too-hard tasks, though there is an option on the server to completely disable serving up of tasks marked too hard. At the moment we have serving enabled on the theory that one person's too hard may be very doable for someone else with a little more experience.

These rules definitely aren't perfect -- they work well in some situations, and not so well in others. Discussion and ideas are always welcome.

**Comment by govvin** [comment]
That sounds perfectly reasonable, but in the setup we had yesterday, trying out this task with a room of about 20 people attempting to do the tasks - everyone marked them as "too hard/ couldn't see" or has skipped them but nobody couldn't get out of the loop of recycled tasks. 

I felt we wasted their time by showing the same thing, and them doing the same actions, and they couldn't move forward with things they can work on instead. I think the current rule is very good for remote, independent verification -- but not ideal for setups with mapathon-like setups?

Perhaps, instead of limiting the time to one hour per reviewer the same task wouldn't be served if it's been marked X number of times by at least X number of people in the last hour?

Or better yet, I could've intervened by shelving those tasks but but the dashboard doesn't show anything right now, and probably related to another issue I encountered earlier #901 :
![image](https://user-images.githubusercontent.com/5821688/65735178-d91c2880-e108-11e9-9421-ce3a5bb1ad8e.png)

**Comment by mvexel** [comment]
So to solve @govvin's issue, we would need to prioritize lower-priority tasks that are marked as created / skipped over higher-priority tasks that are marked too hard, but only if there are no higher-priority tasks available with created / skipped status. Am I interpreting this correctly?

I am a little hesitant to re-interpret the rules that folks may have come to rely on.

I think a valid work-around for this specific situation would be to create separate challenges instead of relying on priorities. To avoid unexpected rules behavior and resulting disappointment / wasted time, I will update the documentation at https://learn.maproulette.org/documentation/task-priority-rules/#content to better reflect what the rules do in these edge cases.

**Comment by mvexel** [comment]
As I am writing the update to the docs, I realized that the current application of rules just isn't right.

The assumption that a task marked as "Too Hard" could still reasonably be solved by another mapper seems flawed. I think we should implement a version of https://github.com/osmlab/maproulette3/issues/217 instead. So I will still close this ticket but will add 217 to the 3.9 or 4.0 milestone (to be discussed with @jschwarz2030)
