### ISSUE TITLE
Edit in iD does not select  

### ISSUE THREAD

**Issue by hbruch** [osmlab/maproulette3#906]
Expected behavior: When I 'Edit in iD' the editor should have the object selected. 

Observed behavior: For [this overpass challenge](https://maproulette.org/browse/challenges/9377) iD opens without the object being selected. 

This issue is similar to #78 but as the tasks are retrieved from an overpass result, the ID should be available.

**Comment by nrotstan** [comment]
Thanks for reporting, this will be fixed in the next release.

**Comment by hbruch** [comment]
Will it be possible to add a specific property (e.g. @id=n{dddd}) in manually uploaded GeoJSON (use case #78) that will be interpreted as OSM-ID?

**Comment by nrotstan** [comment]
Fixed in v3.4.2

And yes, `@id` properties in the GeoJSON are already supported and interpreted as OSM ids. They typically are formatted as `node/12345789`.
