### ISSUE TITLE
Incomplete pop-up when OSM data is on, and selecting an object

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#910]
While OSM data is enabled, clicking on any feature will display an a modal window that shows nothing.

![Peek 2019-09-28 14-21](https://user-images.githubusercontent.com/5821688/65812566-5de76f00-e1fb-11e9-98f4-c01d34c32822.gif)

**Comment by nrotstan** [comment]
Included in v3.4.3 release
