### ISSUE TITLE
'Enter' in 'New Challenge'->'Add keyword' closes editor

### ISSUE THREAD

**Issue by hbruch** [osmlab/maproulette3#911]
Last step before completing 'New challenge' dialog is 'Add keyword'. If I press Enter, the editor is closed, the project overview page shown. Browser's 'Back' returns to the -now empty- editor page, all form field entries are lost. 

Browser is Safari.

**Comment by habi** [comment]
I've seen the same on Ubuntu 18.04 with Firefox 69.0.1 (64-bit). It's quite annyoing since it's the last step after adding quite a bunch of text...

**Comment by nrotstan** [comment]
Addressed by PR #941

**Comment by nrotstan** [comment]
Thank you for the report, @hbruch

**Comment by nrotstan** [comment]
Included in v3.4.3 release
