### ISSUE TITLE
LInks on creation of challenge point to old (defunct) wiki

### ISSUE THREAD

**Issue by habi** [osmlab/maproulette3#912]
I wanted to generate a new challenge (after seeing https://youtu.be/Fi_ZSR4V8do).
I'd like to pull my 'data' from Overpass, but am not entirely sure how to do this.
The links on https://maproulette.org/admin/project/$ID/challenges/new aim to tell me more, but link to the old (in my eyes defunct) wiki.
Specifically, the link to 'learn more' on Overpass goes to https://github.com/maproulette/maproulette2/wiki/Introducing-New-MapRoulette---Part-1.-Creating-and-Maintaining-Challenges#via-overpass which is not available.

**Comment by mvexel** [comment]
Good point @habi , the documentation is in some places outdated.
Does this help for now? https://www.openstreetmap.org/user/mvexel/diary/46863

**Comment by habi** [comment]
> Does this help for now? https://www.openstreetmap.org/user/mvexel/diary/46863

Sure it does.

And with some trial and error I found out that just copying the (compact) OverpassQL query into the appropriate field is good enough.
Here's the challenge I generated: https://maproulette.org/challenge/9400/ :)

**Comment by habi** [comment]
There are a bunch of places where the specified link shows up (--> https://github.com/osmlab/maproulette3/search?q=via-overpass&unscoped_q=via-overpass). Where would I want to start to change that if I'd want to start to work on a pull request?

**Comment by nrotstan** [comment]
Hi @habi , since that link is in a help message, it appears in the various translation files in `src/lang/` in addition to the original `src/components/AdminPane/Manage/ManageChallenges/EditChallenge/Messages.js` messages file. The link would need to be replaced in all of those places.
