### ISSUE TITLE
Export data from Maproulette

### ISSUE THREAD

**Issue by joostschouppe** [osmlab/maproulette3#914]
I used to be able to download task statuses with the Curl command below. It still works, but returns a file stating 301 Moved Permanently. What am I doing wrong?

> curl -X GET "http://maproulette.org/api/v2/challenge/XXXX/tasks?limit=0" -H  "accept: application/json" -H  "content-type: application/json" -o "cXXXX.txt

EDIT: note that I'd be happy to use another kind of download function as well

**Comment by nrotstan** [comment]
@joostschouppe can you try https? Or I believe you can use `-L` to ask curl to follow redirects. I'd guess you're getting redirected from http -> https.

As far as alternative API endpoints go, if you would prefer CSV then there is the `/challenge/:id/tasks/extract` endpoint; or if you'd like GeoJSON (which now includes task statuses), there is `/challenge/view/:id`

**Comment by nrotstan** [comment]
Swagger docs for those other endpoints if you're interested:

[CSV export](https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json#/Challenge/extractTaskSummaries)
[GeoJSON export](https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json#/Challenge/getChallengeGeoJSON)

**Comment by joostschouppe** [comment]
Thanks, I can get a download started with https. I'm looking forward to getting the GeoJSON out, but I don't understand how any of this works, so I'll get a little help elsewhere.
