### ISSUE TITLE
In Quick Fix challenge, tag popup shows data after fix

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#915]
When inspecting a 'Quick Fix' task, clicking on the object on the map reveals the data as it would be after the fix is applied. You would expect that to show the current data.
![Screenshot 2019-10-01 14 07 35](https://user-images.githubusercontent.com/120452/65996960-b023cc80-e455-11e9-806f-df021aa259ab.png)

**Comment by nrotstan** [comment]
It's just displaying the task properties from the GeoJSON (as is done for normal challenges). We could instead show the tags from the live OSM data.

**Comment by mvexel** [comment]
In the case of quick fix challenges, we should show the 'before' data in the popup. If that means getting the data from OSM, we should do that. It doesn't look like the JSON preserves the before data in the challenges I prepared using the command line converter tool..

**Comment by nrotstan** [comment]
OSM data is now shown as of v3.4.2
