### ISSUE TITLE
Support enter key in nominatim search box

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#925]
There's a search option in the challenge dashboard, but on Firefox v69.0.1 and Chromium v77.0.3865.9 , pressing enter will not execute the search, and the search button must be pressed instead.

![image](https://user-images.githubusercontent.com/5821688/66179504-d9ce3500-e69b-11e9-8482-33eb4fcf96d8.png)

**Comment by govvin** [comment]
This input behavior is the same, not only in the dashboard, but wherever you need to search for a place in a task.

It would be great if hitting the enter key after typing activates the search.

**Comment by nrotstan** [comment]
Revised issue title.
