### ISSUE TITLE
Missing action buttons - intermittent behavior

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#926]
![image](https://user-images.githubusercontent.com/5821688/66181008-b4442a00-e6a1-11e9-928f-351dcef6c767.png)

This happens intermittently, sometimes all buttons are missing, and sometimes it's just one Cancel button. 

I couldn't pinpoint what triggers it.

**Comment by govvin** [comment]
Unfortunately, @mvexel , it's so inconsistent I couldn't get it to trigger specifically, but it has happened during a group mapping activity with several people contributing, and I experienced it myself. 

It's possible it has to do with a sub-optimal Internet connection, but I'm not sure.

**Comment by nrotstan** [comment]
I still haven't been able to replicate this. Closing, but feel free to reopen if you continue to encounter the issue.
