### ISSUE TITLE
Rebuilding task operation running for several hours already

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#933]
I am trying to rebuild a task with changes with a geojson structure  (e.g. additional columns not in the orginal)  and the rebuilding operation is going on for several hours now.

![image](https://user-images.githubusercontent.com/5821688/66441503-b7f0fb80-ea69-11e9-9e08-147bd1d537fd.png)

Is this actually supported, or should I have made a different challenge?

**Comment by nrotstan** [comment]
How many tasks are there? It seems likely that something went wrong unless it’s a very large challenge. Does that geojson file work for a new challenge?

**Comment by govvin** [comment]
Unfortunately, I didn't test it by creating a separate challenge yesterday. And now that I have, it actualy failing to create a challenge, and all I got was a blank screen.

Here's a subset of the original for a smaller area. I would appreciate any help to determine the issue with the geojson file. It was created from QGIS, and validated with the built-in processing toolbox, without any errors.

[v2019-282-testing-PLW2.geojson.zip](https://github.com/osmlab/maproulette3/files/3706098/OSMaPaaralan-v2019-282-testing-PLW2.geojson.zip)

**Comment by nrotstan** [comment]
Thanks for including some sample data, @govvin . I can confirm it's a MR bug. We'lll look at getting it fixed right away.

**Comment by nrotstan** [comment]
Addressed by PR maproulette/maproulette2#627

**Comment by govvin** [comment]
Thank you @nrotstan . I tried this again in two separate challenges - one new, and the other rebuilding but I only end up with an empty challenge.

Screenshot while building:
![image](https://user-images.githubusercontent.com/5821688/66525493-37dd9b00-eb28-11e9-9cb8-dd64ae837e46.png)

Screenshot after completion:
![image](https://user-images.githubusercontent.com/5821688/66525511-4b890180-eb28-11e9-87d3-910e17726af4.png)

**Comment by nrotstan** [comment]
@govvin We just deployed a hotfix release, so this bug should be fixed now. Please let me know if you have any further trouble.
