### ISSUE TITLE
Hide completed challenges in the Find Challenges page

### ISSUE THREAD

**Issue by DavidMetcalfe** [osmlab/maproulette3#934]
Completed challenges show up in the Find Challenges view that should be hidden by default and should require some sort of toggle to view. As is, this impedes the ability to find challenges that can still be worked on.

**Comment by nrotstan** [comment]
Thanks for the report, @DavidMetcalfe . You shouldn't be offered completed challenges. Would it be possible to provide an example if you see that again?

One thing that can happen is that you can be presented with a challenge that only has tasks marked as Skipped or Too Hard remaining, the idea being that someone (perhaps with more experience than the mapper who first saw those tasks) may stilll be able to tackle them. If that's what you encountered, then we may need to do a better of conveying the fact that there are still tasks that can be worked on in that challenge.

**Comment by DavidMetcalfe** [comment]
@nrotstan The scenario you describe certainly sounds like it could've been what I encountered. What threw me off was that there was no "Start" option for me to contribute, so I took it to mean it was completed. I'll try to find some more examples.

**Comment by DavidMetcalfe** [comment]
Here we are. If I scroll to the bottom of the Find Challenges view, with no parameters changed, I can see "Cyprus ConnectivityCheck" by andrewwiseman.

![image](https://user-images.githubusercontent.com/80915/66553005-3350bc80-eaff-11e9-8b31-41dba3f82c71.png)

Inside the challenge (URL: https://maproulette.org/browse/challenges/9248), I see a Save button, but no Start button. Thus, I take it to mean this is a completed challenge, yet it still shows up in Find Challenges as though it isn't.

![image](https://user-images.githubusercontent.com/80915/66553106-5e3b1080-eaff-11e9-8e75-38b3675f2810.png)

The only other data point I notice is it also has an Invalid Date, which is covered in #684. May be unrelated though.

**Comment by nrotstan** [comment]
Thanks for the example. It definitely looks complete.

**Comment by nrotstan** [comment]
Addressed by PR maproulette/maproulette2#633 which has been included in backend release 3.6.7 (but not yet deployed to maproulette.org)

**Comment by nrotstan** [comment]
Fixed in v3.4.4
