### ISSUE TITLE
More efficient selection of tasks in Multi-Task widget

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#937]
Two suggestions that came in:

* Allow dragging a box on the minimap to select multiple Tasks
* Add an option to Select All in View on the minimap.

**Comment by nrotstan** [comment]
PR #938 will add a lasso selection tool for selecting multiple tasks


![lasso-selection](https://user-images.githubusercontent.com/445970/66602917-ed781080-eb5f-11e9-8b63-0ac8ca3c5c41.gif)

**Comment by DavidMetcalfe** [comment]
One alternative method that I suggested on Twitter was Ctrl + Click to select each point in the map. Looking forward to trying the selection tool.

**Comment by nrotstan** [comment]
Included in v3.3.4 release
