### ISSUE TITLE
Unexpected behaviors observed after rebuilding a challenge

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#943]
Hi there. There's this [challenge](https://maproulette.org/browse/challenges/9413) I rebuilt yesterday and are now exhibiting some unexpected behavior:
* the geoJSON contains 40,085 task records with valid geographic coordinates, but only 30,448 are reported to be available by the challenge
* the location indexing seems to have stalled, and only show markers for 14,998 tasks
* searching for available task and challenges in a given area,  with or without a keyword specific to a challenge,  and  setting location to "intersecting map bounds" will no longer include the challenge in the list. The task is confirmed to be available when manually selecting the task from the challenge.
* In the dashboard reports "Shown: 100% (15000) of 15000 Tasks" but the completion progress window reports a different number: "0% Fixed (13/30463)"  Is it only reporting the POIS displayed on the map?

I tested the geojson in a new challenge, and again, only 30,463 tasks are reported to be available.

![image](https://user-images.githubusercontent.com/5821688/66617170-9a0ccd80-ec06-11e9-8ffb-0982f15bbef3.png)

**Comment by nrotstan** [comment]
That's a big challenge. I'd have to dig into it to see why you're not getting the full number tasks, but the consistent totals between two attempts indicates there's likely some kind of issue (either with the data or with MR getting consistently tripped up by something on one of the tasks). If you want to attach the GeoJSON, I will take a look.

As for the 15,000 you're seeing: while most places in the app will page results, there are still a couple of places that are limited to 15,000 max tasks, including spots in the dashboard. Most challenges don't exceed that number so it isn't generally an issue, but it can be for large ones. Most of those remaining spots will likely be upgraded over the coming weeks to remove that limitation. In the mean time, if you're finding it problematic, one option would be to break up your tasks into multiple challenges to keep them below 15,000 tasks each.

**Comment by govvin** [comment]
Thank you, Neil for the quick response.  You're right about something in the geojson file triggering the issue. I tried a new challenge with just the id column in, and it was creating the expected number of tasks.

Here is an [archive](https://github.com/osmlab/maproulette3/files/3715608/v2019-284-taskings-full.geojson.zip) of a geojson version I tried that fails to create the expect number of tasks.

Thank you for helping out with this issue.

**Comment by nrotstan** [comment]
Ok great, I'm going to close this issue then. Feel free to reopen it if needed.

**Comment by govvin** [comment]
Hi Neil. I'm re-opening this issue because the other observations remain the same even after the recent rebuild.

While the number of tasks are now what I expect them to be, again the location indexing doesn't appear to be complete, 12 hours after the run.

Also, and probably related to above, all the tasks couldn't be found when searching for available tasks in a given area.

**Comment by govvin** [comment]
Addendum.

While playing with Vespucci, I found out that the tasks I'm after  (described in the earlier post above), was showing up as can be expected from that editor. So the issue I mentioned earlier only occurs while searching  the website.

Here's a screenshot from Vespucci, showing the two challenges I'm playing with:
![Screenshot_20191012-084002_Vespucci](https://user-images.githubusercontent.com/5821688/66691908-64cab300-eccc-11e9-9067-54e5e7875a23.jpg)

Curiously, the first project is public(visible) and is expected to show up,  but the other one (both the challenge and the project)  isn't -- which I didn't expect to be displayed all. So, I suppose that's a bug, too.

**Comment by govvin** [comment]
Over the weekend, I continued experimenting with this and found out a few more things

Apparently, I've been misusing the `@id` column name, which is expected to be an OSM element id while I used it as unique task reference. This wasn't obvious until I tried editing with Level 0, and it sent me to unexpected locations where those element ids exists.

I am hoping to avoid creating a new challenge so we can keep track of the contributors but is that possible if I need to change the id column itself?

So, while I'm not sure of that, I decided to create a new challenge with changes in the column name, and some other internal changes but this time - again - the challenge was missing several thousand tasks, regardless of whether it was created with QGIS or OGR2OGR.

I'm attaching the zipped geojson files I used, hoping someone could give insights about what's causing this issue.

[geojson-taskings.zip](https://github.com/osmlab/maproulette3/files/3722622/geojson-taskings.zip)

Using v284 geojson file, MR created 40,084 tasks were created, which is missing one record. There should've been 40,085 tasks. [Here's](https://maproulette.org/browse/challenges/9892) it's test task

Using v286 (either the geojson created with QGIS or OGR2OGR), MR created 30,355 tasks when there should've been 39,949. Here are the test tasks: [this](https://maproulette.org/browse/challenges/9889) created with geojson from OGR2OGR, and [this](https://maproulette.org/browse/challenges/9891) using QGIS

Please let me know if there's any additional information I can provide to help with this issue.

**Comment by nrotstan** [comment]
Hi @govvin , it's because you have duplicate names using different uppercase/lowercase, e.g. `Buli-Buli Elementary School` and `Buli-buli Elementary School`. MR requires the `name` feature to be unique (case-insensitive).

**Comment by govvin** [comment]
Thank you, @nrotstan .  I'll work around it.

> Hi @govvin , it's because you have duplicate names using different uppercase/lowercase, e.g. `Buli-Buli Elementary School` and `Buli-buli Elementary School`. MR requires the `name` feature to be unique (case-insensitive).
