### ISSUE TITLE
Feature request . Send data to clipboard

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#947]
![image](https://user-images.githubusercontent.com/5821688/66825054-13e0e600-ef7c-11e9-83e1-fb3361768741.png)

I like the copy location feature on MR. Is there a way to send additional information to the clipboard?

For example, I want to send the following text to clipboard, after a user press a clipboard icon in the instruction box.

    highway=crossing
    crossing=uncontrolled

This could be very convenient for users instead of re-typing things, or manually doing a copy & paste operation.

**Comment by govvin** [comment]
If this will be supported in the feature, I wish it would be possible to send Key/Value pairs to Clipboard and it will also ignore Keys without corresponding values.

In our existing challenge, we're asking users to manually Copy & Paste tags from the instruction box:
![image](https://user-images.githubusercontent.com/5821688/70382733-6b5b6b00-199b-11ea-9102-171f5268bc11.png)

This feature could potentially speed up the task completion process, and I've seen other challenges in MR that could benefit from this approach.

**Comment by nrotstan** [comment]
@brianjor Thanks for PR! It looks like it copies the entire contents of the instructions to the clipboard. @govvin is that what you're looking for, or are you looking for the ability to denote in the instructions (with some kind of markup) which parts get copied? Or even have multiple, separate copyable parts with their own clipboard controls?

**Comment by govvin** [comment]
In our use case, it's the latter. The ability to send certain sections of the instructions text to the clipboard would be awesome!

**Comment by nrotstan** [comment]
PR #1465 adds a new `copyable` short code that can be used to specify that some piece of text should copyable to the clipboard.

**Comment by govvin** [comment]
This sounds awesome!  When do you think will this be pushed out to
production? Looking forward to trying it out.

**Comment by nrotstan** [comment]
Probably in late January.

**Comment by nrotstan** [comment]
@govvin the `copyable` short code is now available on maproulette.org and is documented at the bottom of https://learn.maproulette.org/documentation/challenge-instructions-templating/
