### ISSUE TITLE
Export layout

### ISSUE THREAD

**Issue by mvexel** [osmlab/maproulette3#948]
If you have a good MapRoulette widget layout that you want to share with your team or other mappers, it would be nice to have a way to serialize / export / share them so others can easily load it into their setup.

**Comment by nrotstan** [comment]
You can do this using the Export option from the cog dropdown underneath the Edit Layout button.

<img width="393" alt="export_layout" src="https://user-images.githubusercontent.com/445970/67055346-a4463480-f0fc-11e9-9e71-821faeaadc4c.png">

There's some additional discussion on the [Wiki](https://github.com/osmlab/maproulette3/wiki/Using-Layouts#exporting-and-importing-layouts)

**Comment by mvexel** [comment]
I knew this of course :blush:
