### ISSUE TITLE
No pogress when cloning/creating task

### ISSUE THREAD

**Issue by hbruch** [osmlab/maproulette3#953]
For the first task I created an hour ago, a nice progress page was shown, refreshing every 10 seconds. 

As I mistakenly used an overpass-query which converted the features into points, I wanted to clone it. But instead of a progress bar, only a spinning wheel was shown for several minutes without further progress. Trying to recreate the task resulted in the same spinning wheel.

<img width="216" alt="grafik" src="https://user-images.githubusercontent.com/2187389/67166368-d2db3e00-f38e-11e9-9bde-32d6b4456e64.png">

**Comment by nrotstan** [comment]
Thanks for the report, @hbruch . Would you mind providing the Overpass query you were using? I haven't been able to replicate this issue yet.

**Comment by hbruch** [comment]
I think it might rather be caused by a reused task name than the overpass query. I cloned the task just to modify the overpass query and reused the name. I could imagine a unique key constraint causing this issue(?). After changing the name a bit, the task was recreated successfully
