### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jharpster** [osmlab/maproulette3#96]
Some documentation on setting up new challenges would be nice.

**Comment by mvexel** [comment]
Agreed. For now, while the UI is still in flux, I may do a quick video Once we get to Golden Master ✨🥇💎✨ I will create something written and illustrated.

**Comment by mvexel** [comment]
Since we're still tweaking the UX around Challenge creation, I am holding off for just a bit longer on creating this as a fully illustrated guide. I'll write something concise up that I can build out later.

**Comment by mvexel** [comment]
Started to write guides on OSM diary

* https://www.openstreetmap.org/user/mvexel/diary/44325
* https://www.openstreetmap.org/user/mvexel/diary/44578

**Comment by mvexel** [comment]
New one: 

* https://www.openstreetmap.org/user/mvexel/diary/46863
