### ISSUE TITLE
Hard to read text when entering keywords

### ISSUE THREAD

**Issue by govvin** [osmlab/maproulette3#960]
When entering keyword text for selecting features to work on, the black text is very difficult to read. (or it must be my rheumy eyes.) White text will probably work better than black.

![](https://i.imgur.com/F3oUL3c.jpg)

**Comment by nrotstan** [comment]
Thanks for reporting this, @govvin , it'll be fixed in the next release.

**Comment by nrotstan** [comment]
Fixed in v3.4.4
