### ISSUE TITLE
504 Gateway Timeout When Trying to Download CSV from Map Roulette

### ISSUE THREAD

**Issue by lmscheurer** [osmlab/maproulette3#970]
Website: https://maproulette.org/api/v2/challenge/10077/tasks/extract?status=0,1,2,3,4,5,6,9&priority=0,1,2&reviewStatus=0,1,2,3,4,-1

Error Message: 
504 Gateway Time-out / nginx/1.14.0 (Ubuntu)

**Comment by nrotstan** [comment]
Thanks for reporting this, @lmscheurer . PR maproulette/maproulette2#639 should significantly improve performance of the CSV generation

**Comment by nrotstan** [comment]
Fixed in v3.4.4. This should now work for you on maproulette.org
