### ISSUE TITLE
automatic challenge update created in Maproulette;

### ISSUE THREAD

**Issue by raphaelpe** [osmlab/maproulette3#980]
Good Morning,

I would suggest to Developers that an automatic update functionality option be created for challenges created in Maproulette and when there were new changes in OSM Maproulette made it available to update on the same existing task.

================================================================
Bom Dia, 

Gostaria de Sugerir aos Desenvolvedores que fosse criado uma opção de funcionalidade de atualização automática para desafios criados no Maproulette e quando a houvesse novas mundanças no OSM o Maproulette disponibilizasse para atualização na mesma tarefa já existente. 

Raphael de Assis.
Recife/PE.

**Comment by nrotstan** [comment]
Thanks for the great suggestion @raphaelpe ! We do have plans to implement this for challenges that use Overpass queries, where the query can be automatically re-run on occasion and the challenge tasks then rebuilt from the latest query results. Right now the challenge owner has to manually click the Rebuild Tasks button to do that.

We could also probably support it for challenges loading GeoJSON from a "remote" URL, where MapRoulette could occasionally re-fetch the and re-process the data from the URL.

**Comment by raphaelpe** [comment]
I hope this suggestion will soon be inserted into maproulette! 

I would also like what option I choose on the overpass site to insert an overpass query into maproulette, Created a query to fix the ZIP Codes of a city more when I copy from Overpass to maproulette gives error when creating the deafio in maproulette , 

I need help creating this task. 

Raphaelpe
Recife/PE.

**Comment by oguzhanerr** [comment]
Hello! Is there any updates on this topic?
