### ISSUE TITLE
Rebuild Tasks should result in Status "finished" when no tasks are created

### ISSUE THREAD

**Issue by Noki** [osmlab/maproulette3#986]
If you rebuild a challenge that is currently in the "finished" state the state becomes "ready" afterwards, even when no new tasks were found.

Expected behaviour:

Status: Ready (if new tasks are found)
Status: Finished (if no new task are found)

In addtion I have a question regarding "Fixed" and "Already fixed" tasks: Will they be set to "created" again, when they are found during rebuild? This is what I would expect.

Best regards
Tobias

**Comment by nrotstan** [comment]
I'm going to reopen this until the fix is included in a release, just to avoid any confusion.

**Comment by nrotstan** [comment]
This should now be fixed on maproulette.org

**Comment by danieldegroot2** [comment]
https://maproulette.org/browse/challenges/27459 looks like a new challenge (May 06, 2022) with no tasks, but is not marked as finished.
