### ISSUE TITLE
Receiving 502 Bad Gateway Error when trying to access Map Roulette website

### ISSUE THREAD

**Issue by lmscheurer** [osmlab/maproulette3#987]
When trying to access the Map Roulette website, I receive the following error: "502 Bad Gateway, nginx/1.14.0 (Ubuntu)"

I am unable to access any challenges.

**Comment by mgcuthbert** [comment]
We are investigating this issue currently. Will update as soon as it is resolved. Thanks for reporting.

**Comment by nrotstan** [comment]
The site is back up, but we'll continue to monitor it closely. Thanks again for the report @lmscheurer .
