### ISSUE TITLE
Issues with the swagger.json

### ISSUE THREAD

**Issue by wtimme** [osmlab/maproulette3#995]
Hey guys,

Thanks for MapRoulette! I was recently looking into creating an API client in Swift (to see what we need to do for bryceco/GoMap#240) using [the swagger.json][1] that you are providing, but ran into some issues. I first thought it was related [SwagGen][2], but when I also had issues with [swagger-codegen][4], I started to doubt the integrity of the JSON file, and looked into ways to verify it.

When importing the JSON into the [Swagger editor][3], I get a lot of error messages, e. g. 

> Structural error at paths./tasks/review/next.get.parameters.5
> should have required property 'type'
> missingProperty: type

or

> Structural error at paths./project/{id}/comments.get
> should NOT have additional properties
> additionalProperty: response

When I put the URL into the [Swagger Inspector][5], I get the error message

> Could not resolve reference: #/definitions/org.maproulette.services.osm.ChangeObjects.TagChange

Since I am not an expert with Swagger, this could very well be a problem on my end. Could you point me in the right direction? Thanks in advance for your help!

[1]: https://maproulette.org/assets/swagger.json
[2]: https://github.com/yonaskolb/SwagGen/tree/swagger_2
[3]: https://editor.swagger.io/
[4]: https://github.com/swagger-api/swagger-codegen
[5]: https://inspector.swagger.io/builder

**Comment by nrotstan** [comment]
Thanks for the report, @wtimme . I'm sure it's our swagger file and not you. We mostly just provide it as a basic reference and will need to address those errors.

**Comment by wtimme** [comment]
Hey folks,

So I was able to kind-of resolve the issues in the Swagger definition file. Some of the issues that I encountered looked as if the file was created/maintained manually, and others caused my auto-generated Swift 5 client to fail, because it apparently does not support the type "date" with the format "epoch".

You can have a look at the commits above, and the file that I pushed. Maybe that helps to find and fix some of the issues. Please note that due to time constraints on my end, I opted to remove a couple of API methods because they caused by build to fail, and I simply don't need them at the moment.

Overall, I am pretty happy that you provided this Swagger definition. After "resolving" the issues, it helped me to auto-generated the Swift 5 client within a couple of seconds. Thanks for your effort! 💪🏼

**Comment by nrotstan** [comment]
The swagger docs should be much improved now (not perfect, but a lot better).
