### ISSUE TITLE
Using MapRoulette for manual imports

### ISSUE THREAD

**Issue by vgeorge** [osmlab/maproulette3#996]
I understand that MapRoullete was designed primarily to fix existing OSM data, but can I use it to manage manual imports to OSM?

My use case is a Brazilian public domain dataset of rural buildings, which consists in 5 million coordinates of locations visited in the Agricultural Census of 2017. 

Data is grouped by city, so I parsed one into a GeoJSON file, generated an id (a plus code derived from the coordinates) and created this challenge:

https://maproulette.org/challenge/11442

I can open the locations via iD link for some tasks, but for others there is a browser error that I can't replicate now. I think iD tries to load an osm object from the point id, but I'm not sure.

Key question: Is there a way to make MapRoullete just open a location in iD, without trying to load an OSM object?

I would also appreciate if anyone has thoughts about using MapRoulette for these kind of manual imports.

**Comment by nrotstan** [comment]
If there is any numeric portion in your feature id, there is an issue where MapRoulette willl treat it as an OSM id when contacting iD even if it obviously isn't one. PR #991 addresses this and will be included in the next release (probably early December).

There are some challenges for adding geometry, such as [Missing road geometry in New Zealand](https://maproulette.org/browse/challenges/3457).

But as far as adding nodes/ways/relations all setup with specific tags and ready to import, we do not currently support that. We do have ["quick-fix" challenges](https://github.com/osmlab/maproulette3/wiki/Creating-Quick-Fix-Challenges) that -- today -- only support tag changes, but there are near-term plans to also support addition of nodes to OSM (and longer-term plans for ways and relations once we see how nodes go). Just nodes is obviously somewhat limiting, but would allow some kinds of challenges to go forward.

**Comment by vgeorge** [comment]
I added fake OSM ids (`node/1`, `node/2`) to the tasks and now they seem to be opening without problems in iD and JOSM. 

Regarding the import of features, it's good to now that you have plans of supporting it in the future. I believe it will be useful in some cases. For this census import I believe its fine to ask people to add a building polygon or a node, it's a really simple task.

Thanks very much for the clarification, @nrotstan. I believe we can close this issue if there isn't any further comments.
