### ISSUE TITLE
open challenges in new tab from find challenges view

### ISSUE THREAD

**Issue by fazlerabbi37** [osmlab/maproulette3#997]
Please add opening challenges in new tab from find challenges view. I think this small change will users a lot. Sometime I just want to check the details of a project so I would want to open the project in a new tab by doing either ctrl + left mouse click or right click -> open in new tab. Now I have to click on each project and then come back to the challenges view and scroll down to the place where I was last.

**Comment by nrotstan** [comment]
Thanks for suggesting this, @fazlerabbi37 . Are you just trying to see the details of the challenge and then get back to where you were in search results? Would a "quick view" that showed you those challenge details without having to leave the search page do what you are looking for?

**Comment by fazlerabbi37** [comment]
While a quick view is good to see a single project summery I think it would be very helpful if each of the challengers were hyperlinked the same way the project leaderboards bellow each challenge are now.

**Comment by mvexel** [comment]
When you click on a Challenge in the list in Find Challenges, it takes you to the same Challenge detail page as do the Challenge links on the Leaderboard. So we already have this behavior. From the way you phrase it, it sounds like you just want to return to the same location in the Challenge list when you click on a Challenge to view the detail page and then go back?
